    ANNUITY COMPUTATION  BY DR. PETER SHENKIN                                   
   AN ANNUITY IS ANY SET OF EQUAL PAYMENTS MADE AT                              
EQUAL INTERVALS OF TIME. WITH AN ORDINARY  ANNUITY                              
PAYMENTS ARE MADE AT THE ENDS OF THE  PERIODS  DE-                              
FINED BY THESE TIME INTERVALS. FOR AN ANNUITY  DUE                              
THE PAYMENTS ARE MADE AT THE BEGINNING OF THE PER-                              
IODS IN QUESTION.  THE PRESENT VALUE OF AN ANNUITY                              
IS THE AMOUNT OF CASH ONE WOULD ACCEPT NOW INSTEAD                              
OF THE SEQUENCE OF FUTURE PAYMENTS. BECAUSE  MONEY                              
HAS TIME VALUE (INTEREST IS CHARGED)  THE  PRESENT                              
VALUE DOES NOT EQUAL THE SUM OF THE PAYMENTS.  tHE                              
FUTURE VALUE OF AN ANNUITY IS THE  AMOUNT  OF CASH                              
WHICH WOULD ACCUMULATE BY THE END  OF THE  ANNUITY                              
IF THE INDIVIDUAL PAYMENTS ARE  INVESTED  AT   THE                              
PREVAILING INTEREST RATE.                                                       
PRESS ENTER TO CONTINUE?                                                        
MANY  ANNUITIES ALSO INVOLVE A LAST BALLOON PAY-                                
MENT.IN THE ANNUITY PROBLEMS WE EXAMINE,THE VARIABLES                           
OF INTEREST ARE  NUMBER OF PAYMENTS,INTEREST RATE PER                           
PERIOD,PAYMENT PER PERIOD,PRESENT OR FUTURE VALUE,AND                           
BALLOON PAYMENT (AT END OF TERM) IF DESIRED.GIVEN ANY                           
FOUR VALUES OF THE ABOVE VARIABLES THIS PROGRAM WILL                            
FIND THE FIFTH VARIABLE WHEN CONSIDERING THE PRESENT                            
VALUE SITUATION. IN THE FUTURE VALUE CASE NO BALLOON                            
PAYMENTS ARE CONSIDERED AS IN THIS CASE A  BALLOON                              
PAYMENT OF A CERTAIN AMOUNT WOULD ADD THAT AMOUNT                               
TO FUTURE VALUE.NOTE THAT INTEREST RATES ARE WRITTEN                            
AS PER CENTS, NOT AS DECIMALS(E.G. 6%, NOT .06). IN                             
ADDITION NOTE THAT INTEREST RATE IS PER PERIOD,I.E.                             
PER MONTH,PER YEAR,ETC.                                                         
                                                                                
PRESS ENTER TO BEGIN?                                                           
SELECT TYPE OF PROBLEM DESIRED.                                                 
     0.QUIT                                                                     
     1.ORDINARY ANNUITY-FUTURE VALUE(SINKING FUND)                              
     2.ANNUITY DUE-FUTURE VALUE                                                 
     3.ORDINARY ANNUITY-PRESENT VALUE                                           
     4.ANNUITY DUE-PRESENT VALUE                                                
                                                                                
MAKE YOUR CHOICE? 1                                                             
                                                                                
IS INTEREST RATE QUOTED PER PERIOD(P) OR ANNUALLY(A)? A                         
                                                                                
NUMBER OF PAYMENTS PER YEAR? 12                                                 
ENTER EACH OF THE FOLLOWING.FOR THE UNKNOWN VALUE                               
ENTER 9999.                                                                     
                                                                                
FUTURE VALUE               ? 2345.67                                            
PAYMENT                    ? 89.01                                              
NUMBER OF PAYMENTS         ? 12                                                 
ANNUAL INTEREST RATE       ? 3.75                                               
FUTURE VALUE        = 2345.67                                                   
NUMBER OF PAYMENTS  = 12                                                        
     CONSISTING OF  12  PAYMENTS ANNUALLY.                                      
ANNUAL INTEREST RATE  = 3.75                                                    
PAYMENT             = 89.01                                                     
                                                                                
PRESS ENTER FOR MORE?                                                           
SELECT TYPE OF PROBLEM DESIRED.                                                 
     0.QUIT                                                                     
     1.ORDINARY ANNUITY-FUTURE VALUE(SINKING FUND)                              
     2.ANNUITY DUE-FUTURE VALUE                                                 
     3.ORDINARY ANNUITY-PRESENT VALUE                                           
     4.ANNUITY DUE-PRESENT VALUE                                                
                                                                                
MAKE YOUR CHOICE? 2                                                             
                                                                                
IS INTEREST RATE QUOTED PER PERIOD(P) OR ANNUALLY(A)? P                         
ENTER EACH OF THE FOLLOWING.FOR THE UNKNOWN VALUE                               
ENTER 9999.                                                                     
                                                                                
FUTURE VALUE               ? 1234.56                                            
PAYMENT                    ? 89.01                                              
NUMBER OF PAYMENTS         ? 36                                                 
INTEREST RATE PER PERIOD(%)? 0.175                                              
FUTURE VALUE        = 1234.56                                                   
NUMBER OF PAYMENTS  = 36                                                        
INT. RATE PER PERIOD= .175                                                      
PAYMENT             = 89.01                                                     
                                                                                
PRESS ENTER FOR MORE?                                                           
SELECT TYPE OF PROBLEM DESIRED.                                                 
     0.QUIT                                                                     
     1.ORDINARY ANNUITY-FUTURE VALUE(SINKING FUND)                              
     2.ANNUITY DUE-FUTURE VALUE                                                 
     3.ORDINARY ANNUITY-PRESENT VALUE                                           
     4.ANNUITY DUE-PRESENT VALUE                                                
                                                                                
MAKE YOUR CHOICE? 3                                                             
                                                                                
IS INTEREST RATE QUOTED PER PERIOD(P) OR ANNUALLY(A)? A                         
                                                                                
NUMBER OF PAYMENTS PER YEAR? 24                                                 
ENTER EACH OF THE FOLLOWING.FOR THE UNKNOWN VALUE                               
ENTER 9999.                                                                     
                                                                                
PRESENT VALUE              ? 1234.56                                            
PAYMENT                    ? 89.01                                              
NUMBER OF PAYMENTS         ? 52                                                 
ANNUAL INTEREST RATE       ? 3.25                                               
BALLOON PAYMENT            ? 9999                                               
PRESENT VALUE       = 1234.56                                                   
NUMBER OF PAYMENTS  = 52                                                        
     CONSISTING OF  24  PAYMENTS ANNUALLY.                                      
ANNUAL INTEREST RATE  = 3.25                                                    
PAYMENT             = 89.01                                                     
BALLOON PAYMENT     =-3467.45                                                   
                                                                                
PRESS ENTER FOR MORE?                                                           
SELECT TYPE OF PROBLEM DESIRED.                                                 
     0.QUIT                                                                     
     1.ORDINARY ANNUITY-FUTURE VALUE(SINKING FUND)                              
     2.ANNUITY DUE-FUTURE VALUE                                                 
     3.ORDINARY ANNUITY-PRESENT VALUE                                           
     4.ANNUITY DUE-PRESENT VALUE                                                
                                                                                
MAKE YOUR CHOICE? 4                                                             
                                                                                
IS INTEREST RATE QUOTED PER PERIOD(P) OR ANNUALLY(A)? P                         
ENTER EACH OF THE FOLLOWING.FOR THE UNKNOWN VALUE                               
ENTER 9999.                                                                     
                                                                                
PRESENT VALUE              ? 1234.56                                            
PAYMENT                    ? 9999                                               
NUMBER OF PAYMENTS         ? 36                                                 
INTEREST RATE PER PERIOD(%)? 5                                                  
BALLOON PAYMENT            ? 55.55                                              
PRESENT VALUE       = 1234.56                                                   
NUMBER OF PAYMENTS  = 36                                                        
INT. RATE PER PERIOD= 5                                                         
PAYMENT             = 70.5051                                                   
BALLOON PAYMENT     = 55.55                                                     
                                                                                
PRESS ENTER FOR MORE?                                                           
SELECT TYPE OF PROBLEM DESIRED.                                                 
     0.QUIT                                                                     
     1.ORDINARY ANNUITY-FUTURE VALUE(SINKING FUND)                              
     2.ANNUITY DUE-FUTURE VALUE                                                 
     3.ORDINARY ANNUITY-PRESENT VALUE                                           
     4.ANNUITY DUE-PRESENT VALUE                                                
                                                                                
MAKE YOUR CHOICE? 0                                                             
