    DEPRECIATION SCHEDULE-SINKING FUND METHOD                                   
THIS PROGRAM PRINTS A SCHEDULE FOR DEPRECIATING AN ASSET                        
BY THE SINKING FUND METHOD. THIS METHOD IS USED BY REGULATED                    
INDUSTRIES QUITE A BIT. IN THIS METHOD THERE ARE EQUAL YEARLY                   
DEPRECIATION CHARGES BUT THE DEPRECIATION IS ASSUMED TO BE                      
INVESTED IN A (SINKING FUND) ACCOUNT EARNING STATED INTEREST.                   
INPUTS ARE ITEM COST,ESTIMATED SALVAGE VALUE, LIFE IN YEARS,                    
AND SINKING FUND INTEREST RATE.                                                 
                                                                                
OUTPUT INCLUDES ANNUAL DEPRECIATION CHARGES PLUS A YEAR BY                      
YEAR SCHEDULE OF BOOK VALUE,INTEREST ON SINKING FUND, INCREASE                  
IN SIZE OF SINKING FUND, AND TOTAL VALUE OF SINKING FUND.                       
                                                                                
 PRESS ENTER TO BEGIN?                                                          
DO YOU WANT OUTPUT ON LINEPRINTER(Y/N)? Y                                       
ENTER  COST              ? 76543                                                
ENTER SALVAGE VALUE      ? 9876                                                 
ENTER LIFE IN YEARS      ? 7                                                    
ENTER INT RATE ON SINKING FUND(%)? 3.75                                         
PRESS ENTER WHEN PRINTER READY?                                                 
                                                                                
ANNUAL DEPRECIATION CHARGES =  8504.96                                          
YEAR    BOOK VAL.    FUND INT.   INCR. IN FUND   FUND VAL.                      
  0      76543.00                                                               
  1      68038.04         0.00       8504.96       8504.96                      
  2      59214.15       318.94       8823.89      17328.85                      
  3      50059.37       649.83       9154.79      26483.63                      
  4      40561.27       993.14       9498.09      35981.73                      
  5      30707.00      1349.31       9854.27      45836.00                      
  6      20483.20      1718.85      10223.81      56059.80                      
  7       9876.00      2102.24      10607.20      66667.00                      
