    DEPRECIATION SCHEDULE-DOUBLE DECLINING BALANCE                              
THIS PROGRAM PRINTS A SCHEDULE FOR DEPRECIATING AN ASSET                        
BY THE DOUBLE DECLINING BALANCE METHOD                                          
INPUTS ARE ITEM COST,ESTIMATED SALVAGE VALUE & LIFE IN YEARS.                   
OUTPUT IS A YEAR BY YEAR SCHEDULE OF CURRENT DEPRECIATION,                      
ACCUMULATED DEPRECIATION AND BOOK VALUE.                                        
 PRESS ENTER TO BEGIN?                                                          
DO YOU WANT OUTPUT ON LINEPRINTER(Y/N)? Y                                       
ENTER  COST              ? 987654                                               
ENTER SALVAGE VALUE      ? 2345                                                 
ENTER LIFE IN YEARS      ? 5                                                    
PRESS ENTER WHEN PRINTER READY?                                                 
                                                                                
YEAR    CURR.DEP.     ACCUM.DEP.       BOOK VAL. !                              
  0                                    987654.00                                
  1    395061.60       395061.60       592592.40                                
  2    237036.96       632098.56       355555.44                                
  3    142222.18       774320.74       213333.26                                
  4     85333.31       859654.04       127999.96                                
  5    125654.96       985309.00         2345.00                                
