              ENVELOPE WRITING PROGRAM                                          
THIS PROGRAM WILL GENERATE A PRINTED ENVELOPE ON A LINE                         
PRINTER. UNLESS TRACTOR FED ENVELOPES ARE AVAILABLE A FRICTION                  
FEED PRINTER MUST BE HOOKED UP TO THE SYSTEM. THE USER                          
INPUTS A RETURN ADDRESS,AN ADDRESS, THE LENGTH OF THE ENVELOPE                  
IN LINES(6 LINES TO THE INCH), AND NUMBER OF COPIES. MANY                       
OF THE INPUT VALUES MAY BE REPEATED ON SEVERAL ENVELOPES                        
WITHOUT ADDITIONAL INPUT.                                                       
                                                                                
PRESS ENTER TO BEGIN?                                                           
              MENU                                                              
                                                                                
0. QUIT                                                                         
1. INPUT RETURN ADDRESS                                                         
2. INPUT MAIL TO ADDRESS                                                        
3. PRINT ENVELOPE ON SCREEN                                                     
4. PRINT ENVELOPE ON PRINTER                                                    
5. CLEAR DATA:READY FOR NEW ENVELOPE                                            
6. CHANGE PRINT TABS FOR RETURN ADDRESS OR MAIL TO ADDRESS                      
7. CHANGE # LINES ON ENVELOPE                                                   
                                                                                
MAKE YOUR CHOICE? 1                                                             
NO COMMAS IN THE FOLLOWING, PLEASE.                                             
                                                                                
NO COMMAS IN THE FOLLOWING, PLEASE.                                             
                                                                                
ENTER LINE # 1  OF RETURN ADDRESS(-1 FOR EMPTY)                                 
? TOM CAT                                                                       
ENTER LINE # 2  OF RETURN ADDRESS(-1 FOR EMPTY)                                 
? 123 FUNNY STREET                                                              
ENTER LINE # 3  OF RETURN ADDRESS(-1 FOR EMPTY)                                 
? "SOMEWHERE, TX 98765"                                                         
ENTER LINE # 4  OF RETURN ADDRESS(-1 FOR EMPTY)                                 
? -1                                                                            
              MENU                                                              
                                                                                
0. QUIT                                                                         
1. INPUT RETURN ADDRESS                                                         
2. INPUT MAIL TO ADDRESS                                                        
3. PRINT ENVELOPE ON SCREEN                                                     
4. PRINT ENVELOPE ON PRINTER                                                    
5. CLEAR DATA:READY FOR NEW ENVELOPE                                            
6. CHANGE PRINT TABS FOR RETURN ADDRESS OR MAIL TO ADDRESS                      
7. CHANGE # LINES ON ENVELOPE                                                   
                                                                                
MAKE YOUR CHOICE? 2                                                             
                                                                                
NO COMMAS IN THE FOLLOWING, PLEASE.                                             
                                                                                
ENTER LINE # 1  OF MAIL TO ADDRESS(-1 FOR EMPTY)                                
? JERRY MOUSE                                                                   
ENTER LINE # 2  OF MAIL TO ADDRESS(-1 FOR EMPTY)                                
? 567 CARTOON LANE                                                              
ENTER LINE # 3  OF MAIL TO ADDRESS(-1 FOR EMPTY)                                
? "ANYWHERE, TX 12345"                                                          
ENTER LINE # 4  OF MAIL TO ADDRESS(-1 FOR EMPTY)                                
? -1                                                                            
              MENU                                                              
                                                                                
0. QUIT                                                                         
1. INPUT RETURN ADDRESS                                                         
2. INPUT MAIL TO ADDRESS                                                        
3. PRINT ENVELOPE ON SCREEN                                                     
4. PRINT ENVELOPE ON PRINTER                                                    
5. CLEAR DATA:READY FOR NEW ENVELOPE                                            
6. CHANGE PRINT TABS FOR RETURN ADDRESS OR MAIL TO ADDRESS                      
7. CHANGE # LINES ON ENVELOPE                                                   
                                                                                
MAKE YOUR CHOICE? 3                                                             
                                                                                
 TOM CAT                                                                        
 123 FUNNY STREET                                                               
 SOMEWHERE, TX 98765                                                            
                                                                                
                                                                                
                                                                                
                                                                                
                             JERRY MOUSE                                        
                             567 CARTOON LANE                                   
                             ANYWHERE, TX 12345                                 
                                                                                
                                                                                
PRESS ENTER TO CONTINUE?                                                        
              MENU                                                              
                                                                                
0. QUIT                                                                         
1. INPUT RETURN ADDRESS                                                         
2. INPUT MAIL TO ADDRESS                                                        
3. PRINT ENVELOPE ON SCREEN                                                     
4. PRINT ENVELOPE ON PRINTER                                                    
5. CLEAR DATA:READY FOR NEW ENVELOPE                                            
6. CHANGE PRINT TABS FOR RETURN ADDRESS OR MAIL TO ADDRESS                      
7. CHANGE # LINES ON ENVELOPE                                                   
                                                                                
MAKE YOUR CHOICE? 4                                                             
HOW MANY ENVELOPES DO YOU DESIRE? 1                                             
PRESS ENTER TO CONTINUE?                                                        
                                                                                
              MENU                                                              
                                                                                
0. QUIT                                                                         
1. INPUT RETURN ADDRESS                                                         
2. INPUT MAIL TO ADDRESS                                                        
3. PRINT ENVELOPE ON SCREEN                                                     
4. PRINT ENVELOPE ON PRINTER                                                    
5. CLEAR DATA:READY FOR NEW ENVELOPE                                            
6. CHANGE PRINT TABS FOR RETURN ADDRESS OR MAIL TO ADDRESS                      
7. CHANGE # LINES ON ENVELOPE                                                   
                                                                                
MAKE YOUR CHOICE? 0                                                             
