         INSURANCE POLICY FILE                                                  
                                                                                
THIS SIMPLE PROGRAM WILL PERMIT THE INDIVIDUAL OR SMALL                         
BUSINESS TO STORE DATA ABOUT THE PORTFOLIO OF ALL INSURANCE                     
POLICIES HELD. FOR EACH POLICY THE FOLLOWING DATA MAY BE                        
STORED: TYPE INSURANCE,DESCRIPTION,DATE EXPIRES,INSURANCE                       
COMPANY,UNDERWRITER, POLICY NUMBER, FACE AMOUNT, AND ANNUAL                     
PREMIUM. THE FILE MAY BE STORED ON CASSETTE OR DISKETTE AND                     
RECALLED. THE POLICIES MAY BE LISTED EITHER IN FULL OR BY TYPE                  
WITH SUMMARIES OF TOTAL POLICY FACE VALUES AND PREMIUMS.                        
A PROVISION FOR A MAXIMUM OF 70 POLICIES IS MADE.                               
                                                                                
PRESS ENTER TO BEGIN?                                                           
ARE DISK DRIVES ATTACHED(Y/N)? Y                                                
       MAIN MENU                                                                
                                                                                
 0.QUIT                                                                         
 1.ADD TO FILE OR BEGIN NEW FILE                                                
 2.READ FILE IN FROM TAPE                                                       
 3.WRITE FILE OUT ONTO TAPE                                                     
 4.READ FILE IN FROM DISK                                                       
 5.WRITE FILE OUT ONTO DISK                                                     
 6.EDIT FILE                                                                    
 7.LIST CONTENTS, COMPLETE OR BY TYPE                                           
 8.ROUTINE ACTUALLY DELETING RECORD FROM FILE                                   
ENTER YOUR CHOICE? 1                                                            
NEW FILE                                                                        
PRESS ENTER TO CONTINUE?                                                        
                          TYPE INSUR.      ? HOME                               
                          POL. DESCRIPTION ? HOME OWNERS                        
                          DATE EXPIRES     ? 01/23/45                           
                          COMPANY WRITING  ? GEICO                              
                          UNDERWRITER      ? LIZARD                             
                          POLICY NUMBER    ? AB/23-67*D                         
         0.00                FACE AMOUNT    ? 5000                              
         0.00                ANNUAL PREMIUM ? 12.50                             
TYPE  DESCRIPT  EXPIRES  CO.  UNDWRT   POL  #    AMT.    PREM                   
HOME HOME OWNE 01/23/45  GEI  LIZAR  AB/23-67*D    5000    12                   
ENTER Y IF OK,N IF ERROR,A TO ABORT? Y                                          
DO YOU DESIRE MORE ENTRIES(Y/N)? Y                                              
                          TYPE INSUR.      ? RENTERS                            
                          POL. DESCRIPTION ? WATER DAMAGE                       
                          DATE EXPIRES     ? 98/76/54                           
                          COMPANY WRITING  ? FLO                                
                          UNDERWRITER      ? LADY                               
                          POLICY NUMBER    ? ??%^&*                             
         0.00                FACE AMOUNT    ? 500                               
         0.00                ANNUAL PREMIUM ? 2.50                              
TYPE  DESCRIPT  EXPIRES  CO.  UNDWRT   POL  #    AMT.    PREM                   
RENT WATER DAM 98/76/54  FLO  LADY   ??%^&*         500     2                   
ENTER Y IF OK,N IF ERROR,A TO ABORT? Y                                          
DO YOU DESIRE MORE ENTRIES(Y/N)? N                                              
       MAIN MENU                                                                
                                                                                
 0.QUIT                                                                         
 1.ADD TO FILE OR BEGIN NEW FILE                                                
 2.READ FILE IN FROM TAPE                                                       
 3.WRITE FILE OUT ONTO TAPE                                                     
 4.READ FILE IN FROM DISK                                                       
 5.WRITE FILE OUT ONTO DISK                                                     
 6.EDIT FILE                                                                    
 7.LIST CONTENTS, COMPLETE OR BY TYPE                                           
 8.ROUTINE ACTUALLY DELETING RECORD FROM FILE                                   
ENTER YOUR CHOICE? 5                                                            
                                                                                
PUT DATA DISK IN DISK DRIVE                                                     
PRESS ENTER TO CONTINUE?                                                        
                                                                                
PRESENT DISK FILE IS  NEW FILE ? INSFILE.DAT                                    
       MAIN MENU                                                                
                                                                                
 0.QUIT                                                                         
 1.ADD TO FILE OR BEGIN NEW FILE                                                
 2.READ FILE IN FROM TAPE                                                       
 3.WRITE FILE OUT ONTO TAPE                                                     
 4.READ FILE IN FROM DISK                                                       
 5.WRITE FILE OUT ONTO DISK                                                     
 6.EDIT FILE                                                                    
 7.LIST CONTENTS, COMPLETE OR BY TYPE                                           
 8.ROUTINE ACTUALLY DELETING RECORD FROM FILE                                   
ENTER YOUR CHOICE? 4                                                            
PUT DATA DISK IN DISK DRIVE                                                     
PRESS ENTER TO CONTINUE?                                                        
                                                                                
ENTER NAME OF FILE TO READ IN? INSFILE.DAT                                      
       MAIN MENU                                                                
                                                                                
 0.QUIT                                                                         
 1.ADD TO FILE OR BEGIN NEW FILE                                                
 2.READ FILE IN FROM TAPE                                                       
 3.WRITE FILE OUT ONTO TAPE                                                     
 4.READ FILE IN FROM DISK                                                       
 5.WRITE FILE OUT ONTO DISK                                                     
 6.EDIT FILE                                                                    
 7.LIST CONTENTS, COMPLETE OR BY TYPE                                           
 8.ROUTINE ACTUALLY DELETING RECORD FROM FILE                                   
ENTER YOUR CHOICE? 7                                                            
IS A LINE PRINTER TO BE USED(Y/N)? Y                                            
           LIST  MENU                                                           
                                                                                
1. COMPLETE LIST AS ON FILE                                                     
2. LIST BY TYPE                                                                 
3. END LIST PROGRAM                                                             
                                                                                
ENTER APPROPRIATE CHOICE? 1                                                     
PUT PAPER INTO PRINTER                                                          
PRESS ENTER TO CONTINUE?                                                        
TYPE  DESCRIPT  EXPIRES  CO.  UNDWRT   POL  #    AMT.    PREM                   
HOME HOME OWNE 01/23/45  GEI  LIZAR  AB/23-67*D    5000    12                   
RENT WATER DAM 98/76/54  FLO  LADY   ??%^&*         500     2                   
                                                                                
PRESS ENTER TO CONTINUE?                                                        
TOTAL FACE VALUE AMOUNT :   $5500.00                                            
TOTAL PREMIUM AMOUNT    :     $15.00                                            
                                                                                
PRESS ENTER TO CONTINUE?                                                        
           LIST  MENU                                                           
                                                                                
1. COMPLETE LIST AS ON FILE                                                     
2. LIST BY TYPE                                                                 
3. END LIST PROGRAM                                                             
                                                                                
ENTER APPROPRIATE CHOICE? 3                                                     
       MAIN MENU                                                                
                                                                                
 0.QUIT                                                                         
 1.ADD TO FILE OR BEGIN NEW FILE                                                
 2.READ FILE IN FROM TAPE                                                       
 3.WRITE FILE OUT ONTO TAPE                                                     
 4.READ FILE IN FROM DISK                                                       
 5.WRITE FILE OUT ONTO DISK                                                     
 6.EDIT FILE                                                                    
 7.LIST CONTENTS, COMPLETE OR BY TYPE                                           
 8.ROUTINE ACTUALLY DELETING RECORD FROM FILE                                   
ENTER YOUR CHOICE? 0                                                            
