        INVENTORY CONTROL FOR TRS-80                                            
                   BY DR. PETER SHENKIN                                         
 *******************************************************                        
THIS PROGRAM IS A RELATIVELY COMPLETE INVENTORY CONTROL PROGRAM                 
THE ONLY REAL LIMITATION OF WHICH IS THAT IT IS IN MEMORY AND                   
THUS ONLY HANDLES 50 DIFFERENT INVENTORY ITEMS. ACTUALLY                        
THIS LIMITATION MAY BE RELAXED BY CHANGING THE APPROPRIATE                      
DIMENSION STATEMENTS IF ENOUGH MEMORY IS AVAILABLE.                             
   THE PROGRAM SUPPORTS LINE PRINTER OUTPUT AND ALLOWS THE                      
THE INVENTORY FILE TO BE STORED ON EITHER CASSETTE OR DISKETTE.                 
REPORTS INCLUDE A LIST OF ALL DATA AND AN ACTIVITY REPORT                       
WHICH OUTLINE PAST ACTIVITY FOR EACH ITEM. AN AVERAGE COST IS                   
KEPT UPDATED FOR EACH ITEM.                                                     
 *****************************************************+                         
                                                                                
PRESS ENTER TO CONTINUE?                                                        
ARE DISK DRIVES ATTACHED(Y/N)? Y                                                
          INVENTORY CONTROL                                                     
 ENTER NUMBER OF DESIRED OPTION.                                                
                                                                                
1.ADD ITEM TYPES TO INVENTORY FILE(OR START FILE)                               
2.INVENTORY LIST(ENTIRE OR BY CLASS OR BY VENDOR)                               
3.PROCESSING CHANGES OF INVENTORY AMOUNTS                                       
4.READ INVENTORY FILE FROM CASSETTE                                             
5.READ INVENTORY FILE IN FROM DISKETTE                                          
6.WRITE INVENTORY FILE ONTO CASSETTE                                            
7.WRITE INVENTORY FILE ONTO DISKETTE                                            
8.UPDATE TO BEGIN NEW INVENTORY PERIOD                                          
9.ACTIVITY REPORT                                                               
10.EDITING INVENTORY FILE                                                       
11.END THIS PROGRAM                                                             
                                                                                
INPUT OPTION NUMBER & PRESS ENTER? 1                                            
ADDITIONAL INVENTORY ITEM SUBROUTINE                                            
                                                                                
HAS ANY EXISTING FILE BEEN READ FROM TAPE OR DISKETTE?(Y/N);                    
? Y                                                                             
INPUT DATA FOR NEXT ITEM.                                                       
                                                                                
ITEM NUMBER               ? A56-C7                                              
DESCRIPTION( < 20 CHAR)   ? MOUSE PAD                                           
VENDOR NUMBER             ? JM-5*D                                              
QUANTITY ON HAND          ? 125                                                 
LAST ORDER UNIT COST      ? 2.50                                                
SELLING PRICE             ? 9.99                                                
AVERAGE UNIT COST         ? 3.33                                                
REORDER POINT             ? 100                                                 
MAXIMUM INVENTORY         ? 1000                                                
# SOLD THIS INV. PERIOD   ? 750                                                 
# SOLD LAST INV. PERIOD   ? 931                                                 
# SOLD 2 INV. PER. AGO    ? 593                                                 
ITEM NO.     : A56-C7   DESCRIP. :MOUSE PAD                                     
VENDOR NO.   : JM-5*D                                                           
QUANT. ON HAND:  125  LAST  UNIT COST: 2.5                                      
SELLING PR. : 9.99    AVERAGE COST :  3.33                                      
REORDER PT.:  100   MAX INV.:  1000                                             
ORDERS THIS INV. PERIOD :  750                                                  
ORdERS LAST INV. PER: 931  PREV. PER: 593                                       
                                                                                
                                                                                
IF OK PRESS 1,OTHERWISE PRESS 0? 1                                              
DO YOU DESIRE MORE ENTRIES ?(Y/N)                                               
? N                                                                             
          INVENTORY CONTROL                                                     
 ENTER NUMBER OF DESIRED OPTION.                                                
                                                                                
1.ADD ITEM TYPES TO INVENTORY FILE(OR START FILE)                               
2.INVENTORY LIST(ENTIRE OR BY CLASS OR BY VENDOR)                               
3.PROCESSING CHANGES OF INVENTORY AMOUNTS                                       
4.READ INVENTORY FILE FROM CASSETTE                                             
5.READ INVENTORY FILE IN FROM DISKETTE                                          
6.WRITE INVENTORY FILE ONTO CASSETTE                                            
7.WRITE INVENTORY FILE ONTO DISKETTE                                            
8.UPDATE TO BEGIN NEW INVENTORY PERIOD                                          
9.ACTIVITY REPORT                                                               
10.EDITING INVENTORY FILE                                                       
11.END THIS PROGRAM                                                             
                                                                                
INPUT OPTION NUMBER & PRESS ENTER? 7                                            
PREPARE INVENTORY MASTER DISKETTE                                               
PRESS ENTER WHEN READY?                                                         
                                                                                
THERE ARE  1  ITEMS                                                             
          INVENTORY CONTROL                                                     
 ENTER NUMBER OF DESIRED OPTION.                                                
                                                                                
1.ADD ITEM TYPES TO INVENTORY FILE(OR START FILE)                               
2.INVENTORY LIST(ENTIRE OR BY CLASS OR BY VENDOR)                               
3.PROCESSING CHANGES OF INVENTORY AMOUNTS                                       
4.READ INVENTORY FILE FROM CASSETTE                                             
5.READ INVENTORY FILE IN FROM DISKETTE                                          
6.WRITE INVENTORY FILE ONTO CASSETTE                                            
7.WRITE INVENTORY FILE ONTO DISKETTE                                            
8.UPDATE TO BEGIN NEW INVENTORY PERIOD                                          
9.ACTIVITY REPORT                                                               
10.EDITING INVENTORY FILE                                                       
11.END THIS PROGRAM                                                             
                                                                                
INPUT OPTION NUMBER & PRESS ENTER? 2                                            
CHOOSE DESIRED OPTION AND PRESS ENTER                                           
1. COMPLETE INVENTORY LIST                                                      
2. INVENTORY LIST BY VENDOR                                                     
3. LIST OF ITEMS BELOW REORDER POINT                                            
OPTION # ? 1                                                                    
IS PRINTED OUTPUT DESIRED(Y/N)? Y                                               
ITEM NO.     : A56-C7   DESCRIP. :MOUSE PAD                                     
VENDOR NO.   : JM-5*D                                                           
QUANT. ON HAND:  125  LAST  UNIT COST: 2.5                                      
SELLING PR. : 9.99    AVERAGE COST :  3.33                                      
REORDER PT.:  100   MAX INV.:  1000                                             
ORDERS THIS INV. PERIOD :  750                                                  
ORdERS LAST INV. PER: 931  PREV. PER: 593                                       
                                                                                
          INVENTORY CONTROL                                                     
 ENTER NUMBER OF DESIRED OPTION.                                                
                                                                                
1.ADD ITEM TYPES TO INVENTORY FILE(OR START FILE)                               
2.INVENTORY LIST(ENTIRE OR BY CLASS OR BY VENDOR)                               
3.PROCESSING CHANGES OF INVENTORY AMOUNTS                                       
4.READ INVENTORY FILE FROM CASSETTE                                             
5.READ INVENTORY FILE IN FROM DISKETTE                                          
6.WRITE INVENTORY FILE ONTO CASSETTE                                            
7.WRITE INVENTORY FILE ONTO DISKETTE                                            
8.UPDATE TO BEGIN NEW INVENTORY PERIOD                                          
9.ACTIVITY REPORT                                                               
10.EDITING INVENTORY FILE                                                       
11.END THIS PROGRAM                                                             
                                                                                
INPUT OPTION NUMBER & PRESS ENTER? 5                                            
PLACE INVENTORY DATA DISKETTE IN DRIVE.                                         
PRESS ENTER WHEN READY?                                                         
                                                                                
 1  ITEMS TO BE READ                                                            
          INVENTORY CONTROL                                                     
 ENTER NUMBER OF DESIRED OPTION.                                                
                                                                                
1.ADD ITEM TYPES TO INVENTORY FILE(OR START FILE)                               
2.INVENTORY LIST(ENTIRE OR BY CLASS OR BY VENDOR)                               
3.PROCESSING CHANGES OF INVENTORY AMOUNTS                                       
4.READ INVENTORY FILE FROM CASSETTE                                             
5.READ INVENTORY FILE IN FROM DISKETTE                                          
6.WRITE INVENTORY FILE ONTO CASSETTE                                            
7.WRITE INVENTORY FILE ONTO DISKETTE                                            
8.UPDATE TO BEGIN NEW INVENTORY PERIOD                                          
9.ACTIVITY REPORT                                                               
10.EDITING INVENTORY FILE                                                       
11.END THIS PROGRAM                                                             
                                                                                
INPUT OPTION NUMBER & PRESS ENTER? 2                                            
CHOOSE DESIRED OPTION AND PRESS ENTER                                           
1. COMPLETE INVENTORY LIST                                                      
2. INVENTORY LIST BY VENDOR                                                     
3. LIST OF ITEMS BELOW REORDER POINT                                            
OPTION # ? 2                                                                    
IS PRINTED OUTPUT DESIRED(Y/N)? Y                                               
DESIRED VENDOR NUMBER ? JM-5*D                                                  
ITEM NO.     : A56-C7   DESCRIP. :MOUSE PAD                                     
VENDOR NO.   : JM-5*D                                                           
QUANT. ON HAND:  125  LAST  UNIT COST: 2.5                                      
SELLING PR. : 9.99    AVERAGE COST :  3.33                                      
REORDER PT.:  100   MAX INV.:  1000                                             
ORDERS THIS INV. PERIOD :  750                                                  
ORdERS LAST INV. PER: 931  PREV. PER: 593                                       
                                                                                
          INVENTORY CONTROL                                                     
 ENTER NUMBER OF DESIRED OPTION.                                                
                                                                                
1.ADD ITEM TYPES TO INVENTORY FILE(OR START FILE)                               
2.INVENTORY LIST(ENTIRE OR BY CLASS OR BY VENDOR)                               
3.PROCESSING CHANGES OF INVENTORY AMOUNTS                                       
4.READ INVENTORY FILE FROM CASSETTE                                             
5.READ INVENTORY FILE IN FROM DISKETTE                                          
6.WRITE INVENTORY FILE ONTO CASSETTE                                            
7.WRITE INVENTORY FILE ONTO DISKETTE                                            
8.UPDATE TO BEGIN NEW INVENTORY PERIOD                                          
9.ACTIVITY REPORT                                                               
10.EDITING INVENTORY FILE                                                       
11.END THIS PROGRAM                                                             
                                                                                
INPUT OPTION NUMBER & PRESS ENTER? 11                                           
ARE YOU SURE YOU WISH TO END PROGRAM(Y/N)? Y                                    
