               LEASE INTEREST RATE                                              
THERE ARE MANY TYPES OF EQUIPMENT LEASES. ONE TYPE OF AUTO                      
LEASE IS CALLED AN OPEN END LEASE. THE WAY IT WORKS IS THAT                     
THE LESSEE PAYS THE LEASING COMPANY A DOWN PAYMENT AND A FIXED                  
AMOUNT EACH MONTH FOR A GIVEN NUMBER OF MONTHS. AT THE END                      
OF THE LEASE PERIOD THE LESSEE MUST PAY THE LEASING COMPANY A                   
PRE-AGREED AMOUNT (BUY-BACK AMOUNT). THE LESSEE THEN OWNS THE                   
CAR. THERE ARE SEVERAL ADVANTAGES TO LEASING. IF THE INITIAL                    
DOWN PAYMENT IS LOW AND PAYMENTS ARE LESS PER MONTH THAN ON A                   
STRAIGHT LOAN THEN THE LESSEE PAYS LESS MONEY EARLY THAN                        
ON THE LOAN. THE BALLOON PAYMENT MAKES UP FOR THIS LATER.                       
THE PRESENT PROGRAM COMPUTES AN EFFECTIVE INTEREST RATE ON THE                  
LEASE GIVEN THE PURCHASE PRICE OF THE CAR, THE DOWN PAYMENT                     
THE MONTHLY PAYMENT, AND THE BUY-BACK AMOUNT.                                   
                                                                                
PRESS ENTER TO BEGIN ?                                                          
IT IS ASSUMED THAT THE BUY-BACK OCCURS ONE MONTH AFTER THE                      
LAST PAYMENT. IF THE LAST PAYMENT AND THE BUY-BACK OCCUR AT                     
THE SAME TIME THEN DECREASE THE NUMBER OF PAYMENTS BY 1 AND                     
INCREASE THE BUY-BACK BY THE AMOUNT OF 1 PAYMENT                                
                                                                                
   IN ADDITION, THE FIRST PAYMENT MAY BE AT THE END OF THE                      
1ST MONTH, 2ND MONTH, ETC.                                                      
                                                                                
INPUT CASH COST OF ITEM          ? 10000                                        
INPUT DOWN PAYMENT               ? 2000                                         
INPUT MONTHLY PAYMENT            ? 300                                          
INPUT NUMBER OF MONTHLY PAYMENTS ? 50                                           
INPUT MONTH OF 1ST PAYMENT       ? 1                                            
INPUT BUY-BACK AMOUNT            ? 6000                                         
                                                                                
                                                                                
                                                                                
COMPUTING INTEREST RATE                                                         
PASS 0     CURRENT MONTHLY RATE = 0 %                                           
PASS 1     CURRENT MONTHLY RATE = 10 %                                          
PASS 2     CURRENT MONTHLY RATE = 1 %                                           
PASS 3     CURRENT MONTHLY RATE = 2 %                                           
PASS 4     CURRENT MONTHLY RATE = 3 %                                           
PASS 5     CURRENT MONTHLY RATE = 4 %                                           
PASS 6     CURRENT MONTHLY RATE = 3.1 %                                         
PASS 7     CURRENT MONTHLY RATE = 3.2 %                                         
PASS 8     CURRENT MONTHLY RATE = 3.3 %                                         
PASS 9     CURRENT MONTHLY RATE = 3.4 %                                         
PASS 10     CURRENT MONTHLY RATE = 3.5 %                                        
PASS 11     CURRENT MONTHLY RATE = 3.6 %                                        
PASS 12     CURRENT MONTHLY RATE = 3.51 %                                       
PASS 13     CURRENT MONTHLY RATE = 3.52 %                                       
PASS 14     CURRENT MONTHLY RATE = 3.53 %                                       
PASS 15     CURRENT MONTHLY RATE = 3.54 %                                       
PASS 16     CURRENT MONTHLY RATE = 3.55 %                                       
PASS 17     CURRENT MONTHLY RATE = 3.541 %                                      
PASS 18     CURRENT MONTHLY RATE = 3.542 %                                      
MONTHLY INTEREST RATE      =   3.542 %                                          
ANNUAL INTEREST RATE(EFF)  =  51.8443 %                                         
ANNUAL INTEREST RATE(SIMP) =  42.504 %                                          
                                                                                
         INTEREST RATE(SIMP) COMPUTED BY MULTIPLYING                            
         MONTHLY INTEREST RATE BY 12 WHILE INTEREST                             
         RATE(SIMP) IS A COMPOUNDED MONTHLY RATE                                
                                                                                
PRESS ENTER FOR MORE COMPUTATIONS? -1                                           
