         MONEY MULTIPLIER                                                       
                                                                                
THIS PROGRAM COMPUTES HOW LONG IT WILL TAKE AN INVESTOR                         
TO DOUBLE,TRIPLE, MULTIPLY BY 4, ETC.  HIS/HER MONEY INVESTED                   
AT A KNOWN INTEREST RATE.                                                       
                                                                                
COMPUTATIONS MAY BE DONE WHEN RATES ARE QUOTED ANNUALYY OR                      
PER PERIOD(TIME BETWEEN COMPOUNDINGS). IN THE ANNUAL CASE                       
IT IS NECESSARY TO GIVE THE NUMBER OF TIMES PER YEAR                            
INTEREST IS COMPOUNDED(NUMBER OF INTEREST PERIODS).                             
                                                                                
PRESS ENTER TO BEGIN ?                                                          
      DOUBLE MONEY MENU                                                         
                                                                                
0. QUIT                                                                         
1. INTEREST RATES & TIME MEASURED ANNUALLY                                      
2. INTEREST RATES & TIME MEASURED BY PERIOD                                     
                                                                                
ENTER YOUR CHOICE? 1                                                            
ENTER ANNUAL INTEREST RATE IN %, E.G. 5% ENTERED AS 5? 3.75                     
                                                                                
WE NOW WANT THE NUMBER OF COMPOUNDING PERIODS PER YEAR.                         
IF THIS IS DAILY THEN SOME BANKS USE 360 & SOME 365                             
ENTER NUMBER? 12                                                                
                                                                                
ENTER THE FACTOR BY WHICH YOU DESIRE TO INCREASE YOUR FUNDS.                    
E.G. TO DOUBLE INPUT 2,TRIPLE 3, ETC. ? 10                                      
                                                                                
                                                                                
                                                                                
INTEREST RATE & TIME MEASURED ANNUALLY                                          
                                                                                
ANNUAL INTEREST RATE EQUALS  3.75 PER CENT                                      
INTEREST COMPOUNDED  12 TIMES PER YEAR                                          
                                                                                
TIME NECESSARY TO MULTIPLY ACCOUNT BY 10 EQUALS  61.4982 YEARS                  
                                                                                
ACTUALLY THIS TAKES BETWEEN  737  AND 738  INTEREST PERIODS                     
OR BETWEEN  61.4167  AND 61.5  YEARS                                            
 THE EXACT AMOUNT OF TIME NEEDED DEPENDS UPON HOW INTEREST                      
IS CREDITED WITHIN AN INTEREST PERIOD.                                          
                                                                                
ENTER Y FOR MORE COMPUTATIONS, N TO END ? Y                                     
      DOUBLE MONEY MENU                                                         
                                                                                
0. QUIT                                                                         
1. INTEREST RATES & TIME MEASURED ANNUALLY                                      
2. INTEREST RATES & TIME MEASURED BY PERIOD                                     
                                                                                
ENTER YOUR CHOICE? 2                                                            
ENTER INTEREST RATE PER PERIOD IN % ,E.G. 5% ENTERED AS 5? 1.25                 
                                                                                
ENTER THE FACTOR BY WHICH YOU DESIRE TO INCREASE YOUR FUNDS.                    
E.G. TO DOUBLE INPUT 2,TRIPLE 3, ETC. ? 3                                       
                                                                                
                                                                                
                                                                                
INTEREST RATE AND TIME MEASURED PER PERIOD                                      
                                                                                
PER PERIOD INTEREST RATE EQUALS  1.25 PER CENT                                  
                                                                                
TIME NEEDED TO MULTIPLY ACCOUNT BY 3 EQUALS  88.4372  INTEREST PERIODS          
                                                                                
ACTUALLY THIS TAKES BETWEEN  88 AND 89 INTEREST PERIODS                         
 THE EXACT AMOUNT OF TIME NEEDED DEPENDS UPON HOW INTEREST                      
IS CREDITED WITHIN AN INTEREST PERIOD.                                          
                                                                                
ENTER Y FOR MORE COMPUTATIONS, N TO END ? Y                                     
      DOUBLE MONEY MENU                                                         
                                                                                
0. QUIT                                                                         
1. INTEREST RATES & TIME MEASURED ANNUALLY                                      
2. INTEREST RATES & TIME MEASURED BY PERIOD                                     
                                                                                
ENTER YOUR CHOICE? 0                                                            
