THIS PROGRAM IS A SIMPLE STOCK PORTFOLIO PROGRAM. IT WILL                       
 PERMIT THE USER TO STORE DATA ABOUT HIS PORTFOLIO OF SECURIT-                  
IES AS WELL AS GIVE A PROFIT ANALYSIS OF THE PORTFOLIO.                         
FOR EACH SECURITY WE STORE STOCK TICKER CODE,COMPANY NAME                       
DATE OF PURCHASE, # UNITS PURCHASED, PURCHASE PR/UNIT,                          
PRESENT PR/UNIT, YEARLY DIVIDENDS/UNIT.                                         
                                                                                
 THE ANALYSIS COMPUTES SUCH ELEMENTS AS PORTFOLIO AT COST.                      
PRESENT VALUE OF PORTFOLIO, PRESENT YIELD, ETC.                                 
                                                                                
PRESS ENTER TO BEGIN?                                                           
ARE DISK DRIVES ATTACHED(Y/N)? Y                                                
       MAIN MENU                                                                
                                                                                
 0.QUIT                                                                         
 1.ADD TO FILE OR BEGIN NEW FILE                                                
 2.READ FILE IN FROM TAPE                                                       
 3.WRITE FILE OUT ONTO TAPE                                                     
 4.READ FILE IN FROM DISK                                                       
 5.WRITE FILE OUT ONTO DISK                                                     
 6.EDIT FILE                                                                    
 7.LIST FILE AND PROFIT ANALYSIS                                                
 8.ROUTINE ACTUALLY DELETING RECORD FROM FILE                                   
ENTER YOUR CHOICE? 1                                                            
NEW FILE                                                                        
PRESS ENTER TO CONTINUE?                                                        
                          STOCK TICKER CODE? ABC                                
                          COMPANY NAME     ? A.B.C.                             
                          DATE OF PURCHASE ? 12/34/56                           
      0.00                # UNITS PURCHASED? 789                                
      0.00                PURCHASE PR/UNIT ? 12.34                              
      0.00                PRESENT  PR/UNIT ? 56.78                              
      0.00                YEARLY  DIV/UNIT ? 9.87                               
TK    CORP. NAME    DATE   PURCH.    PRESENT  YEARLY   NO.                      
CODE               PURCH   PR/UNIT   PR/UNIT  DIV/UNIT UNITS                    
ABC   A.B.C.      12/34/56   12.34     56.78    9.87    789                     
ENTER Y IF OK,N IF ERROR,A TO ABORT? Y                                          
DO YOU DESIRE MORE ENTRIES(Y/N)? N                                              
       MAIN MENU                                                                
                                                                                
 0.QUIT                                                                         
 1.ADD TO FILE OR BEGIN NEW FILE                                                
 2.READ FILE IN FROM TAPE                                                       
 3.WRITE FILE OUT ONTO TAPE                                                     
 4.READ FILE IN FROM DISK                                                       
 5.WRITE FILE OUT ONTO DISK                                                     
 6.EDIT FILE                                                                    
 7.LIST FILE AND PROFIT ANALYSIS                                                
 8.ROUTINE ACTUALLY DELETING RECORD FROM FILE                                   
ENTER YOUR CHOICE? 5                                                            
                                                                                
PUT DATA DISK IN DISK DRIVE                                                     
PRESS ENTER TO CONTINUE?                                                        
       MAIN MENU                                                                
                                                                                
 0.QUIT                                                                         
 1.ADD TO FILE OR BEGIN NEW FILE                                                
 2.READ FILE IN FROM TAPE                                                       
 3.WRITE FILE OUT ONTO TAPE                                                     
 4.READ FILE IN FROM DISK                                                       
 5.WRITE FILE OUT ONTO DISK                                                     
 6.EDIT FILE                                                                    
 7.LIST FILE AND PROFIT ANALYSIS                                                
 8.ROUTINE ACTUALLY DELETING RECORD FROM FILE                                   
ENTER YOUR CHOICE? 4                                                            
PUT DATA DISK IN DISK DRIVE                                                     
PRESS ENTER TO CONTINUE?                                                        
       MAIN MENU                                                                
                                                                                
 0.QUIT                                                                         
 1.ADD TO FILE OR BEGIN NEW FILE                                                
 2.READ FILE IN FROM TAPE                                                       
 3.WRITE FILE OUT ONTO TAPE                                                     
 4.READ FILE IN FROM DISK                                                       
 5.WRITE FILE OUT ONTO DISK                                                     
 6.EDIT FILE                                                                    
 7.LIST FILE AND PROFIT ANALYSIS                                                
 8.ROUTINE ACTUALLY DELETING RECORD FROM FILE                                   
ENTER YOUR CHOICE? 7                                                            
IS A LINE PRINTER TO BE USED(Y/N)? Y                                            
           LIST  MENU                                                           
                                                                                
1. COMPLETE LIST AS ON FILE                                                     
2. LIST WITH PAPER PROFIT, YIELD & PORTFOLIO VALUE                              
3. END LIST PROGRAM                                                             
                                                                                
ENTER APPROPRIATE CHOICE? 1                                                     
PUT PAPER INTO PRINTER                                                          
PRESS ENTER TO CONTINUE?                                                        
TK    CORP. NAME    DATE   PURCH.    PRESENT  YEARLY   NO.                      
CODE               PURCH   PR/UNIT   PR/UNIT  DIV/UNIT UNITS                    
ABC   A.B.C.      12/34/56   12.34     56.78    9.87    789                     
                                                                                
PRESS ENTER TO CONTINUE?                                                        
           LIST  MENU                                                           
                                                                                
1. COMPLETE LIST AS ON FILE                                                     
2. LIST WITH PAPER PROFIT, YIELD & PORTFOLIO VALUE                              
3. END LIST PROGRAM                                                             
                                                                                
ENTER APPROPRIATE CHOICE? 2                                                     
                                                                                
******* COMPUTING *******                                                       
 TK    DATE      PURCH.   PRES.    YIELD    PRESENT  % PROFIT                   
CODE  PURCH.    PR/UNIT  PR/UNIT     %       VALUE                              
ABC  12/34/56     12.34    56.78    17.38   44799.42   360.13                   
                                                                                
PRESS ENTER TO CONTINUE?                                                        
                                                                                
PORTFOLIO VALUE AT COST :   $9736.26                                            
PRESENT PORTFOLIO VALUE :  $44799.42                                            
DOLLAR PAPER PROFIT     :  $35063.16                                            
TOTAL DIVIDENDS PER YEAR:   $7787.43                                            
DIVIDEND YIELD          :       0.17                                            
                                                                                
PRESS ENTER TO CONTINUE?                                                        
           LIST  MENU                                                           
                                                                                
1. COMPLETE LIST AS ON FILE                                                     
2. LIST WITH PAPER PROFIT, YIELD & PORTFOLIO VALUE                              
3. END LIST PROGRAM                                                             
                                                                                
ENTER APPROPRIATE CHOICE? 3                                                     
       MAIN MENU                                                                
                                                                                
 0.QUIT                                                                         
 1.ADD TO FILE OR BEGIN NEW FILE                                                
 2.READ FILE IN FROM TAPE                                                       
 3.WRITE FILE OUT ONTO TAPE                                                     
 4.READ FILE IN FROM DISK                                                       
 5.WRITE FILE OUT ONTO DISK                                                     
 6.EDIT FILE                                                                    
 7.LIST FILE AND PROFIT ANALYSIS                                                
 8.ROUTINE ACTUALLY DELETING RECORD FROM FILE                                   
ENTER YOUR CHOICE? 0                                                            
