                 PRESENT VALUE                                                  
                                                                                
THIS PROGRAM WILL COMPUTE THE PRESENT VALUE OF A SINGLE                         
AMOUNT , A ,TO BE OBTAINED AFTER N EQUAL TIME PERIODS, WITH                     
INTEREST COMPOUNDED AT A RATE OF I% pER PERIOD.                                 
BE SURE TO INPUT INTEREST RATE AS A PER CENT. CONVERSION                        
TO DECIMAL FORM IS DONE IN THE PROGRAM.                                         
                                                                                
   INTEREST RATES MAY BE QUOTED AS ANNUAL RATES IF THE                          
NUMBER OF COMPOUNDINGS PER YEAR ARE KNOWN.                                      
                                                                                
PRESS ENTER TO BEGIN ?                                                          
ARE INTEREST RATES QUOTED ANNUALLY(Y/N)? Y                                      
                                                                                
ANNUAL INTEREST RATE IN %? 8                                                    
NUMBER OF COMPOUNDINGS ANNUALLY? 12                                             
                                                                                
INTEREST RATE PER PERIOD =  .666667 %                                           
INTEREST RATE ,i,PER PERIOD= ? 7                                                
AMOUNT TO BE OBTAINED (A)  = ? 123456                                           
NUMBER OF PERIODS          = ? 40                                               
                                                                                
PRESENT VALUE              = 8244.44                                            
                                                                                
FOR ADDITIONAL TRIALS PRESS 1,ELSE PRESS 0? 0                                   
