REGULAR WITHDRAWAL OF INVESTMENT                                                
                                                                                
THIS PROGRAM COMPUTES THE AMOUNT THAT CAN BE                                    
WITHDRAWN FROM AN INITIAL INVESTMENT,M TIMES                                    
PER YEAR FOR N YEARS,WITH NOTHING LEFT AT THE                                   
END OF N YEARS,IF THE NOMINAL INTEREST RATE IS                                  
GIVEN.                                                                          
THIS TYPE OF COMPUTATION SHOULD BE INTERESTING                                  
TO THOSE WHO WOULD LIKE TO KNOW HOW WELL THEY                                   
CAN LIVE FOR A FIXED NUMBER OF YEARS ON                                         
ACCUMULATED SAVINGS.                                                            
                                                                                
PRESS ENTER TO BEGIN?                                                           
AMOUNT OF INITIAL INVESTMENT? 123456                                            
NUMBER  OF WITHDRAWALS PER YEAR? 12                                             
NUMBER OF YEARS OF WITHDRAWALS ? 10                                             
NOMINAL INTEREST RATE (%) ? 5                                                   
                                                                                
 REGULAR WITHDRAWAL PERMITTED =   $1309.44                                      
                                                                                
PRESS 0 TO END,1 TO START OVER,2 FOR NEW INTEREST RATE? 0                       
