         PURCHASE PRICE FOR RENTAL PROPERTY                                     
                                                                                
AN INVESTOR IN RENTAL PROPERTY SHOULD ONLY PURCHASE IF PROFIT                   
CAN BE REALIZED. ONE APPROACH WHICH MAY BE USED IS TO                           
PURCHASE THE PROPERTY IF THE TOTAL RENT RECEIPTS EXCEED TOTAL                   
EXPENSES. THESE EXPENSES CONSIST OF PROPERTY TAXES, INSURANCE,                  
MORTGAGE PAYMENTS, MAINTENANCE COSTS, AND OTHER MISC. COSTS.                    
IN THE MODEL TO BE USED IN THIS PROGRAM RENTAL INCOME IS KNOWN.                 
ALL EXPENSES ARE KNOWN EXCEPT THE MONTHLY MORTGAGE PAYMENT.                     
THE BANK MORTGAGE RATE IS KNOWN. WHAT WE ATTEMPT TO DETERMINE                   
HERE IS THE AMOUNT WHICH SHOULD BE BORROWED TO MAKE TOTAL                       
EXPENSES EQUAL TO TOTAL INCOME.                                                 
                                                                                
PRESS ENTER TO BEGIN?                                                           
ENTER TOTAL MONTHLY RENTAL INCOME? 2345                                         
ENTER MONTHLY INSURANCE          ? 45                                           
ENTER MONTHLY MAINTENANCE        ? 67                                           
ENTER MONTHLY TAXES              ? 89                                           
ENTER MONTHLY MISCELLANEOUS COSTS? 12                                           
ENTER ANNUAL MORTGAGE INT RATE(%)? 7.5                                          
ENTER LENGTH OF MORTGAGE(YEARS) ? 30                                            
                                                                                
MONTHLY INTEREST RATE =  .625 %                                                 
MONTHLY MORTGAGE PAYMENT WILL EQUAL   $2132.00                                  
                                                                                
AMOUNT PROPERTY IS WORTH  =  $304914                                            
                                                                                
PRESS ENTER FOR MORE COMPUTATION? -1                                            
