    SEASONAL INDEX FOR A TIME SERIES                                            
                                                                                
MOST BUSINESSES SHOW SEASONAL VARIATIONS OF SALES. THAT MEANS                   
THAT THE SALES AT ONE TIME OF THE YEAR ARE HIGHER THAN THOSE                    
AT OTHER TIMES YEAR AFTER YEAR. THE SEASONAL INDEX FOR A                        
SEASON(OR MONTH) IS THE PERCENTAGE THAT SEASON'S SALES ARE OF                   
THE SALES IN AN 'AVERAGE' SEASON. FOR EXAMPLE IF A STORE SELLS                  
$60,00 PER YEAR, OR $5,000 PER MONTH AND AVERAGES $8,000                        
DURING JUNE THEN THE INDEX FOR JUNE IS 160.                                     
                                                                                
THIS PROGRAM WILL COMPUTE SEASONAL INDICES. WHAT IS                             
NECESARY IS THE INPUT OF SALES AMOUNTS FOR EACH SEASON FOR                      
AT LEAST SEVERAL YEARS. THE PROGRAM WILL ACCEPT FEWER YEARS                     
BUT THE RESULTS WOULD BE MEANINGLESS.                                           
                                                                                
PRESS ENTER TO BEGIN?                                                           
NUMBER OF SEASONS IN YEAR(<=12)? 4                                              
NUMBER OF YEARS OF DATA AVAILABLE(<=100)? 2                                     
                                                                                
DATA FOR YEAR  1                                                                
   ENTER DATA FOR SEASON 1 ? 111                                                
   ENTER DATA FOR SEASON 2 ? 155                                                
   ENTER DATA FOR SEASON 3 ? 177                                                
   ENTER DATA FOR SEASON 4 ? 199                                                
DATA FOR YEAR  2                                                                
   ENTER DATA FOR SEASON 1 ? 122                                                
   ENTER DATA FOR SEASON 2 ? 144                                                
   ENTER DATA FOR SEASON 3 ? 166                                                
   ENTER DATA FOR SEASON 4 ? 188                                                
IS LINE PRINTER OUTPUT DESIRED(Y/N)? Y                                          
PRESS ENTER WHEN PRINTER READY?                                                 
AVERAGE MONTHLY SALES = $ 157.75                                                
                                                                                
SEASON        AVERAGE SALES        INDEX                                        
   1               $116.50             0.74                                     
   2               $149.50             0.95                                     
   3               $171.50             1.09                                     
   4               $193.50             1.23                                     
                                                                                
