        SHELL SORT ROUTINE                                                      
                                                                                
THE INPUT OF THIS PROGRAM IS A LIST OF WORDS.(OR POS NOS.).                     
THE OUTPUT IS THE LIST IN ALPHABETICAL (OR NUMERICAL)ORDER.                     
WHEN INPUTTING THE DATA DO NOT IMBED COMMAS WITHIN INPUT                        
WORDS OR NUMBERS OR USE NEGATIVE NUMBERS.                                       
THE SHELL SORT IS GENERALLY MORE EFFICIENT THAN THE EASIER TO                   
UNDERSTAND BUBBLE SORT.                                                         
   THERE IS AN OPTION TO PRINT OUT BOTH THE ORIGINAL AND THE                    
SORTED LISTS ON THE LINE PRINTER.                                               
                                                                                
PRESS ENTER TO BEGIN?                                                           
WHAT IS THE MAXIMUM NUMBER OF ITEMS YOU WISH TO SORT? 9                         
                                                                                
DO YOU WANT OUTPUT TO GO TO THE LINE PRINTER(Y/N)? Y                            
PRESS 1 FOR ALPHABETIC DATA, 2 FOR NUMERIC DATA? 1                              
INPUT ITEM 1  (99999 TO END)? XXX                                               
INPUT ITEM 2  (99999 TO END)? NNN                                               
INPUT ITEM 3  (99999 TO END)? BBB                                               
INPUT ITEM 4  (99999 TO END)? 99999                                             
TO PRINT ORIGINAL LIST PRESS ENTER?                                             
PRESS ENTER WHEN PRINTER READY?                                                 
 ITEM NUMBER               ITEM VAL.                                            
       1                  XXX                                                   
       2                  NNN                                                   
       3                  BBB                                                   
PRESS ENTER TO CONTINUE?                                                        
SORTING - SORTING - SORTING                                                     
TO PRINT SORTED LIST PRESS ENTER?                                               
PRESS ENTER WHEN PRINTER READY?                                                 
 ITEM NUMBER               ITEM VAL.                                            
       1                  BBB                                                   
       2                  NNN                                                   
       3                  XXX                                                   
PRESS ENTER TO CONTINUE?                                                        
