         DEPRECIATION AND INCOME TAX                                            
                                                                                
AS A BUSINESS EXPENSE HIGH DEPRECIATION LOWERS PROFITS.                         
HOWEVER, LOWER TAXES ARE A RESULT OF THIS. THUS, HIGHER                         
DEPRECIATION MEANS HIGHER NET CASH FLOW WHICH WE DEFINE AS                      
PROFITS BEFORE DEPRECIATION-INCOME TAXES.                                       
IN THIS PROGRAM THE USER INPUTS PROFITS BEFORE DEPRECIATION.                    
THEN HE INPUTS VARIOUS POSSIBLE DEPRECIATIONS. NET CASH FLOW                    
FOR EACH IS THEN COMPUTED. TAX SCHEDULES USED ARE:                              
          17% OF FIRST $25000                                                   
          20% OF NEXT  $25000                                                   
          30% OF NEXT $25000                                                    
          40% OF NEXT $25000                                                    
          46% OF ANY AMOUNT OVER $100000                                        
                                                                                
PRESS ENTER TO BEGIN?                                                           
INPUT PROFITS BEFORE DEPRECIATION? 123456                                       
                                                                                
ENTER DEPRECIATION AMOUNT & <ENTER> BELOW                                       
                                                                                
     DEPRECIATION         TAXES        NET CASH FLOW !                          
 ? 6543                                                                         
      $6543.00         $34529.98         $88926.02                              
 ? 4321                                                                         
      $4321.00         $35552.10         $87903.90                              
 ? 9876                                                                         
      $9876.00         $32996.80         $90459.20                              
 ? -1                                                                           
