SIMPLE MOVING AVERAGE SMOOTHING PROGRAM                                         
                                                                                
THIS PROGRAM COMPUTES AN M-PERIOD MOVING AVERAGE FOR A SET OF                   
VALUES. M SHOULD BE AN ODD INTEGER,E.G 3,5,7,ETC. THERE SHOULD                  
BE MORE THAN M OBSERVATIONS TO GET MEANINGFUL RESULTS.                          
                                                                                
PRESS ENTER TO BEGIN.?                                                          
                                                                                
THIS IS AN M-PERIOD MOVING AVERAGE.WHAT DOES M EQUAL? 3                         
                                                                                
GIVE AN UPPER BOUND ON THE NUMBER OF OBSERVATIONS YOU INTEND TO                 
USE.THIS WILL BE THE GREATEST NUMBER OF OBSERVATIONS POSSIBLE.                  
NUMBER = ? 10                                                                   
INPUT OBSERVATIONS 1 BY 1, PRESSING ENTER AFTER EACH.                           
INPUT 99999 AND ENTER WHEN DONE.                                                
                                                                                
PRESS ENTER TO BEGIN?                                                           
OBSERVATION  1  (99999 TO END)? 1223                                            
OBSERVATION  2  (99999 TO END)? 882                                             
OBSERVATION  3  (99999 TO END)? 987                                             
OBSERVATION  4  (99999 TO END)? 99999                                           
OBSERVATION #   OBSERVATION VALUE   SMOOTHED VALUE                              
        1              1223.00                                                  
        2               882.00                                                  
        3               987.00                                                  
