               TIME CLOCK                                                       
                                                                                
THIS PROGRAM USES AS INPUT THE USUAL INFORMATION ON THE                         
COMINGS AND GOINGS OF EMPLOYES STAMPED BY A TIME CLOCK ON                       
THE EMPLOYEE TIME CARD. aS OUTPUT THE COMPUTER GIVES A                          
SUMMARY OF THE NUMBER OF HOURS THE EMPLOYEE HAS WORKED                          
EACH DAY ALONG WITH THE TOTAL OF HOURS FOR THE WEEK. THE                        
WEEKLY HOURS ARE DIVIDED INTO REGULAR AND OVERTIME HOURS                        
WITH OVERTIME HOURS CONSIDERED TO BE THOSE HOURS GREATER                        
THAN 40. THERE IS THE OPTION TO MANUALLY OVERRIDE THE DIVISION                  
OF REGULAR VERSUS OVERTIME HOURS.                                               
PRESS ENTER TO CONTINUE?                                                        
INPUT Y IF PRINTER DESIRED,N IF NOT? Y                                          
EMPLOYEE NUMBER ? 1                                                             
ENTER TIME FOR DAY OF WEEK GIVEN. FORM SHOULD BE:                               
A OR P,HR IN.MIN IN,A OR P,HR OUT. MIN OUT                                      
TO END DAY ENTER D,0,0,0.TO END WEEK ENTER W,0,0,0                              
MONDAY                                                                          
A OR P,TIME IN,A OR P,TIME OUT? A,10,P,2                                        
A OR P,TIME IN,A OR P,TIME OUT? A,10,P,2                                        
A OR P,TIME IN,A OR P,TIME OUT? A,10,P,2                                        
A OR P,TIME IN,A OR P,TIME OUT? A,10,P,2                                        
A OR P,TIME IN,A OR P,TIME OUT? W,0,0,0                                         
A  10              P       2           TOTAL =  4          HRS                  
A  10              P       2           TOTAL =  4          HRS                  
A  10              P       2           TOTAL =  4          HRS                  
A  10              P       2           TOTAL =  4          HRS                  
MONDAY        TOTAL =         16       HRS.                                     
                             GRAND TOTAL =  16                                  
REGULAR HOURS  =  16          OVERTIME HOURS =  0                               
REGULAR HOURS,OVERTIME HOURS ? 40,20                                            
EMPLOYEE NUMBER ? -1                                                            
