                   TRANSPORTATION PROBLEM                                       
                                                                                
THE TRANSPORTATION PROBLEM EXAMINED HERE IS THE FOLLOWING:                      
   THERE ARE N SOURCES OF SUPPLY AND M DESTINATIONS FOR A                       
GOOD. EACH OF THE SUPPLY SOURCES CAN SUPPLY A GIVEN AMOUNT OF                   
THE GOOD AND EACH DESTINATION HAS A CERTAIN REQUIREMENT. WE                     
REQUIRE THAT THE TOTAL OF POSSIBLE SUPPLY EQUALS THE TOTAL                      
REQUIRED.TO DELIVER A UNIT OF THE ITEM FROM A GIVEN SOURCE TO                   
A GIVEN DESTINATION HAS A KNOWN COST,DEPENDING UPON THE SOURCE-                 
DESTINATION COMBINATION. THE PROBLEM ATTEMPTS TO DETERMINE                      
WHICH SHIPPING ASSIGNMENT MINIMIZES SHIPPING COST.                              
                                                                                
PRESS ENTER TO CONTINUE?                                                        
ENTER NUMBER OF SOURCES     ? 3                                                 
ENTER NUMBER OF DESTINATIONS? 2                                                 
                                                                                
SOURCE 1                                                                        
    UNIT COST TO DESTINATION  1 ? 1                                             
    UNIT COST TO DESTINATION  2 ? 2                                             
CAPACITY OF SOURCE 1 ? 3                                                        
SOURCE 2                                                                        
    UNIT COST TO DESTINATION  1 ? 2                                             
    UNIT COST TO DESTINATION  2 ? 1                                             
CAPACITY OF SOURCE 2 ? 5                                                        
SOURCE 3                                                                        
    UNIT COST TO DESTINATION  1 ? 1                                             
    UNIT COST TO DESTINATION  2 ? 1                                             
CAPACITY OF SOURCE 3 ? 2                                                        
                                                                                
REQUIREMENTS OF DESTINATION 1 ? 4                                               
REQUIREMENTS OF DESTINATION 2 ? 6                                               
IS PRINTER COPY OF INPUT DESIRED(Y/N)? Y                                        
PRESS ENTER WHEN PRINTER READY?                                                 
                                                                                
                                                                                
                                                                                
                   COMPUTING                                                    
IS PRINTER OUTPUT DESIRED(Y/N)? Y                                               
SHIPPING ASSIGNMENTS                                                            
 FROM SOURCE  1 TO DESTINATION  1  :     3.0   COST=      3.00                  
 FROM SOURCE  2 TO DESTINATION  2  :     5.0   COST=      5.00                  
 FROM SOURCE  3 TO DESTINATION  1  :     1.0   COST=      1.00                  
 FROM SOURCE  3 TO DESTINATION  2  :     1.0   COST=      1.00                  
                       TOTAL COST            =  10                              
                                                                                
PRESS ENTER WHEN PRINTER READY?                                                 
                                                                                
PRESS ENTER FOR MORE COMPUTATION? -1                                            
