THIS PROGRAM SHOULD LOAD AND RUN THE 'CHAIN_2' PROGRAM                          
THE 'TEST' PROGRAM IS NOW RUNNING                                               
 1  2  3  4  5  6  7  8  9 THIS PROGRAM WILL NOW CHAIN BACK TO THE MAIN PROGRAM 
CHAIN PASSED THE TEST IF THE 'CHAIN_2' PROGRAM                                  
PRINTED A SERIES OF NUMBERS                                                     
