ENTER THE 'CONT' COMMAND                                                        
                                                                                
Program interrupted at line 30                                                  
bwBASIC: CONT 80                                                                
THE CONT COMMAND PASSED THE TEST                                                
