THE # OPERATOR PASSED THE PRINT USING TEST                                      
IF THE FOLLOWING NUMBERS ARE PRINTED                                            
        1.20                                                                    
      400.00                                                                    
2,400,000.00                                                                    
   82,450.50                                                                    
       -0.25                                                                    
