THE COMPUTER IS WAITING FOR ONLY BIT 1 TO BE SET                                
IN PORT 20 (THE DECIMAL VALUE OF 2)                                             
  X= 20                                                                         
  Y= 253                                                                        
  Z= 2                                                                          
BIT 1 IN PORT 20 IS SET                                                         
