1ST STAR MAG? 2                                                                 
2ND STAR MAG? 3                                                                 
TOTAL MAG:    1.63615                                                           
                                                                                
ANOTHER STAR? X                                                                 
STAR COUNT:   2                                                                 
