Zenith distance (deg.): ? 174                                                   
                                                                                
Airmass (gas, aerosol, ozone):      0.00    0.00    1.01                        
Extinction Coefficients (UBVRI):    0.66    0.36    0.22    0.11    0.06        
Total Extinction (UBVRI):           0.00    0.00    0.03    0.01    0.00        
Sky brightness (UBVRI):  0.04.999651e-14  0.07.143514e-14  0.0                  
                                                                                
Visual Sky Brightness (nL):     64                                              
Visual Limiting Magnitude:    6.50                                              
