TEST CASE # 1 : A$=[is], B$=[Now is the], I%= 1 , N%= 5                         
TEST CASE # 2 : A$=[##], B$=[October 8, 1876], I%= 1 , N%= 12                   
TEST CASE # 3 : A$=[a?], B$=[character], I%= 4 , N%= 5                          
TEST CASE # 4 : A$=[\#], B$=[123#45], I%= 1 , N%= 4                             
TEST CASE # 5 : A$=[ABCD], B$=[ABC], I%= 1 , N%= 0                              
TEST CASE # 6 : A$=[\#1\\\?], B$=[1#1\?2#], I%= 1 , N%= 2                       
TEST CASE # 7 : A$=[ ], B$=[ ], I%= 2 , N%= 0                                   
TEST CASE # 8 : A$=[ ], B$=[], I%= 1 , N%= 0                                    
TEST CASE # 9 : A$=[], B$=[ ], I%= 1 , N%= 1                                    
TEST CASE # 10 : A$=[], B$=[], I%= 1 , N%= 0                                    
TEST PASSED                                                                     
