SIZE() of non-existing file is zero                                             
N= 0                                                                            
  TEST PASSED                                                                   
SIZE() of zero length file is zero                                              
N= 0                                                                            
 TEST PASSED                                                                    
SIZE() of < 1024 length file is 1                                               
N= 1                                                                            
 TEST PASSED                                                                    
SIZE() of 1024 length file is 1                                                 
N= 1                                                                            
 TEST PASSED                                                                    
