THESE LINES ARE                                                                 
FROM PROG1                                                                      
   BUT ...                                                                      
bwBASIC: LIST                                                                   
   10 REM 'APPEND' TEST PROGRAM PROG1                                           
   20 PRINT "THESE LINES ARE"                                                   
   30 PRINT "FROM PROG1"                                                        
   40 PRINT "   BUT ..."                                                        
                                                                                
bwBASIC: APPEND "APPEND_1.DAT"                                                  
bwBASIC: LIST                                                                   
   10 REM 'APPEND' TEST PROGRAM PROG1                                           
   20 PRINT "THESE LINES ARE"                                                   
   30 PRINT "FROM PROG1"                                                        
   40 PRINT "   BUT ..."                                                        
 1000 PRINT "THESE LINES ARE"                                                   
 1010 PRINT "FROM PROG2"                                                        
 1020 END                                                                       
                                                                                
bwBASIC: RUN                                                                    
THESE LINES ARE                                                                 
FROM PROG1                                                                      
   BUT ...                                                                      
THESE LINES ARE                                                                 
FROM PROG2                                                                      
