ENTER TWO VALUES (SEPARATED BY COMMAS                                           
? 3,7                                                                           
 3 IS LESS THAN OR EQUAL TO 7                                                   
ENTER TWO VALUES (SEPARATED BY COMMAS                                           
? 9,1                                                                           
 1 IS LESS THAN OR EQUAL TO 9                                                   
ENTER TWO VALUES (SEPARATED BY COMMAS                                           
? 0,0                                                                           
