 1 0 0                                                                          
 0 1 0                                                                          
 0 0 1                                                                          
'MAT IDN' PASSED THE TEST IF A 3X3 IDENTITY                                     
MATRIX WAS PRINTED.                                                             
