 1  1  1  1  1                                                                  
 1  1  1  1  1                                                                  
 1  1  1  1  1                                                                  
'MAT CON' PASSED THE TEST IF A                                                  
3X5 ARRAY OF ONES WAS PRINTED.                                                  
