 11  21  31                                                                     
 12  22  32                                                                     
 13  23  33                                                                     
 14  24  34                                                                     
 15  25  35                                                                     
'MAT TRN' PASSED THE TEST IF THE NUMBERS 11-15,                                 
21-25, AND 31-35 ARE PRINTED IN 3 COLUMNS.                                      
