 0  0  0  0  0                                                                  
 0  0  0  0  0                                                                  
 0  0  0  0  0                                                                  
'MAT ZER' PASSED THE TEST IF A                                                  
3X5 ARRAY OF ZEROS WAS PRINTED.                                                 
