bwBASIC: NEW                                                                    
bwBASIC: FLOW                                                                   
Trace is ON                                                                     
bwBASIC: LOAD "NOFLOW_1.DAT"                                                    
bwBASIC: RUN                                                                    
[ 10 REM 'NOFLOW' TEST PROGRAM ][ 20 PRINT "THE FIRST THREE LINES OF THIS PROGRA
[ 30 NOFLOW ]Trace is OFF                                                       
ARE PRINTED WITH THE TRACE TURNED ON.                                           
THIS LINE IS PRINTED WITH THE TRACE TURNED OFF.                                 
