THIS IS A TEST                                                                  
bwBASIC: LIST                                                                   
   10 REM 'SCRATCH' COMMAND TEST PROGRAM                                        
   20 PRINT "THIS IS A TEST"                                                    
   99 END                                                                       
                                                                                
bwBASIC: SCRATCH                                                                
bwBASIC: LIST                                                                   
                                                                                
