                                                                                
ERROR in line 210: Syntax error                                                 
                                                                                
STACK TRACE:                                                                    
210:LET A                                                                       
