 [2J [1;1H [2J [1;1H 1                                                          
 2                                                                              
 3                                                                              
 4                                                                              
 5                                                                              
 6                                                                              
 7                                                                              
 8                                                                              
 9                                                                              
 10                                                                             
 11                                                                             
 12                                                                             
 13                                                                             
 14                                                                             
 15                                                                             
 [8;5H'AT' PASSED THE TEST IF THIS IS LINE #8.                                  
