                                                                                
Program interrupted at line 30                                                  
bwBASIC: CONT                                                                   
THE COMPUTER SHOULD STOP EXECUTION AT LINE 30                                   
                                                                                
Program interrupted at line 50                                                  
bwBASIC: CONT                                                                   
LINE 50                                                                         
                                                                                
Program interrupted at line 70                                                  
bwBASIC: CONT                                                                   
LINE 70                                                                         
                                                                                
Program interrupted at line 80                                                  
bwBASIC: CONT                                                                   
LINE 80                                                                         
                                                                                
Program interrupted at line 90                                                  
bwBASIC: CONT                                                                   
AND LINE 90                                                                     
