THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
THIS LINE SHOULD DISAPPEAR                                                      
 [2J [1;1HIF THIS IS ALL THAT'S ON THE SCREEN                                   
THE CLS STATEMENT PASSED THE TEST                                               
