ENTER THE 'CONT' COMMAND                                                        
                                                                                
Program interrupted at line 30                                                  
bwBASIC: CONT                                                                   
THE CONT COMMAND PASSED THE TEST                                                
