bwBASIC: NEW                                                                    
bwBASIC: 10 REM 'CSAVE' TEST PROGRAM                                            
bwBASIC: 20 PRINT "THIS PROGRAM TESTS THE CSAVE FEATURE"                        
bwBASIC: 99 END                                                                 
bwBASIC: LIST                                                                   
   10 REM 'CSAVE' TEST PROGRAM                                                  
   20 PRINT "THIS PROGRAM TESTS THE CSAVE FEATURE"                              
   99 END                                                                       
                                                                                
bwBASIC: CSAVE "CSAVE_1.DAT"                                                    
bwBASIC: NEW                                                                    
bwBASIC: LIST                                                                   
                                                                                
bwBASIC: CLOAD "CSAVE_1.DAT"                                                    
bwBASIC: LIST                                                                   
   10 REM 'CSAVE' TEST PROGRAM                                                  
   20 PRINT "THIS PROGRAM TESTS THE CSAVE FEATURE"                              
   99 END                                                                       
                                                                                
