LIST TEST COMPLETE                                                              
bwBASIC: LIST 20-30                                                             
   20 REM THIS COMMAND                                                          
   30 REM WILL DISPLAY EACH LINE                                                
                                                                                
