ENTER 12 NUMBERS (TYPE A COMMA BETWEEN EACH NUMBER)                             
?1,2,3,4,5,6,7,8,9,10,11,12                                                     
 1  2  3  4                                                                     
 5  6  7  8                                                                     
 9  10  11  12                                                                  
THE MAT INPUT STATEMENT PASSED THE TEST                                         
IF THE INPUT VALUES ARE PRINTED                                                 
IN A MATRIX HAVING THREE ROWS OF FOUR COLUMNS                                   
