 1  2  3  4                                                                     
 5  6  7  8                                                                     
 9  10  11  12                                                                  
THE MAT READ STATEMENT PASSED THE TEST                                          
IF A MATRIX IS PRINTED HAVING 3 ROWS AND 4 COLUMNS                              
