REM Filename:  00INDENT.BAT
REM  Purpose:  format source code
REM   Author:  Howard Wulf, AF5NE
REM     Date:  2015-01-29
REM   Uasage:  implementation defined
REM  Example:
REM            CD \sdcard\Download\BASIC\bwbasic-2.62\
REM            00INDENT.BAT
REM
call 01indent.bat BWBASIC.C
call 01indent.bat BWBASIC.H
call 01indent.bat BWB_CMD.C
call 01indent.bat BWB_CND.C
call 01indent.bat BWB_DIO.C
call 01indent.bat BWB_ELX.C
call 01indent.bat BWB_EXP.C
call 01indent.bat BWB_FNC.C
call 01indent.bat BWB_INP.C
call 01indent.bat BWB_INT.C
call 01indent.bat BWB_OPS.C
call 01indent.bat BWB_PRN.C
call 01indent.bat BWB_STC.C
call 01indent.bat BWB_STR.C
call 01indent.bat BWB_TBL.C
call 01indent.bat BWB_VAR.C
call 01indent.bat BWD_CMD.C
call 01indent.bat BWD_FUN.C
call 01indent.bat BWD_SIX.H
call 01indent.bat BWX_TTY.C
REM EOF
