/***************************************************************
  
        bwx_tty.c       Six character extern redefinitions
                        for Bywater BASIC Interpreter
  
                        Copyright (c) 1993, Ted A. Campbell
                        Bywater Software
  
                        email: tcamp@delphi.com
  
        Copyright and Permissions Information:
  
        All U.S. and international rights are claimed by the author,
        Ted A. Campbell.
  
   This software is released under the terms of the GNU General
   Public License (GPL), which is distributed with this software
   in the file "COPYING".  The GPL specifies the terms under
   which users may copy and use the software in this distribution.
  
   A separate license is available for commercial distribution,
   for information on which you should contact the author.
  
***************************************************************/

/*---------------------------------------------------------------*/
/* NOTE: Modifications marked "JBV" were made by Jon B. Volkoff, */
/* 11/1995 (eidetics@cerf.net).                                  */
/*                                                               */
/* Those additionally marked with "DD" were at the suggestion of */
/* Dale DePriest (daled@cadence.com).                            */
/*                                                               */
/* Version 3.00 by Howard Wulf, AF5NE                            */
/*                                                               */
/*---------------------------------------------------------------*/

#define ed                               X00000
#define fi                               X00001
#define pr                               X00002
#define im                               X00003
#define co                               X00004
#define progfile                         X00005
#define rescan                           X00006
#define number                           X00007
#define bwb_l                            X00008
#define bwb_start                        X00009
#define bwb_end                          X0000A
#define data_line                        X0000B
#define data_pos                         X0000C
#define var_start                        X0000D
#define var_end                          X0000E
#define fnc_start                        X0000F
#define fnc_end                          X00010
#define fslt_start                       X00011
#define fslt_end                         X00012
#define exsc                             X00013
#define expsc                            X00014
#define excs                             X00015
#define exps                             X00016
#define bwb_curtask                      X00017
#define bwb_ebuf                         X00018
#define bwb_trace                        X00019
#define dim_base                         X0001A
#define option_degrees                   X0001B
#define errfdevice                       X0001C
#define err_line                         X0001D
#define err_number                       X0001E
#define err_gosubl                       X0001F
#define err_fired                        X00020
#define ErrMsg                           X00021
#define stopped_line                     X00022
#define dev_table                        X00023
#define exp_ops                          X00024
#define bwb_cmdtable                     X00025
#define bwb_prefuncs                     X00026
#define bwb_vertable                     X00027
#define OptionVersion                    X00028
#define OptionCommentChar                X00029
#define OptionStatementChar              X0002A
#define OptionFlags                      X0002B
#define OptionDateFormat                 X0002C
#define OptionTimeFormat                 X0002D
#define OptionIndentValue                X0002E
#define OptionTerminalType               X0002F
#define tmr_gotol                        X00030
#define tmr_count                        X00031
#define tmr_expires                      X00032
#define IsInteractive                    X00033
#define IsCommandLineFile                X00034
#define LPRINT_COLUMN                    X00035
#define LPRINT_WIDTH                     X00036
#define LPRINT_NULLS                     X00037
#define mark                             X00038
#define ExternalInputFile                X00039
#define MaintainerDebugOn                X0003A
#define DefaultVariableType              X0003B
#define err_openfile                     X0003C
#define err_getmem                       X0003D
#define err_noln                         X0003E
#define err_nofn                         X0003F
#define err_lnnotfound                   X00040
#define err_incomplete                   X00041
#define err_valoorange                   X00042
#define err_syntax                       X00043
#define err_devnum                       X00044
#define err_dev                          X00045
#define err_opsys                        X00046
#define err_argstr                       X00047
#define err_defchar                      X00048
#define err_mismatch                     X00049
#define err_dimnotarray                  X0004A
#define err_retnogosub                   X0004B
#define err_od                           X0004C
#define err_overflow                     X0004D
#define err_nf                           X0004E
#define err_uf                           X0004F
#define err_dbz                          X00050
#define err_redim                        X00051
#define err_obdim                        X00052
#define err_uc                           X00053
#define err_noprogfile                   X00054
#define fnc_timer                        X00055
#define bwb_Timer_On                     X00056
#define bwb_Timer_Off                    X00057
#define bwb_ON_TIMER                     X00058
#define bwb_TIMER                        X00059
#define bwb_TIMER_OFF                    X0005A
#define bwb_TIMER_ON                     X0005B
#define bwb_TIMER_STOP                   X0005C
#define adv_element                      X0005D
#define adv_eos                          X0005E
#define adv_ws                           X0005F
#define BasicNumerc                      X00060
#define break_mes                        X00061
#define bwb_CALL                         X00062
#define bwb_CASE                         X00063
#define bwb_CASE_ELSE                    X00064
#define bwb_CASE_IF                      X00065
#define bwb_CASE_IS                      X00066
#define bwb_CHAIN                        X00067
#define bwb_CHANGE                       X00068
#define bwb_CLEAR                        X00069
#define bwb_CLOAD                        X0006A
#define bwb_CLOAD_                       X0006B
#define bwb_CMDS                         X0006C
#define bwb_COMMON                       X0006D
#define bwb_const                        X0006E
#define bwb_CONT                         X0006F
#define bwb_CSAVE                        X00070
#define bwb_CSAVE_                       X00071
#define bwb_DATA                         X00072
#define bwb_decexec                      X00073
#define bwb_DEF                          X00074
#define bwb_DEFDBL                       X00075
#define bwb_DEFINT                       X00076
#define bwb_DEFSNG                       X00077
#define bwb_DEFSTR                       X00078
#define bwb_DEF_SUB                      X00079
#define bwb_DELETE                       X0007A
#define bwb_DIM                          X0007B
#define bwb_DO                           X0007C
#define bwb_DO_UNTIL                     X0007D
#define bwb_DO_WHILE                     X0007E
#define bwb_ELSE                         X0007F
#define bwb_ELSEIF                       X00080
#define bwb_END                          X00081
#define bwb_END_FUNCTION                 X00082
#define bwb_END_IF                       X00083
#define bwb_END_SELECT                   X00084
#define bwb_END_SUB                      X00085
#define bwb_ERASE                        X00086
#define bwb_error                        X00087
#define bwb_etov                         X00088
#define bwb_execline                     X00089
#define bwb_EXIT                         X0008A
#define bwb_EXIT_DO                      X0008B
#define bwb_EXIT_FOR                     X0008C
#define bwb_EXIT_FUNCTION                X0008D
#define bwb_EXIT_SUB                     X0008E
#define bwb_EXIT_UNTIL                   X0008F
#define bwb_EXIT_WHILE                   X00090
#define bwb_exp                          X00091
#define bwb_FIELD                        X00092
#define bwb_fload                        X00093
#define bwb_FNCS                         X00094
#define bwb_FOR                          X00095
#define bwb_freeline                     X00096
#define bwb_FUNCTION                     X00097
#define bwb_gets                         X00098
#define bwb_getvarname                   X00099
#define bwb_GO                           X0009A
#define bwb_GOSUB                        X0009B
#define bwb_GOTO                         X0009C
#define bwb_HELP                         X0009D
#define bwb_IF                           X0009E
#define bwb_IF_THEN                      X0009F
#define bwb_incexec                      X000A0
#define bwb_init                         X000A1
#define bwb_INPUT                        X000A2
#define bwb_interact                     X000A3
#define bwb_isvar                        X000A4
#define bwb_ladd                         X000A5
#define bwb_LET                          X000A6
#define bwb_LINE                         X000A7
#define bwb_LIST                         X000A8
#define bwb_LOAD                         X000A9
#define bwb_LOOP                         X000AA
#define bwb_LOOP_UNTIL                   X000AB
#define bwb_LOOP_WHILE                   X000AC
#define bwb_LPRINT                       X000AD
#define bwb_LSET                         X000AE
#define bwb_mainloop                     X000AF
#define bwb_MAINTAINER                   X000B0
#define bwb_MERGE                        X000B1
#define bwb_MID_                         X000B2
#define bwb_NAME                         X000B3
#define bwb_NEW                          X000B4
#define bwb_NEXT                         X000B5
#define bwb_null                         X000B6
#define bwb_numseq                       X000B7
#define bwb_ON                           X000B8
#define bwb_ON_ERROR_GOTO                X000B9
#define bwb_ON_ERROR_GOSUB               X000BA
#define bwb_ON_ERROR_RESUME_NEXT         X000BB
#define bwb_ON_ERROR_RETURN_NEXT         X000BC
#define bwb_OPEN                         X000BD
#define bwb_OPTION                       X000BE
#define bwb_OPTION_ANGLE_DEGREES         X000BF
#define bwb_OPTION_ANGLE_RADIANS         X000C0
#define bwb_OPTION_ARITHMETIC_DECIMAL    X000C1
#define bwb_OPTION_ARITHMETIC_FIXED      X000C2
#define bwb_OPTION_ARITHMETIC_NATIVE     X000C3
#define bwb_OPTION_BASE_0                X000C4
#define bwb_OPTION_BASE_1                X000C5
#define bwb_OPTION_BUGS_OFF              X000C6
#define bwb_OPTION_BUGS_ON               X000C7
#define bwb_OPTION_COMMENT               X000C8
#define bwb_OPTION_COMPARE_BINARY        X000C9
#define bwb_OPTION_COMPARE_DATABASE      X000CA
#define bwb_OPTION_COMPARE_TEXT          X000CB
#define bwb_OPTION_COVERAGE_OFF          X000CC
#define bwb_OPTION_COVERAGE_ON           X000CD
#define bwb_OPTION_DATE                  X000CE
#define bwb_OPTION_DISABLE_COMMAND       X000CF
#define bwb_OPTION_DISABLE_FUNCTION      X000D0
#define bwb_OPTION_DISABLE_OPERATOR      X000D1
#define bwb_OPTION_ENABLE_COMMAND        X000D2
#define bwb_OPTION_ENABLE_FUNCTION       X000D3
#define bwb_OPTION_ENABLE_OPERATOR       X000D4
#define bwb_OPTION_ERROR_GOSUB           X000D5
#define bwb_OPTION_ERROR_GOTO            X000D6
#define bwb_OPTION_INDENT                X000D7
#define bwb_OPTION_LABELS_OFF            X000D8
#define bwb_OPTION_LABELS_ON             X000D9
#define bwb_OPTION_STATEMENT             X000DA
#define bwb_OPTION_STRICT_OFF            X000DB
#define bwb_OPTION_STRICT_ON             X000DC
#define bwb_OPTION_TERMINAL_NONE         X000DD
#define bwb_OPTION_TERMINAL_ADM_3A       X000DE
#define bwb_OPTION_TERMINAL_ANSI         X000DF
#define bwb_OPTION_TIME                  X000E0
#define bwb_OPTION_TRACE_OFF             X000E1
#define bwb_OPTION_TRACE_ON              X000E2
#define bwb_OPTION_VERSION               X000E3
#define bwb_PRINT                        X000E4
#define bwb_QUEST                        X000E5
#define bwb_QUIT                         X000E6
#define bwb_READ                         X000E7
#define bwb_REM                          X000E8
#define bwb_RESTORE                      X000E9
#define bwb_RESUME                       X000EA
#define bwb_RETURN                       X000EB
#define bwb_RSET                         X000EC
#define bwb_RUN                          X000ED
#define bwb_SAVE                         X000EE
#define bwb_scan                         X000EF
#define bwb_SELECT                       X000F0
#define bwb_SELECT_CASE                  X000F1
#define bwb_setexec                      X000F2
#define bwb_STOP                         X000F3
#define bwb_stripcr                      X000F4
#define bwb_SUB                          X000F5
#define bwb_SWAP                         X000F6
#define bwb_SYSTEM                       X000F7
#define bwb_UEND                         X000F8
#define bwb_UNTIL                        X000F9
#define bwb_USER_LBL                     X000FA
#define bwb_VARS                         X000FB
#define bwb_vector                       X000FC
#define bwb_vtov                         X000FD
#define bwb_Warning                      X000FE
#define bwb_Warning_Clear                X000FF
#define bwb_Warning_InvalidParameter     X00100
#define bwb_Warning_OutOfData            X00101
#define bwb_Warning_Overflow             X00102
#define bwb_Warning_AdvancedFeature      X00103
#define bwb_Warning_Pending              X00104
#define bwb_WEND                         X00105
#define bwb_WHILE                        X00106
#define bwb_WRITE                        X00107
#define bwb_xlist                        X00108
#define bwb_xload                        X00109
#define bwb_xnew                         X0010A
#define bwb_xtxtline                     X0010B
#define bwb_zline                        X0010C
#define CALLOC                           X0010D
#define dec_esc                          X0010E
#define DetermineNumberOfDimensions      X0010F
#define dim_getparams                    X00110
#define dim_getparams_FIXED              X00111
#define DumpAllCommandSwitchStatement    X00112
#define DumpAllCommandSyntax             X00113
#define DumpAllCommandTableDefinitions   X00114
#define DumpAllCommandUniqueID           X00115
#define DumpAllFuctionSyntax             X00116
#define DumpAllFuctionTableDefinitions   X00117
#define DumpAllFuctionUniqueID           X00118
#define DumpAllFunctionSwitch            X00119
#define DumpOneCommandSyntax             X0011A
#define DumpOneFunctionSyntax            X0011B
#define exp_findop                       X0011C
#define exp_function                     X0011D
#define exp_getnval                      X0011E
#define exp_getival                      X0011F
#define exp_getsval                      X00120
#define exp_getvfname                    X00121
#define exp_iscmd                        X00122
#define exp_isfn                         X00123
#define exp_isnc                         X00124
#define exp_isop                         X00125
#define exp_isvn                         X00126
#define exp_numconst                     X00127
#define exp_operation                    X00128
#define exp_paren                        X00129
#define exp_strconst                     X0012A
#define exp_validarg                     X0012B
#define exp_variable                     X0012C
#define find_BottomLineInCode            X0012D
#define find_label                       X0012E
#define fnc_add_deffn                    X0012F
#define fnc_deffn                        X00130
#define fnc_find                         X00131
#define fnc_find_by_id                   X00132
#define fnc_find_exact                   X00133
#define fnc_init                         X00134
#define fnc_intrinsic                    X00135
#define fnc_null                         X00136
#define FREE                             X00137
#define fslt_add                         X00138
#define fslt_addcallvar                  X00139
#define fslt_addlocalvar                 X0013A
#define fslt_find_name                   X0013B
#define fslt_init                        X0013C
#define FunctionDefinitionCheck          X0013D
#define FunctionSyntax                   X0013E
#define FunctionUniqueID                 X0013F
#define GetKeyword                       X00140
#define GetRestOfLine                    X00141
#define ImplicitDim                      X00142
#define inc_esc                          X00143
#define inp_adv                          X00144
#define inp_numconst                     X00145
#define int_qmdstr                       X00146
#define IsLastKeyword                    X00147
#define is_cmd                           X00148
#define is_eol                           X00149
#define is_label                         X0014A
#define is_let                           X0014B
#define is_ln                            X0014C
#define is_numconst                      X0014D
#define line_start                       X0014E
#define ln_asbuf                         X0014F
#define NumberValueCheck                 X00150
#define OptionBaseHelper                 X00151
#define OptionVersionSet                 X00152
#define prn_iprintf                      X00153
#define prn_lprintf                      X00154
#define prn_precision                    X00155
#define prn_xprintf                      X00156
#define ResetConsoleColumn               X00157
#define scan_element                     X00158
#define SortAllCommands                  X00159
#define SortAllFunctions                 X0015A
#define StringLengthCheck                X0015B
#define str_btob                         X0015C
#define str_btoc                         X0015D
#define str_cat                          X0015E
#define str_cmp                          X0015F
#define str_ctob                         X00160
#define var_chain                        X00161
#define var_delcvars                     X00162
#define var_find                         X00163
#define var_findnval                     X00164
#define var_findsval                     X00165
#define var_free                         X00166
#define var_getnval                      X00167
#define var_getsval                      X00168
#define var_init                         X00169
#define var_make                         X0016A
#define var_new                          X0016B
#define var_pos                          X0016C
#define var_setnval                      X0016D
#define VerifyNumeric                    X0016E
#define SetOnError                       X0016F
#define GetOnError                       X00170
#define ToUpper                          X00171
#define ToLower                          X00172
#define var_CLEAR                        X00173
#define break_handler                    X00174
#define bwb_EDIT                         X00175
#define bwb_RENUM                        X00176
#define bwx_CHDIR                        X00177
#define bwx_CLS                          X00178
#define bwx_COLOR                        X00179
#define bwx_CONSOLE_WIDTH                X0017A
#define bwx_DEBUG                        X0017B
#define bwx_errmes                       X0017C
#define bwx_FILES                        X0017D
#define bwx_FRE                          X0017E
#define bwx_INKEY                        X0017F
#define bwx_INP                          X00180
#define bwx_input                        X00181
#define bwx_INPUT                        X00182
#define bwx_KILL                         X00183
#define bwx_LOCATE                       X00184
#define bwx_LPRINT                       X00185
#define bwx_LPRINT_WIDTH                 X00186
#define bwx_message                      X00187
#define bwx_MKDIR                        X00188
#define bwx_NAME                         X00189
#define bwx_OUT                          X0018A
#define bwx_OUTPUT_WIDTH                 X0018B
#define bwx_PEEK                         X0018C
#define bwx_POKE                         X0018D
#define bwx_PRINT                        X0018E
#define bwx_RANDOM_RECORD_SIZE           X0018F
#define bwx_RMDIR                        X00190
#define bwx_SHELL                        X00191
#define bwx_STOP                         X00192
#define bwx_terminate                    X00193
#define bwx_TIMER                        X00194
#define bwx_WAIT                         X00195
#define bwx_signon                       X00196
#define isnan                            X00197
#define isinf                            X00198
#define rint                             X00199
#define strcasecmp                       X0019A
#define strncasecmp                      X0019B
#define broken_strcpy                    X0019C

/* EOF */
