REM OPTION VERSION BYWATER   ' Bywater BASIC
REM OPTION VERSION DARTMOUTH ' Dartmouth BASIC
REM OPTION VERSION ECMA-55   ' ECMA-55
REM OPTION VERSION BASIC-80  ' Microsoft BASIC-80
REM OPTION VERSION TRS-83    ' TRS-80 Model III
REM OPTION VERSION TRS-84    ' TRS-80 Model 4
REM OPTION VERSION GW-BASIC  ' Microsoft GW-BASIC
REM OPTION VERSION ECMA-116  ' ECMA-116
REM OPTION VERSION QBASIC    ' Microsoft QBASIC
REM OPTION VERSION VBDOS     ' Microsoft VBDOS
REM OPTION VERSION VB1       ' Microsoft VB1
REM OPTION VERSION VB2       ' Microsoft VB2
REM OPTION VERSION VB3       ' Microsoft VB3
REM OPTION VERSION VB4       ' Microsoft VB4
REM OPTION VERSION VB5       ' Microsoft VB5
REM OPTION VERSION VB6       ' Microsoft VB6
REM OPTION ANGLE DEGREES
REM OPTION ANGLE RADIANS
REM OPTION ARITHMETIC DECIMAL
REM OPTION ARITHMETIC FIXED
REM OPTION ARITHMETIC NATIVE
REM OPTION BASE 0
REM OPTION BASE 1
REM OPTION BUGS OFF
REM OPTION BUGS ON
REM OPTION COMMENT !
REM OPTION COMPARE BINARY
REM OPTION COMPARE DATABASE
REM OPTION COMPARE TEXT
REM OPTION COVERAGE OFF
REM OPTION COVERAGE ON
REM OPTION DATE "%m/%d/%Y"
REM OPTION DISABLE COMMAND QUIT
REM OPTION DISABLE FUNCTION PI
REM OPTION DISABLE OPERATOR MOD
REM OPTION ENABLE COMMAND QUIT
REM OPTION ENABLE FUNCTION PI
REM OPTION ENABLE OPERATOR MOD
REM OPTION ERROR GOSUB
REM OPTION ERROR GOTO
REM OPTION INDENT number
REM OPTION LABELS OFF
REM OPTION LABELS ON
REM OPTION STATEMENT \
REM OPTION STRICT OFF
REM OPTION STRICT ON
REM OPTION TERMINAL ADM-3A
REM OPTION TERMINAL ANSI
REM OPTION TERMINAL NONE
REM OPTION TIME "%H:%M:%S"
REM OPTION TRACE OFF
REM OPTION TRACE ON
REM MAINTAINER DEBUG ON
REM LET BWB.EDITOR$ = "nano"
REM LET BWB.FILES$  = "ls -Fx"
REM LET BWB.PROMPT$ = "bwBASIC: "
