X=1                                                                             
ONE             1                                                               
X=9                                                                             
None of the above                                                               
X=2                                                                             
TWO             2                                                               
X=0                                                                             
None of the above                                                               
X=8                                                                             
None of the above                                                               
X=3                                                                             
THREE           3                                                               
X=4                                                                             
None of the above                                                               
X=-1                                                                            
None of the above                                                               
