THIS IS LINE 1                                                                  
 12.35                                                                          
 12.3457                                                                        
 12.35                                                                          
ABCDEFGHIJKLMNOPQRSTUVWXYZ                                                      
ABCD                                                                            
