LAT, LONG ? 180,80                                                              
TIME-ZONE MERIDIAN? 6                                                           
AZIMUTH DIAL FACES? 123                                                         
SUN E OR W? W                                                                   
DIAL HEIGHT? 6                                                                  
WIDTH OF THIS PART? 5                                                           
STEP SIZE IN MIN? 2                                                             
                                                                                
LAT:  180   LONG:  80   MERID:  6                                               
DIAL FACES AZIMUTH  123                                                         
STYLE END COORDINATES:                                                          
X= 2.80352E+9 , Y=-6 , Z=-1.82063E+9                                            
SUN W    5 WIDE BY 6 HIGH                                                       
                                                                                
                                                                                
AGAIN (Y OR N)? N                                                               
