                                                                                
INITIAL MASS (KG)  ? 567890                                                     
DENSITY (KG/M^3)   ? 2.345                                                      
SPEED (KM/S)       ? 123456                                                     
ZENITH ANGLE (DEG) ? 76.54                                                      
TIME STEP (SEC)    ? 0.123                                                      
                                                                                
        GROUND                        ATMOS                                     
TIME     TRACK   HEIGHT      SPEED    DECEL      MASS    VISUAL                 
  (S)    (KM)      (KM)      (KM/S) (M/S/S)       (%)       MAG                 
 0        0         155       123456    227707    100      -55.7                
