HOW MANY POINTS? 3                                                              
                                                                                
X,F? 1,6                                                                        
X,F? 2,8                                                                        
X,F? 3,10                                                                       
                                                                                
DESIRED X? 1.5                                                                  
F:  7                                                                           
                                                                                
DESIRED X? 2.5                                                                  
F:  9                                                                           
                                                                                
DESIRED X? X                                                                    
