Year, month, day? 2015,03,01                                                    
Moon's age from new (days):       10.6797                                       
Distance (Earth radii):           62.9648                                       
Ecliptic latitude (degrees):     -5.06297                                       
Ecliptic longitude (degrees):     113.748                                       
                                                                                
Continue (y or n)? n                                                            
