NAME OF COMET? AAA                                                              
MONTH (3 LETTERS)? MAR                                                          
HOW MANY DATES (2-5)? 2                                                         
DAY, RA(H.M), DE(D.M):                                                          
 ? 1,2.3,4.5                                                                    
 ? 31,6.7,8.9                                                                   
STARTING DATE? 1                                                                
                                                                                
AAA                                                                             
                                                                                
MAR 1        RA(H.M)      DE(D.M)                                               
  ( 1950.0)   2.3         4.5                                                   
  ( 1987.0)   2.31938     4.59804                                               
  ARCSEC/MIN   5.82557                                                          
  POS ANGLE    86                                                               
  STEPS  7.25024 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8485  KHZ                                                           
                                                                                
MAR 2        RA(H.M)      DE(D.M)                                               
  ( 1950.0)   2.39333     4.59333                                               
  ( 1987.0)   2.41275     5.08823                                               
  ARCSEC/MIN   5.82422                                                          
  POS ANGLE    86                                                               
  STEPS  7.24856 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8451  KHZ                                                           
                                                                                
MAR 3        RA(H.M)      DE(D.M)                                               
  ( 1950.0)   2.48667     5.08667                                               
  ( 1987.0)   2.50612     5.17826                                               
  ARCSEC/MIN   5.82283                                                          
  POS ANGLE    86                                                               
  STEPS  7.24683 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8415  KHZ                                                           
                                                                                
MAR 4        RA(H.M)      DE(D.M)                                               
  ( 1950.0)   2.58        5.18                                                  
  ( 1987.0)   2.59949     5.26814                                               
  ARCSEC/MIN   5.8214                                                           
  POS ANGLE    86                                                               
  STEPS  7.24505 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8379  KHZ                                                           
                                                                                
MAR 5        RA(H.M)      DE(D.M)                                               
  ( 1950.0)   3.07333     5.27333                                               
  ( 1987.0)   3.09286     5.35787                                               
  ARCSEC/MIN   5.81992                                                          
  POS ANGLE    86                                                               
  STEPS  7.24321 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8341  KHZ                                                           
                                                                                
MAR 6        RA(H.M)      DE(D.M)                                               
  ( 1950.0)   3.16667     5.36667                                               
  ( 1987.0)   3.18623     5.44747                                               
  ARCSEC/MIN   5.8184                                                           
  POS ANGLE    86                                                               
  STEPS  7.24131 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8302  KHZ                                                           
                                                                                
MAR 7        RA(H.M)      DE(D.M)                                               
  ( 1950.0)   3.26        5.46                                                  
  ( 1987.0)   3.27961     5.53693                                               
  ARCSEC/MIN   5.81683                                                          
  POS ANGLE    86                                                               
  STEPS  7.23937 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8262  KHZ                                                           
                                                                                
MAR 8        RA(H.M)      DE(D.M)                                               
  ( 1950.0)   3.35333     5.55333                                               
  ( 1987.0)   3.37298     6.02626                                               
  ARCSEC/MIN   5.81523                                                          
  POS ANGLE    86                                                               
  STEPS  7.23737 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8221  KHZ                                                           
                                                                                
MAR 9        RA(H.M)      DE(D.M)                                               
  ( 1950.0)   3.44667     6.04667                                               
  ( 1987.0)   3.46635     6.11547                                               
  ARCSEC/MIN   5.81358                                                          
  POS ANGLE    86                                                               
  STEPS  7.23532 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8179  KHZ                                                           
                                                                                
MAR 10       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   3.54        6.14                                                  
  ( 1987.0)   3.55972     6.20457                                               
  ARCSEC/MIN   5.81189                                                          
  POS ANGLE    86                                                               
  STEPS  7.23321 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8136  KHZ                                                           
                                                                                
MAR 11       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   4.03333     6.23333                                               
  ( 1987.0)   4.05309     6.29356                                               
  ARCSEC/MIN   5.81015                                                          
  POS ANGLE    86                                                               
  STEPS  7.23105 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8092  KHZ                                                           
                                                                                
MAR 12       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   4.12667     6.32667                                               
  ( 1987.0)   4.14646     6.38245                                               
  ARCSEC/MIN   5.80838                                                          
  POS ANGLE    86                                                               
  STEPS  7.22884 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8047  KHZ                                                           
                                                                                
MAR 13       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   4.22        6.42                                                  
  ( 1987.0)   4.23984     6.47125                                               
  ARCSEC/MIN   5.80656                                                          
  POS ANGLE    86                                                               
  STEPS  7.22658 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.8  KHZ                                                              
                                                                                
MAR 14       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   4.31333     6.51333                                               
  ( 1987.0)   4.3332      6.55996                                               
  ARCSEC/MIN   5.80469                                                          
  POS ANGLE    86                                                               
  STEPS  7.22426 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7953  KHZ                                                           
                                                                                
MAR 15       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   4.40667     7.00667                                               
  ( 1987.0)   4.42657     7.04859                                               
  ARCSEC/MIN   5.80279                                                          
  POS ANGLE    86                                                               
  STEPS  7.22189 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7904  KHZ                                                           
                                                                                
MAR 16       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   4.5         7.1                                                   
  ( 1987.0)   4.51994     7.13716                                               
  ARCSEC/MIN   5.80084                                                          
  POS ANGLE    86                                                               
  STEPS  7.21946 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7855  KHZ                                                           
                                                                                
MAR 17       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   4.59333     7.19333                                               
  ( 1987.0)   5.01331     7.22566                                               
  ARCSEC/MIN   5.79885                                                          
  POS ANGLE    86                                                               
  STEPS  7.21698 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7804  KHZ                                                           
                                                                                
MAR 18       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   5.08667     7.28667                                               
  ( 1987.0)   5.10668     7.31411                                               
  ARCSEC/MIN   5.79682                                                          
  POS ANGLE    86                                                               
  STEPS  7.21445 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7752  KHZ                                                           
                                                                                
MAR 19       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   5.18        7.38                                                  
  ( 1987.0)   5.20004     7.40252                                               
  ARCSEC/MIN   5.79474                                                          
  POS ANGLE    86                                                               
  STEPS  7.21187 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7699  KHZ                                                           
                                                                                
MAR 20       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   5.27333     7.47333                                               
  ( 1987.0)   5.2934      7.49089                                               
  ARCSEC/MIN   5.79262                                                          
  POS ANGLE    86                                                               
  STEPS  7.20923 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7645  KHZ                                                           
                                                                                
MAR 21       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   5.36667     7.56667                                               
  ( 1987.0)   5.38676     7.57923                                               
  ARCSEC/MIN   5.79046                                                          
  POS ANGLE    86                                                               
  STEPS  7.20654 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.759  KHZ                                                            
                                                                                
MAR 22       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   5.46        8.06                                                  
  ( 1987.0)   5.48012     8.06754                                               
  ARCSEC/MIN   5.78825                                                          
  POS ANGLE    86                                                               
  STEPS  7.2038 HZ                                                              
  RATIO  5                                                                      
  FREQ   14.7534  KHZ                                                           
                                                                                
MAR 23       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   5.55333     8.15333                                               
  ( 1987.0)   5.57348     8.15585                                               
  ARCSEC/MIN   5.78601                                                          
  POS ANGLE    86                                                               
  STEPS  7.201 HZ                                                               
  RATIO  5                                                                      
  FREQ   14.7476  KHZ                                                           
                                                                                
MAR 24       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   6.04667     8.24667                                               
  ( 1987.0)   6.06684     8.24415                                               
  ARCSEC/MIN   5.78372                                                          
  POS ANGLE    86                                                               
  STEPS  7.19815 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7418  KHZ                                                           
                                                                                
MAR 25       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   6.14        8.34                                                  
  ( 1987.0)   6.16019     8.33246                                               
  ARCSEC/MIN   5.78138                                                          
  POS ANGLE    86                                                               
  STEPS  7.19525 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7359  KHZ                                                           
                                                                                
MAR 26       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   6.23333     8.43333                                               
  ( 1987.0)   6.25355     8.42077                                               
  ARCSEC/MIN   5.77901                                                          
  POS ANGLE    86                                                               
  STEPS  7.19229 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7298  KHZ                                                           
                                                                                
MAR 27       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   6.32667     8.52667                                               
  ( 1987.0)   6.34689     8.50911                                               
  ARCSEC/MIN   5.77659                                                          
  POS ANGLE    86                                                               
  STEPS  7.18928 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7236  KHZ                                                           
                                                                                
MAR 28       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   6.42        9.02                                                  
  ( 1987.0)   6.44024     8.59748                                               
  ARCSEC/MIN   5.77413                                                          
  POS ANGLE    86                                                               
  STEPS  7.18622 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7174  KHZ                                                           
                                                                                
MAR 29       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   6.51333     9.11333                                               
  ( 1987.0)   6.53359     9.08589                                               
  ARCSEC/MIN   5.77163                                                          
  POS ANGLE    86                                                               
  STEPS  7.1831 HZ                                                              
  RATIO  5                                                                      
  FREQ   14.711  KHZ                                                            
                                                                                
MAR 30       RA(H.M)      DE(D.M)                                               
  ( 1950.0)   7.00667     9.20667                                               
  ( 1987.0)   7.02693     9.17434                                               
  ARCSEC/MIN   5.76908                                                          
  POS ANGLE    86                                                               
  STEPS  7.17994 HZ                                                             
  RATIO  5                                                                      
  FREQ   14.7045  KHZ                                                           
