LONGEST USEFUL PERIOD TO TRY =  44.8735                                         
LONGEST PERIOD TO TRY THIS RUN ? 31                                             
COARSE, MEDIUM OR FINE (C,M,F)? C                                               
MAXIMUM NUMBER OF TRIALS ? 24                                                   
THEN SHORTEST ALLOWABLE PERIOD =  11.9741                                       
SHORTEST PERIOD TO TRY THIS RUN ? 11                                            
TRIAL #       PERIOD         FREQUENCY      STRENGTH                            
 9             19.9657        .050086        2.01562                            
 10            19.1152        5.23144E-2     2.59658                            
 11            18.3342        5.45429E-2     2.54603                            
                                                                                
 24            11.9741        8.35133E-2     3.15297                            
 25            11.6629        8.57417E-2     5.25591                            
 26            11.3675        8.79702E-2     6.32874                            
 27            11.0866        9.01987E-2     5.74238                            
                                                                                
              PERIOD         FREQUENCY      STRENGTH                            
AVERAGE                                      1.33936                            
BEST           11.3675        8.79702E-2     6.32874                            
AMPLITUDE ESTIMATE =  .243                                                      
