Please Enter SCALE LENGTH in mm - ? 250                                         
                                                                                
Do you want the scale in Degrees or Hours and Minutes?                          
        Please indicate 'd' for Degrees or 'h' for Hours... ? d                 
                                                                                
                                                                                
                                                                                
Printing.......                                                                 
                                                                                
NOTE: This will take up to 90 seconds to print.                                 
