YEAR? 2015                                                                      
QU'DNTDS      JAN  4.2                                                          
LYRIDS        APR 23.1                                                          
ETA AQR       MAY  5.9                                                          
DLT AQR       JUL 28.6                                                          
PERSEIDS      AUG 13.2                                                          
ORIONIDS      OCT 22.6                                                          
TAURIDS       NOV  3.9                                                          
LEONIDS       NOV 18.9                                                          
GEMINIDS      DEC 14.6                                                          
