SELECT PHOTO METHOD--                                                           
  (A) PRIME FOCUS                                                               
  (B) BARLOW PROJ.                                                              
  (C) EYEPIECE PROJ.                                                            
  (D) AFOCAL METHOD                                                             
  (E) QUIT                                                                      
? A                                                                             
                                                                                
OBJECTIVE F.L.? 7.89                                                            
APERTURE? 1.23                                                                  
                                                                                
EXAMPLE F/NUMBER? 2.5                                                           
EXAMPLE FILM INDEX? 600                                                         
EXAMPLE TIME? 360                                                               
                                                                                
YOUR FILM INDEX? 1200                                                           
 1185.05  IS YOUR TIME                                                          
                                                                                
NEXT?                                                                           
SELECT PHOTO METHOD--                                                           
  (A) PRIME FOCUS                                                               
  (B) BARLOW PROJ.                                                              
  (C) EYEPIECE PROJ.                                                            
  (D) AFOCAL METHOD                                                             
  (E) QUIT                                                                      
? E                                                                             
                                                                                
