Zenith distance (deg.): ? 174                                                   
                                                                                
Airmass (gas, aerosol, ozone):      0.00    0.00    1.01                        
Extinction Coefficients (UBVRI):    0.66    0.36    0.22    0.11    0.06        
Total Extinction (UBVRI):           0.00    0.00    0.03    0.01    0.00        
Sky brightness (UBVRI): 5.71274e-14 4.99965e-14 7.14300e-14 7.14351e-14         
2.14312e-13                                                                     
                                                                                
Visual Sky Brightness (nL):     64                                              
Visual Limiting Magnitude:    6.50                                              
