                                                                                
DISTANCE? 98765                                                                 
WAVELENGTH =  661                                                               
                                                                                
DISTANCE? 43321                                                                 
WAVELENGTH =  668                                                               
                                                                                
DISTANCE? -1                                                                    
