 [2J [1;1H [8;11HDATE IS SET TO 12/15/15 . IS THIS CORRECT ? ? Y                
 [2J [1;1H [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                 
 [2;54H12/15/15                                                                 
 [8;25HENTER PASSWORD ---> ? TXT                                                
 [8;25HINITIALIZING                                                             
 [3;1H  [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                    
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 1                                                           
 [2J [1;1H                   INPUT NEW ITEMS                                    
                                                                                
 [5;26H  [5;1H0 - STOCK # -------->                                             
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [3;1H  (TYPE @ TO EXIT TO MAIN MENU) [5;26H? ABCD1234    
 [3;1H  (TYPE @ TO REDO ENTRY) [6;26H? WIDGET                                   
 [7;26H? 111                                                                    
 [8;26H? 1.11                                                                   
  [9;26H? 11.11                                                                 
  [9;41HGROSS PROFIT=  90.0 % [10;26H? STOCKROOM 1                              
 [11;26H? 100                                                                   
 / ? 10                                                                         
 [12;26H? 11                                                                    
 [13;26H? 11/11/11                                                              
 [14;26H? V1                                                                    
 [10;41HCURRENT SALES   :  0  [11;41HCUMULATIVE SALES:  0  [5;1H0 - STOCK # ----
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [5;26H  [5;1H0 - STOCK # -------->                       
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [3;1H  (TYPE @ TO EXIT TO MAIN MENU) [5;40H(LAST ENTRY: A
 [2J [1;1H [8;17HLOADING IN DATA FOR SORT                                       
*** RUNNING DATASORT ***                                                        
 [2J [1;1H [8;21HSORT IS IN PROGRESS                                            
 [2J [1;1H [8;21HSORT COMPLETE. SAVING FILES                                    
 [2J [1;1H [8;21HALL OPERATIONS COMPLETE                                        
 [10;21HRETURNING TO MAIN MENU                                                  
 [2J [1;1H [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                 
 [2;54H12/15/15                                                                 
 [3;1H  [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                    
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 3                                                           
 [2J [1;1H              OUTPUT REPORTS AND SUMMARIES                            
                                                                                
OPTIONS:                                                                        
                                                                                
1 - PRINTOUT COMPLETE LISTING                                                   
2 - PRINTOUT OF NOT-IN-STOCK ITEMS                                              
3 - PRINTOUT ALL ITEMS ON ORDER                                                 
4 - PRINTOUT ALL ITEMS AT OR BELOW REORDER POINT                                
5 - PRINTOUT BY VENDOR                                                          
6 - PRINTOUT BY PREFIX / SUFFIX                                                 
7 - PRINT SUGGESTED PURCHASE ORDER TO VENDOR                                    
8 - TEST PRINTER                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT OPTION --> ? 1                                                           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [8;9HDO YOU WANT TO SUPPRESS COST AND PROFIT FIGURES ? ? N           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [2J [1;1H              OUTPUT REPORTS AND SUMMARIES                  
                                                                                
OPTIONS:                                                                        
                                                                                
1 - PRINTOUT COMPLETE LISTING                                                   
2 - PRINTOUT OF NOT-IN-STOCK ITEMS                                              
3 - PRINTOUT ALL ITEMS ON ORDER                                                 
4 - PRINTOUT ALL ITEMS AT OR BELOW REORDER POINT                                
5 - PRINTOUT BY VENDOR                                                          
6 - PRINTOUT BY PREFIX / SUFFIX                                                 
7 - PRINT SUGGESTED PURCHASE ORDER TO VENDOR                                    
8 - TEST PRINTER                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT OPTION --> ? @                                                           
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 2                                                           
 [2J [1;1H                   ACCESS / UPDATE DATA                               
                                                                                
 [5;26H  [5;1H0 - STOCK # -------->                                             
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [3;1H                                                    
  [3;1HENTER STOCK # (TYPE @ TO EXIT) ----> ? ABCD1234                          
 [5;26H  [5;1H0 - STOCK # -------->                                             
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [5;26HABCD1234   [6;26HWIDGET                            
 [7;26H 111                                                                     
 [8;26H   1.11                                                                  
 [9;26H  11.11                                                                  
 [9;41HGROSS PROFIT=  90.0 % [10;26HSTOCKROOM                                   
 [11;26H 100 / 10                                                               
 [12;26H 11                                                                     
 [13;26H11/11/11                                                                
 [14;26HV1                                                                      
 [10;41HCURRENT SALES   :  0  [11;41HCUMULATIVE SALES:  0  [3;1H                
  [3;1HSELECT (U)PDATE, (S)EARCH, (N)EXT ITEM, (P)REVIOUS ITEM,                 
(A)DJUST QTY, (D)ELETE, (@) TO EXIT TO MAIN MENU --> ? @                        
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 9                                                           
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
                   SYSTEM STATUS REPORT                                         
                                                                                
                                                                                
NUMBER OF ITEMS CURRENTLY IN LISTING:  1                                        
NUMBER OF UNPOSTED SALES TICKETS:  0                                            
TOTAL COST (WHOLESALE) VALUE:       $123.21                                     
TOTAL RETAIL SALE VALUE ----:     $1,233.21                                     
TOTAL VALUE OF ITEMS ORDERED:        $12.21                                     
                                                                                
         TYPE @ TO RETURN TO MAIN MENU --> ? @                                  
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 5                                                           
 [2J [1;1H                    ENTER SALES TICKETS                               
                                                                                
 [3;1H  (TYPE @ TO EXIT TO MAIN MENU) [5;1H                                     
 [5;1HSTOCK NUMBER: ? ABCD1234                                                  
 [3;1H  (TYPE @ TO REDO ENTRY) [7;1HQUANTITY SOLD: ? 12                         
 [3;1H  (TYPE @ TO EXIT TO MAIN MENU) [5;1H                                     
 [5;40H(LAST ENTRY: ABCD1234) [5;1HSTOCK NUMBER: ? @                            
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 9                                                           
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
                   SYSTEM STATUS REPORT                                         
                                                                                
                                                                                
NUMBER OF ITEMS CURRENTLY IN LISTING:  1                                        
NUMBER OF UNPOSTED SALES TICKETS:  1                                            
TOTAL COST (WHOLESALE) VALUE:       $123.21                                     
TOTAL RETAIL SALE VALUE ----:     $1,233.21                                     
TOTAL VALUE OF ITEMS ORDERED:        $12.21                                     
                                                                                
         TYPE @ TO RETURN TO MAIN MENU --> ? @                                  
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 6                                                           
 [2J [1;1H                   END OF PERIOD PROCESSING                           
                                                                                
 [3;1HFUNCTIONS:                                                                
                                                                                
1 - POST SALES TICKETS AND CLEAR TICKET FILE                                    
                                                                                
2 - CLEAR CURRENT SALES FIGURES FROM INVENTORY                                  
                                                                                
3 - CLEAR CURRENT AND CUMULATIVE SALES FIGURES FROM INVENTORY                   
                                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT FUNCTION > ? 1                                                           
 [2J [1;1H [8;21HpOSTING IN PROGRESS                                            
 [10;21HTICKETS REMAINING:  0                                                   
 [2J [1;1H                   END OF PERIOD PROCESSING                           
                                                                                
 [3;1HFUNCTIONS:                                                                
                                                                                
1 - POST SALES TICKETS AND CLEAR TICKET FILE                                    
                                                                                
2 - CLEAR CURRENT SALES FIGURES FROM INVENTORY                                  
                                                                                
3 - CLEAR CURRENT AND CUMULATIVE SALES FIGURES FROM INVENTORY                   
                                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT FUNCTION > ? @                                                           
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 9                                                           
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
                   SYSTEM STATUS REPORT                                         
                                                                                
                                                                                
NUMBER OF ITEMS CURRENTLY IN LISTING:  1                                        
NUMBER OF UNPOSTED SALES TICKETS:  0                                            
TOTAL COST (WHOLESALE) VALUE:       $109.89                                     
TOTAL RETAIL SALE VALUE ----:     $1,099.89                                     
TOTAL VALUE OF ITEMS ORDERED:        $12.21                                     
                                                                                
         TYPE @ TO RETURN TO MAIN MENU --> ? @                                  
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 3                                                           
 [2J [1;1H              OUTPUT REPORTS AND SUMMARIES                            
                                                                                
OPTIONS:                                                                        
                                                                                
1 - PRINTOUT COMPLETE LISTING                                                   
2 - PRINTOUT OF NOT-IN-STOCK ITEMS                                              
3 - PRINTOUT ALL ITEMS ON ORDER                                                 
4 - PRINTOUT ALL ITEMS AT OR BELOW REORDER POINT                                
5 - PRINTOUT BY VENDOR                                                          
6 - PRINTOUT BY PREFIX / SUFFIX                                                 
7 - PRINT SUGGESTED PURCHASE ORDER TO VENDOR                                    
8 - TEST PRINTER                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT OPTION --> ? 1                                                           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [8;9HDO YOU WANT TO SUPPRESS COST AND PROFIT FIGURES ? ? N           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [2J [1;1H              OUTPUT REPORTS AND SUMMARIES                  
                                                                                
OPTIONS:                                                                        
                                                                                
1 - PRINTOUT COMPLETE LISTING                                                   
2 - PRINTOUT OF NOT-IN-STOCK ITEMS                                              
3 - PRINTOUT ALL ITEMS ON ORDER                                                 
4 - PRINTOUT ALL ITEMS AT OR BELOW REORDER POINT                                
5 - PRINTOUT BY VENDOR                                                          
6 - PRINTOUT BY PREFIX / SUFFIX                                                 
7 - PRINT SUGGESTED PURCHASE ORDER TO VENDOR                                    
8 - TEST PRINTER                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT OPTION --> ? @                                                           
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 8                                                           
 [2J [1;1H              ENTER ITEMS PLACED ON ORDER                             
                                                                                
 [5;26H  [5;1H0 - STOCK # -------->                                             
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [3;1H                                                    
  [3;1HENTER STOCK# (TYPE @ TO EXIT) ----> ? ABCD1234                           
 [5;26H  [5;1H0 - STOCK # -------->                                             
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [5;26HABCD1234   [6;26HWIDGET                            
 [7;26H 99                                                                      
 [8;26H   1.11                                                                  
 [9;26H  11.11                                                                  
 [9;41HGROSS PROFIT=  90.0 % [10;26HSTOCKROOM                                   
 [11;26H 100 / 10                                                               
 [12;26H 11                                                                     
 [13;26H11/11/11                                                                
 [14;26HV1                                                                      
 [10;41HCURRENT SALES   :  12  [11;41HCUMULATIVE SALES:  12  [3;1H              
  [3;1HQUANTITY ORDERED (HIT <ENTER> FOR DEFAULT QTY): ? 34                     
 [3;1H                                                                          
  [3;1HDATE OF ORDER (HIT <eNTER> FOR LAST ENTERED DATE): ? 12/12/12            
 [5;1H0 - STOCK # -------->                                                     
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [6;26HWIDGET                                             
 [7;26H 99                                                                      
 [8;26H   1.11                                                                  
 [9;26H  11.11                                                                  
 [9;41HGROSS PROFIT=  90.0 % [10;26HSTOCKROOM                                   
 [11;26H 100 / 10                                                               
 [12;26H 45                                                                     
 [13;26H12/12/12                                                                
 [14;26HV1                                                                      
 [10;41HCURRENT SALES   :  12  [11;41HCUMULATIVE SALES:  12  [3;1H              
  [3;1HENTER STOCK# (TYPE @ TO EXIT) ----> ? @                                  
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 3                                                           
 [2J [1;1H              OUTPUT REPORTS AND SUMMARIES                            
                                                                                
OPTIONS:                                                                        
                                                                                
1 - PRINTOUT COMPLETE LISTING                                                   
2 - PRINTOUT OF NOT-IN-STOCK ITEMS                                              
3 - PRINTOUT ALL ITEMS ON ORDER                                                 
4 - PRINTOUT ALL ITEMS AT OR BELOW REORDER POINT                                
5 - PRINTOUT BY VENDOR                                                          
6 - PRINTOUT BY PREFIX / SUFFIX                                                 
7 - PRINT SUGGESTED PURCHASE ORDER TO VENDOR                                    
8 - TEST PRINTER                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT OPTION --> ? 3                                                           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [8;9HDO YOU WANT TO SUPPRESS COST AND PROFIT FIGURES ? ? N           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [2J [1;1H              OUTPUT REPORTS AND SUMMARIES                  
                                                                                
OPTIONS:                                                                        
                                                                                
1 - PRINTOUT COMPLETE LISTING                                                   
2 - PRINTOUT OF NOT-IN-STOCK ITEMS                                              
3 - PRINTOUT ALL ITEMS ON ORDER                                                 
4 - PRINTOUT ALL ITEMS AT OR BELOW REORDER POINT                                
5 - PRINTOUT BY VENDOR                                                          
6 - PRINTOUT BY PREFIX / SUFFIX                                                 
7 - PRINT SUGGESTED PURCHASE ORDER TO VENDOR                                    
8 - TEST PRINTER                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT OPTION --> ? 1                                                           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [8;9HDO YOU WANT TO SUPPRESS COST AND PROFIT FIGURES ? ? N           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [2J [1;1H              OUTPUT REPORTS AND SUMMARIES                  
                                                                                
OPTIONS:                                                                        
                                                                                
1 - PRINTOUT COMPLETE LISTING                                                   
2 - PRINTOUT OF NOT-IN-STOCK ITEMS                                              
3 - PRINTOUT ALL ITEMS ON ORDER                                                 
4 - PRINTOUT ALL ITEMS AT OR BELOW REORDER POINT                                
5 - PRINTOUT BY VENDOR                                                          
6 - PRINTOUT BY PREFIX / SUFFIX                                                 
7 - PRINT SUGGESTED PURCHASE ORDER TO VENDOR                                    
8 - TEST PRINTER                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT OPTION --> ? @                                                           
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 9                                                           
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
                   SYSTEM STATUS REPORT                                         
                                                                                
                                                                                
NUMBER OF ITEMS CURRENTLY IN LISTING:  2                                        
NUMBER OF UNPOSTED SALES TICKETS:  0                                            
TOTAL COST (WHOLESALE) VALUE:       $219.78                                     
TOTAL RETAIL SALE VALUE ----:     $2,199.78                                     
TOTAL VALUE OF ITEMS ORDERED:        $99.90                                     
                                                                                
         TYPE @ TO RETURN TO MAIN MENU --> ? @                                  
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 7                                                           
 [2J [1;1H         ENTER RECEIPTS OF ON-ORDER ITEMS                             
                                                                                
 [5;26H  [5;1H0 - STOCK # -------->                                             
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [3;1H                                                    
  [3;1HENTER STOCK# (TYPE @ TO EXIT) ----> ? ABCD1234                           
 [5;26H  [5;1H0 - STOCK # -------->                                             
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [5;26HABCD1234   [6;26HWIDGET                            
 [7;26H 99                                                                      
 [8;26H   1.11                                                                  
 [9;26H  11.11                                                                  
 [9;41HGROSS PROFIT=  90.0 % [10;26HSTOCKROOM                                   
 [11;26H 100 / 10                                                               
 [12;26H 45                                                                     
 [13;26H12/12/12                                                                
 [14;26HV1                                                                      
 [10;41HCURRENT SALES   :  12  [11;41HCUMULATIVE SALES:  12  [3;1H              
  [3;1HQUANTITY RECEIVED: ? 31                                                  
 [3;1H                                                                          
  [3;1HCHANGE IN COST (HIT <ENTER> TO SKIP): ? 2.22                             
  [3;1H                                                                         
  [3;1HCHANGE IN SELL PRICE (HIT <ENTER> TO SKIP): ? 12.13                      
  [5;1H0 - STOCK # -------->                                                    
1 - DESCRIPTION ---->                                                           
2 - QUANTITY ------->                                                           
3 - COST ----------->                                                           
4 - SELL ----------->                                                           
5 - LOCATION ------->                                                           
6 - REORDER PT/QTY-->                                                           
7 - # ON ORDER ----->                                                           
8 - DATE LAST ORDER->                                                           
9 - VENDOR --------->  [6;26HWIDGET                                             
 [7;26H 130                                                                     
 [8;26H   2.22                                                                  
 [9;26H  12.13                                                                  
 [9;41HGROSS PROFIT=  81.7 % [10;26HSTOCKROOM                                   
 [11;26H 100 / 10                                                               
 [12;26H 14                                                                     
 [13;26H12/12/12                                                                
 [14;26HV1                                                                      
 [10;41HCURRENT SALES   :  12  [11;41HCUMULATIVE SALES:  12  [3;1H              
  [3;1HENTER STOCK# (TYPE @ TO EXIT) ----> ? @                                  
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 9                                                           
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
                   SYSTEM STATUS REPORT                                         
                                                                                
                                                                                
NUMBER OF ITEMS CURRENTLY IN LISTING:  2                                        
NUMBER OF UNPOSTED SALES TICKETS:  0                                            
TOTAL COST (WHOLESALE) VALUE:       $398.49                                     
TOTAL RETAIL SALE VALUE ----:     $2,676.79                                     
TOTAL VALUE OF ITEMS ORDERED:        $81.03                                     
                                                                                
         TYPE @ TO RETURN TO MAIN MENU --> ? @                                  
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? 3                                                           
 [2J [1;1H              OUTPUT REPORTS AND SUMMARIES                            
                                                                                
OPTIONS:                                                                        
                                                                                
1 - PRINTOUT COMPLETE LISTING                                                   
2 - PRINTOUT OF NOT-IN-STOCK ITEMS                                              
3 - PRINTOUT ALL ITEMS ON ORDER                                                 
4 - PRINTOUT ALL ITEMS AT OR BELOW REORDER POINT                                
5 - PRINTOUT BY VENDOR                                                          
6 - PRINTOUT BY PREFIX / SUFFIX                                                 
7 - PRINT SUGGESTED PURCHASE ORDER TO VENDOR                                    
8 - TEST PRINTER                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT OPTION --> ? 3                                                           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [8;9HDO YOU WANT TO SUPPRESS COST AND PROFIT FIGURES ? ? N           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [2J [1;1H              OUTPUT REPORTS AND SUMMARIES                  
                                                                                
OPTIONS:                                                                        
                                                                                
1 - PRINTOUT COMPLETE LISTING                                                   
2 - PRINTOUT OF NOT-IN-STOCK ITEMS                                              
3 - PRINTOUT ALL ITEMS ON ORDER                                                 
4 - PRINTOUT ALL ITEMS AT OR BELOW REORDER POINT                                
5 - PRINTOUT BY VENDOR                                                          
6 - PRINTOUT BY PREFIX / SUFFIX                                                 
7 - PRINT SUGGESTED PURCHASE ORDER TO VENDOR                                    
8 - TEST PRINTER                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT OPTION --> ? 7                                                           
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1H [8;3HENTER ENOUGH LETTERS TO IDENTIFY VENDOR --> ? V1                
 [3;1H                                                                          
 [8;23H** PRINTING **                                                           
 [2J [1;1HOPTIONS:                                                              
                                                                                
1 - PRINTOUT COMPLETE LISTING                                                   
2 - PRINTOUT OF NOT-IN-STOCK ITEMS                                              
3 - PRINTOUT ALL ITEMS ON ORDER                                                 
4 - PRINTOUT ALL ITEMS AT OR BELOW REORDER POINT                                
5 - PRINTOUT BY VENDOR                                                          
6 - PRINTOUT BY PREFIX / SUFFIX                                                 
7 - PRINT SUGGESTED PURCHASE ORDER TO VENDOR                                    
8 - TEST PRINTER                                                                
@ - EXIT TO MAIN MENU                                                           
                                                                                
SELECT OPTION --> ? @                                                           
 [2J [1;1H            TRS-80 INVENTORY CONTROL SYSTEM                           
 [2;54H12/15/15                                                                 
FUNCTIONS:                                                                      
                                                                                
1 - INPUT NEW ITEMS                                                             
2 - ACCESS / UPDATE                                                             
3 - OUTPUT REPORTS AND SUMMARIES                                                
4 - CREATE NEW INVENTORY                                                        
5 - ENTER SALES TICKETS                                                         
6 - END OF PERIOD PROCESSING                                                    
7 - ENTER RECEIPTS OF ON-ORDER ITEMS                                            
8 - ENTER ITEMS PLACED ON ORDER                                                 
9 - DISPLAY SYSTEM STATUS                                                       
@ - EXIT FROM PROGRAM                                                           
                                                                                
SELECT FUNCTION > ? @                                                           
 [2J [1;1H [8;25HEND OF PROGRAM                                                 
                                                                                
                                                                                
