PROGRAM FILE 81: ERROR - DIM-STATEMENT PRECEDES                                 
        OPTION-STATEMENT.                                                       
    ANSI STANDARD 15.4                                                          
                                                                                
*** NOTE: THIS PROGRAM MAKES USE OF THE INPUT STATEMENT                         
    WHICH HAS NOT YET BEEN TESTED. IF SUBSEQUENT TESTS SHOW                     
    THIS FEATURE TO BE INCORRECTLY IMPLEMENTED, THEN THE                        
    VALIDITY OF THE RESULTS OF THIS TEST ROUTINE IS DOUBTFUL.                   
                                                                                
SECTION 81.1: ERROR - DIM-STATEMENT PRECEDES                                    
        OPTION-STATEMENT.                                                       
                                                                                
THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC.                     
TO PASS THIS TEST, THE PROCESSOR MUST EITHER:                                   
                                                                                
   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION                    
      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION                        
      BY THE PROCESSOR, OR                                                      
                                                                                
   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE                      
                                                                                
SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL                           
FOR DETAILED CRITERIA.                                                          
                                                                                
               BEGIN TEST                                                       
                                                                                
TO HELP IN CHECKING INTERPRETATION, YOU MAY ENTER                               
VALUES TO BE USED AS SUBSCRIPTS ON THE ARRAY. THE PROGRAM                       
WILL ASSIGN THE VALUE 777 TO THE INDICATED ELEMENT AND                          
THEN ECHO THE RESULT. IN THIS WAY YOU CAN CHECK WHICH                           
SUBSCRIPTS ARE WITHIN THE ARRAY AND WHICH CAUSE EXCEPTIONS.                     
THE ARRAY IS SET WITH 'DIM A(5)', FOLLOWED BY OPTION BASE 1.                    
YOU SHOULD AT LEAST TEST SUBSCRIPT VALUES OF ZERO                               
AND SIX.  THE ARRAY HAS BEEN DIMENSIONED AS A(5).                               
                                                                                
ENTER 100 WHEN YOU WISH TO STOP.                                                
                                                                                
ENTER VALUE TO BE USED AS SUBSCRIPT:                                            
? 0                                                                             
A( 0 ) =  777                                                                   
                                                                                
ENTER VALUE TO BE USED AS SUBSCRIPT:                                            
? 1                                                                             
A( 1 ) =  777                                                                   
                                                                                
ENTER VALUE TO BE USED AS SUBSCRIPT:                                            
? 2                                                                             
A( 2 ) =  777                                                                   
                                                                                
ENTER VALUE TO BE USED AS SUBSCRIPT:                                            
? 3                                                                             
A( 3 ) =  777                                                                   
                                                                                
ENTER VALUE TO BE USED AS SUBSCRIPT:                                            
? 4                                                                             
A( 4 ) =  777                                                                   
                                                                                
ENTER VALUE TO BE USED AS SUBSCRIPT:                                            
? 5                                                                             
A( 5 ) =  777                                                                   
                                                                                
ENTER VALUE TO BE USED AS SUBSCRIPT:                                            
? 100                                                                           
                                                                                
               END TEST                                                         
                                                                                
END PROGRAM 81                                                                  
