PROGRAM FILE 105: ERROR - NULL DATUM IN DATA-LIST.                              
    ANSI STANDARD 14.2                                                          
                                                                                
SECTION 105.1: ERROR - NULL DATUM IN DATA-LIST.                                 
                                                                                
                                                                                
THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC.                     
TO PASS THIS TEST, THE PROCESSOR MUST EITHER:                                   
                                                                                
   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION                    
      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION                        
      BY THE PROCESSOR, OR                                                      
                                                                                
   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE                      
                                                                                
SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL                           
FOR DETAILED CRITERIA.                                                          
                                                                                
               BEGIN TEST                                                       
                                                                                
A$, B$, AND C$ INITIALIZED TO 'AAAAA', 'BBBBB', AND                             
'CCCCC', RESPECTIVELY. ABOUT TO READ A$, B$, C$ FROM                            
'DATA ABC,,GHI,JKL'.                                                            
                                                                                
                                                                                
ERROR in line 300: Bad DATA                                                     
