PROGRAM FILE 108: INPUT TO SUBSCRIPTED VARIABLES.                               
    ANSI STANDARD 13.2, 13.4                                                    
                                                                                
SECTION 108.1: SIMPLE INPUT TO FILL ARRAY.                                      
                                                                                
              BEGIN TEST.                                                       
                                                                                
PLEASE ENTER: 0                                                                 
? 0                                                                             
PLEASE ENTER: 1                                                                 
? 1                                                                             
PLEASE ENTER: 2                                                                 
? 2                                                                             
PLEASE ENTER: 3                                                                 
? 3                                                                             
PLEASE ENTER: 4                                                                 
? 4                                                                             
PLEASE ENTER: 5                                                                 
? 5                                                                             
PLEASE ENTER: 6                                                                 
? 6                                                                             
PLEASE ENTER: 7                                                                 
? 7                                                                             
PLEASE ENTER: 8                                                                 
? 8                                                                             
PLEASE ENTER: 9                                                                 
? 9                                                                             
PLEASE ENTER: 10                                                                
? 10                                                                            
                                                                                
                 CONTENTS OF ARRAY                                              
SUBSCRIPT      SHOULD BE      ACTUAL                                            
 0              7              7                                                
 1              3              3                                                
 2              2              2                                                
 3              1              1                                                
 4              9              9                                                
 5              4              4                                                
 6              8              8                                                
 7              0              0                                                
 8              10             10                                               
 9              5              5                                                
 10             6              6                                                
                                                                                
***  TEST PASSED  ***                                                           
                                                                                
              END TEST.                                                         
                                                                                
                                                                                
SECTION 108.2: INPUT OF SUBSCRIPT FOLLOWED BY SUBSCRIPTED                       
        VARIABLE.                                                               
                                                                                
             BEGIN TEST.                                                        
                                                                                
FOR THIS REPLY, STATEMENT IS: INPUT A(I),I,A(I),I,A(I)                          
PLEASE ENTER 500,6,600,2,200                                                    
? 500,6,600,2,200                                                               
                                                                                
                 CONTENTS OF ARRAY                                              
SUBSCRIPT      SHOULD BE      ACTUAL                                            
 0              10             10                                               
 1              11             11                                               
 2              200            200                                              
 3              13             13                                               
 4              14             14                                               
 5              500            500                                              
 6              600            600                                              
 7              17             17                                               
 8              18             18                                               
 9              19             19                                               
 10             20             20                                               
                                                                                
***  TEST PASSED  ***                                                           
                                                                                
               END TEST.                                                        
                                                                                
                                                                                
SECTION 108.3: NO ASSIGNMENT BEFORE VALIDATION OF INPUT.                        
                                                                                
                BEGIN TEST                                                      
                                                                                
THIS SECTION TESTS THAT NO ASSIGNMENT IS DONE BEFORE                            
THE ENTIRE REPLY IS VALIDATED.                                                  
                                                                                
PLEASE ENTER LINE NO. 1 FIRST. IT SHOULD BE REJECTED                            
BECAUSE OF INSUFFICIENT DATA AND YOU SHOULD BE ALLOWED                          
TO RE-SUPPLY INPUT. THEN ENTER LINE NO. 2 (NOTE THE SECOND                      
CHARACTER IS A COMMA RATHER THAN A PERIOD).                                     
                                                                                
*** IF NOT ALLOWED TO RE-SUPPLY INPUT, TEST FAILS ***                           
                                                                                
THE ASSOCIATED INPUT STATEMENT IS: INPUT H,I,J,A(I),K,L                         
THEREFORE, AN 8 SHOULD BE PUT INTO A(1), AND NO OTHER                           
CHANGE MADE TO THE ARRAY.                                                       
                                                                                
LINE NO. 1:    3.1,6,8,9,11                                                     
LINE NO. 2:    3,1,6,8,9,11                                                     
? 3.1,6,8,9,11                                                                  
?Redo from start                                                                
? 3,1,6,8,9,11                                                                  
                                                                                
                 CONTENTS OF ARRAY                                              
SUBSCRIPT      SHOULD BE      ACTUAL                                            
 0              0              0                                                
 1              8              8                                                
 2              200            200                                              
 3              300            300                                              
 4              400            400                                              
 5              500            500                                              
 6              600            600                                              
 7              700            700                                              
 8              800            800                                              
 9              900            900                                              
 10             1000           1000                                             
                                                                                
***  TEST PASSED  ***                                                           
                                                                                
                END TEST                                                        
                                                                                
SECTION 108.4: INPUT TO TWO-DIMENSIONAL ARRAY.                                  
                                                                                
                 BEGIN TEST                                                     
                                                                                
STATEMENT FOR THIS REPLY: INPUT I,J,X(I,J)                                      
PLEASE ENTER 2,3,999                                                            
? 2,3,999                                                                       
                                                                                
X(I,J)         J=1            J=2            J=3                                
I= 1            1001           1002           1003                              
I= 2            2001           2002           999                               
I= 3            3001           3002           3003                              
I= 4            4001           4002           4003                              
I= 5            5001           5002           5003                              
                                                                                
***  TEST PASSED  ***                                                           
                                                                                
                  END TEST                                                      
                                                                                
END PROGRAM 108                                                                 
                                                                                
Program interrupted at line 1090                                                
