PROGRAM FILE 128: ACCURACY OF TAN FUNCTION.                                     
    ANSI STANDARD 7.6, 8.4                                                      
                                                                                
SECTION 128.1: ACCURACY OF TAN FUNCTION.                                        
                                                                                
THIS PROGRAM TESTS VALUES RETURNED BY INVOCATIONS OF THE                        
TAN FUNCTION FOR ACCURACY. THE INVOCATION MUST RETURN,                          
ACCURATE TO SIX DIGITS, SOME VALUE ACTUALLY TAKEN ON BY                         
THE FUNCTION WITHIN A DOMAIN BOUNDED BY THE ACTUAL ARGUMENT                     
PLUS OR MINUS ONE IN THE SIXTH DIGIT. ALSO, AN                                  
'ERROR MEASURE' IS COMPUTED AND REPORTED. THIS MEASURE                          
IS JUST 2 * THE ABSOLUTE ERROR OVER THE SIZE OF THE RANGE;                      
THUS, A VALUE JUST BARELY PASSING OR FAILING WILL USUALLY                       
HAVE A MEASURE OF ABOUT 1. A VALUE 3 TIMES                                      
AS INACCURATE AS EXPECTED WILL HAVE A MEASURE OF 3.                             
                                                                                
THIS TEST IS INFORMATIVE ONLY, SINCE THE ANSI STANDARD                          
DOES NOT MANDATE ANY ACCURACY FOR SUPPLIED-FUNCTIONS.                           
                                                                                
              BEGIN TEST                                                        
                                                                                
ARGUMENT       TRUE           COMPUTED       ERROR          OUTCOME             
               VALUE          VALUE          MEASURE                            
                                                                                
-98778.9       -1.38017       -1.38017        2.64032E-9     OK                 
-9876.54        .724992        .724992        7.58307E-9     OK                 
-987.654       -2.52646       -2.52646        2.62572E-7     OK                 
-98.7654       -5.06921       -5.06921        1.73817E-6     OK                 
-9.87654       -.48523        -.48523         3.70988E-5     OK                 
-5.55555        .890668        .890668        2.14631E-5     OK                 
-4.71239        980762.        980762.       RANGE SPLIT     OK                 
-4.56789       -6.87223       -6.87223        1.97278E-6     OK                 
-4             -1.15782       -1.15782        8.27025E-5     OK                 
-3.14159        2.65359E-6     2.65359E-6     3.36206E-10    OK                 
-2.87654        .271439        .271439        2.81063E-5     OK                 
-2              2.18504        2.18504        5.19805E-5     OK                 
-1.61616        22.0289        22.0289        5.24035E-6     OK                 
-1.57081        73135.7        73135.7        3.48614E-10    OK                 
-1.5708         272242.        272242.       RANGE SPLIT     OK                 
-1.57078       -61249.        -61249.         5.24726E-10    OK                 
-1.23456       -2.86117       -2.86117        1.6459E-5      OK                 
-1             -1.55741       -1.55741        1.18566E-4     OK                 
-.87654        -1.20118       -1.20118        3.85899E-4     OK                 
-.232323       -.236595       -.236595        2.36288E-4     OK                 
-7.67676E-2    -7.69188E-2    -7.69188E-2     2.48291E-4     OK                 
-2.34567E-2    -.023461       -.023461       RANGE SPLIT     OK                 
-1.23456E-2    -1.23462E-2    -1.23462E-2     3.22076E-4     OK                 
-9.87654E-3    -9.87686E-3    -9.87686E-3     1.10671E-4     OK                 
-3.45678E-3    -3.45679E-3    -3.45679E-3     8.00762E-5     OK                 
-9.87654E-4    -9.87654E-4    -9.87654E-4     9.28058E-5     OK                 
-3.45678E-4    -3.45678E-4    -3.45678E-4     1.54126E-4     OK                 
-.00009        -.00009        -.00009         2.86571E-4     OK                 
-9.E-7         -9.E-7         -9.E-7          1.61941E-7     OK                 
-9.E-10        -9.E-10        -9.E-10         0              OK - EXACT         
-9.E-20        -9.E-20        -9.E-20         0              OK - EXACT         
-9.E-30        -9.E-30        -9.E-30         0              OK - EXACT         
-9.E-38        -9.E-38        -9.E-38         0              OK - EXACT         
 0              0              0             RANGE ZERO      OK - EXACT         
 9.E-38         9.E-38         9.E-38         0              OK - EXACT         
 9.E-30         9.E-30         9.E-30         0              OK - EXACT         
 9.E-20         9.E-20         9.E-20         0              OK - EXACT         
 9.E-10         9.E-10         9.E-10         0              OK - EXACT         
 9.E-7          9.E-7          9.E-7          1.61941E-7     OK                 
 .00009         .00009         .00009         2.86571E-4     OK                 
 3.45678E-4     3.45678E-4     3.45678E-4     1.54126E-4     OK                 
 9.87654E-4     9.87654E-4     9.87654E-4     9.28058E-5     OK                 
 3.45678E-3     3.45679E-3     3.45679E-3     8.00762E-5     OK                 
 9.87654E-3     9.87686E-3     9.87686E-3     1.10671E-4     OK                 
 1.23456E-2     1.23462E-2     1.23462E-2     3.22076E-4     OK                 
 2.34567E-2     .023456        .023461        33.3114        OK                 
 7.67676E-2     7.69188E-2     7.69188E-2     2.48291E-4     OK                 
 .232323        .236595        .236595        2.36288E-4     OK                 
 .876543        1.20118        1.20118        5.87061E-4     OK                 
 1              1.55741        1.55741        1.18566E-4     OK                 
 1.23456        2.86117        2.86117        1.6459E-5      OK                 
 1.57078        61249.         61249.         5.24726E-10    OK                 
 1.5708        -272242.       -272242.       RANGE SPLIT     OK                 
 1.57081       -73135.7       -73135.7        3.48614E-10    OK                 
 1.61616       -42241.8       -22.0289        8.59392E+6     OK                 
 2             -2.18504       -2.18504        5.19805E-5     OK                 
 2.87654       -.271439       -.271439        2.81063E-5     OK                 
 3.14159       -2.65359E-6    -2.65359E-6     3.36206E-10    OK                 
 4              1.15782        1.15782        8.27025E-5     OK                 
 4.56789        6.87223        6.87223        1.97278E-6     OK                 
 4.71239       -980762.       -980762.       RANGE SPLIT     OK                 
 5.55555       -.890668       -.890668        2.14619E-5     OK                 
 9.87654        .48523         .48523         3.70988E-5     OK                 
 98.7654        5.06921        5.06921        1.73817E-6     OK                 
 987.654        2.53387        2.52646        1.00252        OK                 
 9876.54       -.724992       -.724992        7.58307E-9     OK                 
 98778.9        1.38017        1.38017        2.64032E-9     OK                 
                                                                                
*** INFORMATIVE TEST PASSED ***                                                 
                                                                                
               END TEST                                                         
                                                                                
END PROGRAM 128                                                                 
