PROGRAM FILE 135: SERIAL TEST FOR RANDOMNESS.                                   
    ANSI STANDARD 8.4                                                           
                                                                                
SECTION 135.1: SERIAL TEST FOR RANDOMNESS.                                      
                                                                                
THIS PROGRAM TESTS WHETHER PAIRS OF ADJACENT NUMBERS FROM                       
THE RND FUNCTION ARE EQUALLY DISTRIBUTED AMONG CATEGORIES                       
BASED ON THEIR VALUES. THE TEST ASSIGNS A PAIR TO ONE OF                        
121 CATEGORIES BASED ON WHICH 11TH OF THE SEGMENT FROM 0                        
TO 1 EACH MEMBER OF THE PAIR FALLS WITHIN. CHI-SQUARE IS                        
COMPUTED AND DISPLAYED AS THE RESULT.                                           
                                                                                
***** THIS TEST IS INFORMATIVE ONLY *****                                       
                                                                                
                 BEGIN TEST                                                     
                                                                                
1ST OF PAIR    2ND OF PAIR    ACTUAL COUNT                                      
(EXPECTED COUNT = 20)                                                           
                                                                                
 1              1              23                                               
 1              2              21                                               
 1              3              24                                               
 1              4              17                                               
 1              5              24                                               
 1              6              18                                               
 1              7              18                                               
 1              8              22                                               
 1              9              18                                               
 1              10             18                                               
 1              11             29                                               
 2              1              19                                               
 2              2              19                                               
 2              3              30                                               
 2              4              21                                               
 2              5              22                                               
 2              6              21                                               
 2              7              16                                               
 2              8              20                                               
 2              9              19                                               
 2              10             16                                               
 2              11             20                                               
 3              1              23                                               
 3              2              15                                               
 3              3              26                                               
 3              4              24                                               
 3              5              17                                               
 3              6              16                                               
 3              7              22                                               
 3              8              21                                               
 3              9              14                                               
 3              10             20                                               
 3              11             25                                               
 4              1              19                                               
 4              2              24                                               
 4              3              17                                               
 4              4              20                                               
 4              5              27                                               
 4              6              19                                               
 4              7              18                                               
 4              8              16                                               
 4              9              21                                               
 4              10             19                                               
 4              11             25                                               
 5              1              21                                               
 5              2              20                                               
 5              3              15                                               
 5              4              16                                               
 5              5              29                                               
 5              6              22                                               
 5              7              16                                               
 5              8              24                                               
 5              9              21                                               
 5              10             20                                               
 5              11             14                                               
 6              1              17                                               
 6              2              17                                               
 6              3              21                                               
 6              4              20                                               
 6              5              14                                               
 6              6              17                                               
 6              7              17                                               
 6              8              18                                               
 6              9              21                                               
 6              10             17                                               
 6              11             23                                               
 7              1              17                                               
 7              2              20                                               
 7              3              22                                               
 7              4              22                                               
 7              5              6                                                
 7              6              12                                               
 7              7              21                                               
 7              8              22                                               
 7              9              21                                               
 7              10             21                                               
 7              11             26                                               
 8              1              22                                               
 8              2              23                                               
 8              3              22                                               
 8              4              24                                               
 8              5              18                                               
 8              6              16                                               
 8              7              21                                               
 8              8              19                                               
 8              9              20                                               
 8              10             17                                               
 8              11             29                                               
 9              1              19                                               
 9              2              19                                               
 9              3              24                                               
 9              4              19                                               
 9              5              19                                               
 9              6              20                                               
 9              7              24                                               
 9              8              11                                               
 9              9              20                                               
 9              10             17                                               
 9              11             17                                               
 10             1              28                                               
 10             2              24                                               
 10             3              15                                               
 10             4              21                                               
 10             5              27                                               
 10             6              27                                               
 10             7              20                                               
 10             8              15                                               
 10             9              21                                               
 10             10             18                                               
 10             11             17                                               
 11             1              20                                               
 11             2              9                                                
 11             3              19                                               
 11             4              18                                               
 11             5              20                                               
 11             6              16                                               
 11             7              21                                               
 11             8              23                                               
 11             9              30                                               
 11             10             19                                               
 11             11             19                                               
                                                                                
FOR 120 D.F., SHOULD HAVE 95.70 <= CHI-SQ <= 146.57                             
(5% TAIL AT EACH END).                                                          
                                                                                
ACTUAL CHI-SQ =  99.1                                                           
                                                                                
*** INFORMATIVE TEST PASSED ***                                                 
                                                                                
                  END TEST                                                      
                                                                                
END PROGRAM 135                                                                 
