 HILBERT MATRIX 0F 0RDER  2                                                     
 1              .5                                                              
 .5             .333333                                                         
INVERSE 0F HIL8ERT MATRIX 0F 0RDER  2                                           
 4.            -6.                                                              
-6.             12.                                                             
HILBERT MATRIX TIMES ITS 0WN INVERSE 0RDER  2                                   
 1              0                                                               
 0              1                                                               
 HILBERT MATRIX 0F 0RDER  3                                                     
 1              .5             .333333                                          
 .5             .333333        .25                                              
 .333333        .25            .2                                               
INVERSE 0F HIL8ERT MATRIX 0F 0RDER  3                                           
 9.            -36.            30.                                              
-36.            192.          -180.                                             
 30.           -180.           180.                                             
HILBERT MATRIX TIMES ITS 0WN INVERSE 0RDER  3                                   
 1.            -2.41585E-13    2.27374E-13                                      
 2.93099E-14    1.             1.49214E-13                                      
 2.30926E-14   -1.20792E-13    1.                                               
                                                                                
ERROR in line 20: Out of DATA                                                   
