 4             -5.5                                                             
 .666667        .166667                                                         
-3.66667        3.83333                                                         
                                                                                
ERROR in line 30: Out of DATA                                                   
