100 a$ = "                    abc"
105 print len( a$ )
110 l$ = ltrim$( a$ )
120 print l$
130 print len( l$ )
2100 a$ = "abc              "
2105 print len( a$ )
2110 r$ = rtrim$( a$ )
2120 print r$
2130 print len( r$ )
2200 a$ = ""
2210 print len( a$ )
2220 l$ = ltrim$( a$ )
2230 print l$
2240 print len( l$ )
2400 a$ = ""
2410 print len( a$ )
2420 r$ = rtrim$( a$ )
2430 print r$
2440 print len(r$)
2500 a$ = "          abc             "
2510 print len( a$ )
2520 t$ = trim$( a$ )
2530 print t$
2540 print len( t$ )
2600 a$ = ""
2610 print len( a$ )
2620 t$ = trim$( a$ )
2630 print t$
2640 print len( t$ )
9000 print "*** TEST PASSED ***"
9999 QUIT

