00100 REM ----------------------------------------------------
00110 REM FILENAME:  option2.bas
00120 REM  PURPOSE:  Verify OPTION ARITHMETIC DECIMAL/NATIVE/FIXED
00130 REM   AUTHOR:  Howard Wulf AF5NE
00140 REM     DATE:  October 9th, 2014
00150 REM     NOTE:  These commands are parsed but have no effect
00160 REM ----------------------------------------------------
01000 option arithmetic decimal 
02000 option arithmetic native
03000 option arithmetic fixed
19900 REM ----------------------------------------------------
19910 REM *** ALL TESTS PASSED ***
19920 REM ----------------------------------------------------
19930 PRINT "*** ALL TESTS PASSED ***"
19999 QUIT

