Iteration 0                                                                     
Iteration 1                                                                     
Iteration 2                                                                     
Iteration 3                                                                     
Iteration 4                                                                     
Iteration 5                                                                     
Iteration 6                                                                     
Iteration 7                                                                     
Iteration 8                                                                     
Iteration 9                                                                     
Iteration 10                                                                    
Iteration 11                                                                    
Iteration 12                                                                    
Iteration 13                                                                    
Iteration 14                                                                    
Iteration 15                                                                    
Iteration 16                                                                    
Iteration 17                                                                    
Iteration 18                                                                    
Iteration 19                                                                    
Iteration 20                                                                    
 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20                           
 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40                      
 0 3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60                     
 0 4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80                    
 0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100                  
