THIS PROGRAM WILL GIVE THE VALUE OF A CALL OPTION VIA THE                       
BLACK SCHOLES OPTION VALUATION FORMULA. NECESSARY INPUT                         
CONSISTS OF PRESENT STOCK PRICE, EXERCISE PRICE OF THE                          
OPTION,INTEREST RATE,# OF DAYS TO EXPIRATION OF THE OPTION                      
AND STOCK VOLATILITY. OUTPUT IS THE VALUE OF THE OPTION                         
AND THE HEDGE RATIO.                                                            
                                                                                
PRESS ENTER TO CONTINUE?                                                        
STOCK PRICE,EXERCISE PR.,INT.RATE(%),DAYS TO EXP,VOLATILITY(%)                  
? 12.34,45.67,5,39,7                                                            
                                                                                
ARE OPTIONS PUTS(P) OR CALLS(C)? P                                              
ST.PR.   EX.PR.    INT.RT.   D.T.EXP.     VOL.    VALUE  HEDGE                  
                                                                                
 12.34    45.67      0.05       39        0.07   33.09   1.00                   
                                                                                
PRESS ENTER FOR MORE? -1                                                        
