ALPHABETIZE                                                                     
                                                                                
(TO END PROGRAM ENTER 0)                                                        
NUMBER OF ITEMS? 3                                                              
ITEM 1 ? MNO                                                                    
ITEM 2 ? DEF                                                                    
ITEM 3 ? JKL                                                                    
                                                                                
DEF                                                                             
JKL                                                                             
MNO                                                                             
                                                                                
NUMBER OF ITEMS? 0                                                              
