DISCOUNT COMMERCIAL PAPER                                                       
                                                                                
FUTURE VALUE? 1234                                                              
DISCOUNT RATE? 24                                                               
DAYS TO MATURITY? 350                                                           
DISCOUNT = $ 287.933                                                            
     COST = $ 946.067                                                           
                                                                                
MORE DATA (1=YES, 0=NO)? 0                                                      
