COORDINATE PLOT                                                                 
                                                                                
X-AXIS:  LEFT ENDPOINT, RIGHT ENDPOINT, INCREMENT? 1,40,1                       
Y-AXIS: LOWER ENDPOINT, UPPER ENDPOINT, INCERMENT? 1,20,1                       
NUMBER OF POINTS TO BE PLOTTED? 3                                               
COORDINATES OF POINT  1 ? 5,10                                                  
               POINT  2 ? 20,14                                                 
               POINT  3 ? 30,18                                                 
                                                                                
INTERSECTION OF AXES AT ( 1 , 1 )                                               
                                                                                
********************y                                                           
*                                                                               
*                                                                               
*                                                                               
*       +                                                                       
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*           +                                                                   
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*               +                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
*                                                                               
x                                                                               
