DERIVATIVE                                                                      
                                                                                
(ENTER X=99999 TO END PROGRAM)                                                  
DERIVATIVE AT X=? 12.34                                                         
                    IS 24.9044                                                  
DERIVATIVE AT X=? 56.78                                                         
                    IS 113.331                                                  
DERIVATIVE AT X=? 99999                                                         
