EFFECTIVE INTEREST RATE ON INVESTMENTS                                          
                                                                                
INITAL INVESTMENT? 123456                                                       
TOTAL VALUE AFTER Y YEARS? 234567                                               
NUMBER OF YEARS? 12                                                             
ANNUAL INTEREST RATE = 5.49444               %                                  
                                                                                
MORE DATA? (1=YES, 0=NO)? 0                                                     
