EXPONENTIAL REGRESSION                                                          
                                                                                
NUMBER OF KNOWN POINTS? 3                                                       
X,Y OF POINT 1 ? 1,2                                                            
X,Y OF POINT 2 ? 2,33                                                           
X,Y OF POINT 3 ? 3,55                                                           
                                                                                
A = .55886                                                                      
B = 1.65709                                                                     
                                                                                
COEFFICIENT OF DETERMINATION (R[2) = .862442                                    
COEFFICIENT OF CORRELATION = .928677                                            
STANDARD ERROR OF ESTIMATE = .935923                                            
                                                                                
INTERPOLATION: (ENTER X=0 TO END PROGRAM)                                       
X =? 1.5                                                                        
Y = 6.71123                                                                     
                                                                                
X =? 2.5                                                                        
Y = 35.194                                                                      
                                                                                
X =? 0                                                                          
