FUTURE VALUE OF AN INVESTMENT                                                   
                                                                                
INITIAL INVESTMENT? 12345                                                       
NOMINAL INTEREST RATE? 6.7                                                      
NUMBER OF COMPOUNDING PERIODS PER YEAR? 12                                      
NUMBER OF YEARS? 34                                                             
FUTURE VALUE=$ 119691.                                                          
                                                                                
MORE DATA? (1=YES,0=NO)? 0                                                      
