GREATEST COMMON DENOMINATOR                                                     
                                                                                
(ENTER 0,0 TO END PROGRAM)                                                      
ENTER TWO NUMBERS? 75,125                                                       
G.C.D: 25                                                                       
                                                                                
ENTER TWO NUMBERS? 0,0                                                          
