GEOMETRIC MEAN AND DEVIATION                                                    
                                                                                
(TO END PROGRAM ENTER 0 OBSEVATIONS)                                            
NUMBER OF OBSERVATIONS? 3                                                       
ITEM 1 ? 11                                                                     
ITEM 2 ? 23                                                                     
ITEM 3 ? 84                                                                     
GEOMETRIC MEAN = 27.6992                                                        
GEOMETRIC DEVIATION = 2.79864                                                   
                                                                                
NUMBER OF OBSERVATIONS? 0                                                       
