AVERAGE GROWTH RATE, FUTURE PROJECTIONS                                         
                                                                                
NUMBER OF YEARS FIGURES ESTABLISHED? 3                                          
FIGURE: YEAR 1 ? 12                                                             
        yEAR 2 ? 345                                                            
        yEAR 3 ? 6789                                                           
AVERAGE GROWTH RAT = 2278.55 %                                                  
                                                                                
(ENTER 0 TO END PROGRAM)                                                        
PROJECTED SALES FOR YEAR? 1.5                                                   
                            = 62.34                                             
PROJECTED SALES FOR YEAR? 2.5                                                   
                            = 1482.83                                           
PROJECTED SALES FOR YEAR? 0                                                     
