INITAL INVESTMENT                                                               
                                                                                
TOTAL VALUE AFTER Y YEARS? 123456                                               
NUMBER OF COMPOUNDING PERIODS PER YEAR? 12                                      
NUMBER OF YEARS? 7                                                              
NOMINAL INTEREST RATE? 5                                                        
INITIAL = $ 87061.3                                                             
                                                                                
MORE DATA? (1=YES,0=NO)? 0                                                      
