INTEGRATION: SIMPSON'S RULE                                                     
                                                                                
SELECTION: 1=KNOWN FORMULA, O=UNKNOWN FORMULA? 1                                
LOWER, UPPER LIMIT OF INTEGRATION? 1,10                                         
INCREMENT OF X? 0.5                                                             
INTEGRAL IS 49.3333                                                             
