INTEGRATION: GAUSSIAN QUADRATURE                                                
                                                                                
INTEGRATION LIMITS (lower,UPPER)? 1,10                                          
NUMBER OF INTERVALS? 25                                                         
INTEGRAL = 2499.75                                                              
                                                                                
CHANGE DATA AND RECOMPUTE?                                                      
(0=NO, 1=NEW INTEGRATION LIMITS, 2=NEW NO OF INTERVALS)? 0                      
