LAST PAYMENT ON A LOAN                                                          
                                                                                
REGULAR PAYMENT? 1234                                                           
PRINCIPAL? 456789                                                               
TERM IN YEARS? 30                                                               
ANNUAL INTEREST RATE? 3.5                                                       
NUMBER OF PAYMENTS PER YEAR? 12                                                 
LAST PAYMENT = $ 520485.                                                        
                                                                                
MORE DATA? (1=YES,0=NO)? 0                                                      
