LINEAR REGRESSION                                                               
                                                                                
NUMBER OF KNOWN POINTS? 3                                                       
X,Y OF POINT 1 ? 1,2                                                            
X,Y OF POINT 2 ? 3,4                                                            
X,Y OF POINT 3 ? 5,8                                                            
                                                                                
F(X) = .166667 + ( 1.5 * x )                                                    
                                                                                
COEFFICIENT OF DETERMINATION (R[2) = .964286                                    
COEFFICIENT OF CORRELATION = .981981                                            
STANDARD ERROR OF ESTIMATE = .816497                                            
                                                                                
INTERPOLATION:  (ENTER X=0 TO END PROGRAM)                                      
X =? 2                                                                          
Y = 3.16667                                                                     
                                                                                
X =? 4                                                                          
Y = 6.16667                                                                     
                                                                                
X =? 0                                                                          
