REMAINING BALANCE ON A LOAN                                                     
                                                                                
REGULAR PAYMENT? 1234                                                           
PRINCIPAL? 56789                                                                
NUMBER OF PAYMENTS PER YEAR? 12                                                 
ANNUAL INTEREST RATE? 3.25                                                      
LAST PAYMENT MADE (PAYMENT NO. ,YEAR, I.E. 10,4)? 12,30                         
REMAINING BALANCE = $-600373.                                                   
                                                                                
MORE DATA? (1=YES,0=NO)? 0                                                      
