MATRIX INVERSION                                                                
                                                                                
DIMENSION OF MATRIX? 2                                                          
MATRIX ELEMENTS:                                                                
ROW 1                                                                           
VALUE COLUMN 1 ? 1                                                              
VALUE COLUMN 2 ? 2                                                              
ROW 2                                                                           
VALUE COLUMN 1 ? 3                                                              
VALUE COLUMN 2 ? 4                                                              
                                                                                
-2   1                                                                          
 1.5  -.5                                                                       
