MATRIX MULTIPLICATION                                                           
                                                                                
DIMENSION OF MATRIX 1 (R,C)? 2,2                                                
DIMENSION OF MATRIX 2 (R,C)? 2,2                                                
MATRIX 1:                                                                       
ROW 1                                                                           
VALUE COLUMN 1 ? 11                                                             
VALUE COLUMN 2 ? 12                                                             
ROW 2                                                                           
VALUE COLUMN 1 ? 21                                                             
VALUE COLUMN 2 ? 22                                                             
                                                                                
MATRIX 2:                                                                       
ROW 1                                                                           
VALUE COLUMN 1 ? 34                                                             
VALUE COLUMN 2 ? 35                                                             
ROW 2                                                                           
VALUE COLUMN 1 ? 43                                                             
VALUE COLUMN 2 ? 53                                                             
                                                                                
 890    1021                                                                    
 1660    1901                                                                   
