NORMAL DISTRIBUTION                                                             
                                                                                
(0=STANDARD, 1=NON-STANDARD)                                                    
WHICH TYPE OF VARIABLE? 0                                                       
                                                                                
(TO END PROGRAM ENTER X=99999)                                                  
X =? 123                                                                        
FREQUENCY = 0                                                                   
PROBABILITY = .5                                                                
                                                                                
X =? 165                                                                        
FREQUENCY = 0                                                                   
PROBABILITY = .5                                                                
                                                                                
X =? 147                                                                        
FREQUENCY = 0                                                                   
PROBABILITY = .5                                                                
                                                                                
X =? 101                                                                        
FREQUENCY = 0                                                                   
PROBABILITY = .5                                                                
                                                                                
X =? 107                                                                        
FREQUENCY = 0                                                                   
PROBABILITY = .5                                                                
                                                                                
X =? 131                                                                        
FREQUENCY = 0                                                                   
PROBABILITY = .5                                                                
                                                                                
X =? 99999                                                                      
