PRIME FACTORS OF INTEGERS                                                       
                                                                                
(ENTER 0 TO END PROGRAM)                                                        
NUMBER? 121                                                                     
 1                                                                              
 11 [ 2                                                                         
                                                                                
NUMBER? 333                                                                     
 1                                                                              
 3 [ 2                                                                          
 37 [ 1                                                                         
                                                                                
NUMBER? 777                                                                     
 1                                                                              
 3 [ 1                                                                          
 7 [ 1                                                                          
 37 [ 1                                                                         
                                                                                
NUMBER? 0                                                                       
