PRINCIPAL ON A LOAN                                                             
                                                                                
REGULAR PAYMENT? 1234                                                           
TERM IN YEARS? 30                                                               
ANNUAL INTEREST RATE? 5                                                         
NUMBER OF PAYMENTS PER YEAR? 12                                                 
PRINCIPAL = $ 229872.                                                           
                                                                                
MORE DATA? (1=YES, 0=NO)? 0                                                     
