ROOTS OF QUADRATIC EQUATIONS                                                    
                                                                                
COEFFICIENTS A,B,C? 3,4,5                                                       
ROOTS (COMPLEX): -.666667  + OR - 1.10554  I                                    
                                                                                
MORE DATA (1=YES, 0=NO)? 0                                                      
