ROOTS OF POLYNOMIALS: HALF-INTERVAL SEARCH                                      
                                                                                
(TO END SEARCH ENTER 0,0)                                                       
INTERVAL (LOWER, UPPER LIMIT)? 1,10                                             
NO CHANGE OF SIGN FOUND                                                         
INTERVAL (LOWER, UPPER LIMIT)? -1,1                                             
ROOT = .303574                                                                  
                                                                                
INTERVAL (LOWER, UPPER LIMIT)? 0,0                                              
