REAL ROOTS OF POLYNOMIALS: NEWTON                                               
                                                                                
DEGREE OF EQUATION? 2                                                           
COEFFICIENT A( 0 )? 5                                                           
COEFFICIENT A( 1 )? 8                                                           
COEFFICIENT A( 2 )? 9                                                           
                                                                                
guess? 10                                                                       
100 ITERATIONS COMPLETED:                                                       
  X = .17034  F(x) = 3.75415                                                    
   CONTINUE (1= YES, 0=NO)? 0                                                   
ANOTHER VALUE (1=YES, 0=NO)? 0                                                  
ANOTHER FUNCTION (1=YES, 0=NO)? 0                                               
