   *** SHELL METZNER SORT ***                                                   
                                                                                
BY ALLAN D. EMERT                                                               
RT #4, BOX 1455, ODESSA, TX 79763                                               
                                                                                
TO END PROGRAM ENTER ///                                                        
ITEM  1 ? XYZ                                                                   
ITEM  2 ? ABC                                                                   
ITEM  3 ? MNO                                                                   
ITEM  4 ? JKL                                                                   
ITEM  5 ? TUV                                                                   
ITEM  6 ? ///                                                                   
                                                                                
ABC                                                                             
JKL                                                                             
MNO                                                                             
TUV                                                                             
XYZ                                                                             
