                                                                                
                                                                                
   **** SHOPPING LIST ****                                                      
      BY  J. A. KRAYNAK                                                         
                                                                                
                                                                                
                                                                                
DO YOU NEED INSTRUCTIONS (Y/N)? Y                                               
                                                                                
                                                                                
    FIVE LISTS OF GROCERIES WILL APPEAR ON THE SCREEN, ONE                      
AT A TIME OF COURSE,  WITH A BLINKING CURSOR ( ) NEXT TO THE                    
FIRST ITEM ON THE LIST.  IF YOU DESIRE THAT ITEM TO BE ON YOUR                  
PRINTED SHOPPING LIST - PRESS THE 'Y' KEY.  IF NOT - PRESS THE                  
'N' KEY & THE CURSOR WILL MOVE ON TO THE NEXT ITEM.                             
                                                                                
    AN '*' WILL APPEAR TO THE LEFT OF THE ITEMS SELECTED.  TO                   
MOVE TO THE NEXT 'PAGE' PRESS THE '@' KEY.  YOU CANNOT GO                       
BACKWARDS...IF YOU FORGET AN ITEM - DON'T FRET - AFTER                          
RUNNING THE ENTIRE LIST YOU WILL BE ABLE TO ADD ITEMS NOT                       
LISTED OR FORGOTTEN; BEFORE THE PRINT-OUT OCCURS.                               
                * PRESS SPACE BAR TO CONTINUE *#? @                             
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
    **** LOADING DATA ****                                                      
CANTALOUPESMUSHROOMSAPPLESCELERYCARROTSPEARSLETTUCE                             
CUCUMBERSTOMATOESMARZETTI DRESSINGGREEN PEPPERS                                 
BANANASPOTATOESCORNCABBAGEONIONSGRAPEFRUITGRAPES                                
ORANGE JUICEDRY YEASTEGGSBUTTER                                                 
MARGERINEMILKCHEESE(SLICES)CHEESE(PIZZA)                                        
MAYONNAISESALAD DRESSINGPICKLES(DILL)PICKLES(SLICES)MUSTARDKETCHUPPEANUT BUTTERJ
DINNER ROLLSFRENCH BREADITALIAN BREADPIECAKEDONUTSPOTATOE SALADMACARONI SALAD:::
 KIELBASALUNCHEON MEATBALOGNA                                                   
KIELBASA LOAFPIZZA LOAFSALAMIPEPSI                                              
DIET PEPSI7-UPGINGERALEDR PEPPER                                                
R C COLAPOPROOTBEERPEANUTSWALNUTSPLAIN CHIPSRIPPLED CHIPSPRETZELSPOPCORNCORN CHI
CARROTSGREEN BEANSCORNCHILI BEANSPORK & BEANSINSTANT COFFEEREGULAR COFFEETEA BAG
TOMATO PASTETOMATOES(WHOLE)FRUIT COCKTAILPINEAPPLES                             
TOMATO JUICEDOG FOODCAT FOODBONZ:::::::::::::PRESS '@' KEY FOR NEXT PAGE::::::::
 DOG YUMMIESFLEA POWDERFROSTED FLAKESCHEERIOSCORN FLAKESSHREADED WHEATBEEF NOODL
TOMATO RICE SOUPCHICKEN SOUPTOMATO SOUPVEGTABLE SOUP                            
TUNA FISHSALMONRICE-A-RONIRICESPAGETTI SAUCEPIZZA SAUCESPAGETTI NOODLES         
ELBO MACARONIEGG NOODLESRIGATONICOOKIES                                         
SALTEEN CRACKERSRITZ CRACKERSSOAP(FACE)SOAP(SHOWER)                             
MR BUBBLECLEANSERCHEERWINDEXVANISHSOFT SCRUBMR CLEAN                            
AIR FRESHNERSSHOUTBLEACHIVORY LIQUIDBOUNCEAMMONIASTARCHTOP JOB                  
CAKE MIXESFLOURCRISCOVEGTABLE OIL:::::::::::::PRESS '@' KEY FOR NEXT PAGE:::::::
 LOG CABIN SYRUPPANCAKE MIXSPICESSALTPEPPERSUGARAU JUS GRAVY                    
MEAT LOAF MIXSTROGANOFF MIXMEAT TENDERIZERCANDY                                 
MARSHMELLOWSJELLOCARNATION MILKFREEZER WRAPNAPKINSGLAD WRAPALUMINUM FOILTRASH BA
TOILET PAPERPAPER TOWELSCAKEBREAD                                               
HAMBURG BUNSHOT DOG BUNSDINNER ROLLSBREAD CRUMBSCROUTONSSTUFFING MIXSHAKE & BAKE
PIEROGIESPIZZASTEAK-UMMSCHOPPED ONION:::::::::::::PRESS '@' KEY FOR NEXT PAGE:::
 ICE CREAMPOP SICKLESICE CREAM TOPPINGSCOOL WHIPFROZEN CHICKENROAST BEEF DINNERF
FROZEN STRAWBRYFROZEN MIXED FRUITHOT DOGSBACON                                  
SAUSAGEFISHCHICKENTURKEYPEPPER STEAKSSTEAKROAST                                 
CHOPPED SERLOINHOT SAUSAGEHAMBURGERGROUND CHUCKHAMPORK CHOPSSPARE RIBSCIGARETTES
PIPE TOBACCOPIPE FILTERST V GUIDE................:::::::::::::PRESS '@' KEY FOR 
                                                                                
YOU MAY NOW ADD UP TO 20 ITEMS OF YOUR CHOICE THAT WERE NOT ON  THE LIST.  AFTER
 EACH ITEM IS TYPED, PRESS <ENTER>.  WHEN FIN-  ISHED...TYPE 'END' FOLLOWED BY P
RESSING <ENTER>.                                                                
                                                                                
ITEM # 1   ? Y                                                                  
ITEM # 2   ? Y                                                                  
ITEM # 3   ? Y                                                                  
ITEM # 4   ? Y                                                                  
ITEM # 5   ? Y                                                                  
ITEM # 6   ? N                                                                  
ITEM # 7   ? N                                                                  
ITEM # 8   ? N                                                                  
ITEM # 9   ? N                                                                  
ITEM # 10   ? N                                                                 
ITEM # 11   ? Y                                                                 
ITEM # 12   ? Y                                                                 
ITEM # 13   ? N                                                                 
ITEM # 14   ? N                                                                 
ITEM # 15   ? N                                                                 
ITEM # 16   ? Y                                                                 
ITEM # 17   ? N                                                                 
ITEM # 18   ? Y                                                                 
ITEM # 19   ? N                                                                 
ITEM # 20   ? Y                                                                 
READY PRINTER                                                                   
HIT ENTER WHEN READY                                                            
? @                                                                             
