ENTER THE NUMBER 1, 2, OR 3? 1                                                  
THE GOSUB-0F STATEMENT BRANCHED TO SUBROUTINE #1                                
ENTER THE NUMBER 1, 2, OR 3? 2                                                  
THE GOSUB-0F STATEMENT BRANCHED TO SUBROUTINE #2                                
ENTER THE NUMBER 1, 2, OR 3? 3                                                  
THE GOSUB-0F STATEMENT BRANCHED TO SUBROUTINE #3                                
ENTER THE NUMBER 1, 2, OR 3? -1                                                 
