 1  0  0  0                                                                     
 0  1  0  0                                                                     
 0  0  1  0                                                                     
 0  0  0  1                                                                     
'MAT IDN' PASSED THE TEST IF A 4X4 IDENTITY                                     
MATRIX WAS PRINTED.                                                             
