HELLO THERE.                                                                    
bwBASIC: LIST                                                                   
   10 REM 'NEW X' COMMAND TEST PROGRAM                                          
   20 PRINT "HELLO THERE."                                                      
   99 END                                                                       
                                                                                
bwBASIC: NEW 777                                                                
bwBASIC: LIST                                                                   
                                                                                
