abc(6000)                                                                       
ERL= 210 ERR= 6                                                                 
 0                                                                              
abc(60000)                                                                      
ERL= 260 ERR= 5                                                                 
