COMMA                                                                           
 1              0                                                               
 0              1                                                               
ASTERISK                                                                        
 1              0                                                               
 0              1                                                               
BAR                                                                             
 1              0                                                               
 0              1                                                               
TEST PASSED                                                                     
