LBOUND= 1      UBOUND= 10                                                       
LBOUND= 1      UBOUND= 5                                                        
LBOUND= 1      UBOUND= 9                                                        
LBOUND= 2      UBOUND= 7                                                        
LBOUND= 21     UBOUND= 30                                                       
