CHI-SQUARE DISTRIBUTION                                                         
                                                                                
(TO END PROGRAM ENTER 0)                                                        
DEGREES OF FREEDOM? 2                                                           
CHI-SQUARE? .987                                                                
TAIL END VALUE = .610486                                                        
                                                                                
DEGREES OF FREEDOM? 0                                                           
