CHI-SQUARE TEST                                                                 
                                                                                
NUMBER OF ROWS? 2                                                               
NUMBER OF COLUMNS? 3                                                            
CONTINGENCY TABLE:                                                              
ROW 1                                                                           
   ELEMENT 1 ? 1                                                                
   ELEMENT 2 ? 2                                                                
   ELEMENT 3 ? 3                                                                
ROW 2                                                                           
   ELEMENT 1 ? 4                                                                
   ELEMENT 2 ? 5                                                                
   ELEMENT 3 ? 6                                                                
                                                                                
OBSERVED VALUE EXPECTED VAULE CHI[2 CONTRIBUTION                                
   COLUMN 1                                                                     
     1          1.42857        .128571                                          
     4          3.57143        5.14286E-2                                       
   COLUMN 2                                                                     
     2          2              0                                                
     5          5              0                                                
   COLUMN 3                                                                     
     3          2.57143        7.14286E-2                                       
     6          6.42857        2.85714E-2                                       
                                                                                
CHI-SQUARE = .28                                                                
DEGREES OF FREEDOM = 2                                                          
