ANNUAL INTEREST RATE ON A LOAN                                                  
                                                                                
REGULAR PAYMENT? 2345                                                           
TERM IN YEARS? 30                                                               
PRINCIPAL? 456789                                                               
NUMBER OF PAYMENTS PER YEAR? 12                                                 
ANNUAL INTEREST RATE = 4.612 %                                                  
                                                                                
MORE DATA? (1=YES, 0=NO)? 0                                                     
