 1              2              3                                                
 4              5              6                                                
 7              8              9                                                
MATRIX A 0F 0RDER  3                                                            
 1 2 3                                                                          
 4 5 6                                                                          
 7 8 9                                                                          
MATRIX B 0F 0RDER  3                                                            
 9 8 7                                                                          
 6 5 4                                                                          
 3 2 1                                                                          
      C=A+B                                                                     
 10 10 10                                                                       
 10 10 10                                                                       
 10 10 10                                                                       
 H                                                                              
 360                                                                            
