 A              B              C             GCD                                
 60             90             120            30                                
 38465          64872          98765          1                                 
 32             384            72             8                                 
                                                                                
ERROR in line 20: Out of DATA                                                   
