X VALUE        SINE           RESOLUTION                                        
 1.6            .999574        .1                                               
 1.57           1.             .01                                              
 1.571          1.             .001                                             
                                                                                
ERROR in line 10: Out of DATA                                                   
