  10 FOR L = 1 TO 20
  20   PRINT RND(X),
  30 NEXT L
  40 END
9900 REM ------------------------------------------------------------------------
9910 REM Purpose: RNDTES example 
9920 REM  Author: General Electric
9930 REM    Date: 1965-12-20
9940 REM    Note: OPTION VERSION MARK-I
9950 REM  Origin: 202026A_BASIC_Language_Reference_Manual_Jan1967.pdf
9960 REM    Page: 26
9970 REM ------------------------------------------------------------------------
