                                                                                
ERROR in line 20: Subscript out of range                                        
                                                                                
STACK TRACE:                                                                    
20:print n(7)                                                                   
