This is a first sequence of three RND numbers:                                  
 .10793                                                                         
 .109362                                                                        
 .531097                                                                        
This is a second sequence of three RND numbers:                                 
 .782371                                                                        
 .79199                                                                         
 .823117                                                                        
The second sequence should have been differrent                                 
from the first.                                                                 
