SnglFunc.BAS -- Test Single-Line User-defined Function Statement                
                                                                                
                                                                                
The sum of 6 and 4 is  10                                                       
Did it work properly?                                                           
