? PTP.OUT LINE 1                                                                
PTP.OUT LINE 1                                                                  
? PTP.OUT LINE 2                                                                
PTP.OUT LINE 2                                                                  
? PTP.OUT LINE 3                                                                
PTP.OUT LINE 3                                                                  
