? LPT.OUT  LINE 1                                                               
LPT.OUT  LINE 1                                                                 
? LPT.OUT  LINE 2                                                               
LPT.OUT  LINE 2                                                                 
? LPT.OUT  LINE 3                                                               
LPT.OUT  LINE 3                                                                 
