FRONT INDEXES? 1,2,3                                                            
REAR INDEXES ? 4,5,6                                                            
FOCAL LENGTH ? 7                                                                
                                                                                
R1 = -4.27217                                                                   
R2 = -5.36326                                                                   
R3 =  17.2997                                                                   
R4 =  98.1781                                                                   
