                                                                                
TOTAL MAGNITUDE? 8                                                              
                                                                                
TYPE OF AREA:                                                                   
  (C) CIRCULAR                                                                  
  (E) ELLIPTICAL                                                                
  (R) RECTANGULAR                                                               
  (I) IRREGULAR                                                                 
CHOICE? C                                                                       
                                                                                
DIAM IN ARC MIN? 46                                                             
                                                                                
SURFACE MAGNITUDE --                                                            
  PER SQ ARC MIN:  16.0515                                                      
  PER SQ ARC SEC:  24.9423                                                      
                                                                                
TOTAL MAGNITUDE? X                                                              
