The absolute value of -1.23457  is 1.23457                                      
*** TEST #1 PASSED ***                                                          
The absolute value of  1.23457  is 1.23457                                      
*** TEST #2 PASSED ***                                                          
*** ALL TESTS PASSED ***                                                        
