The cosine value of  0  is 1                                                    
*** TEST #1 PASSED ***                                                          
The cosine value of  .5  is .877583                                             
*** TEST #2 PASSED ***                                                          
The cosine value of -.5  is .877583                                             
*** TEST #3 PASSED ***                                                          
The cosine value of  1  is .540302                                              
*** TEST #4 PASSED ***                                                          
The cosine value of -1  is .540302                                              
*** TEST #5 PASSED ***                                                          
*** ALL TESTS PASSED ***                                                        
