The hyperbolic cosine value of  0  is 1                                         
*** TEST #1 PASSED ***                                                          
The hyperbolic cosine value of  .5  is 1.12763                                  
*** TEST #2 PASSED ***                                                          
The hyperbolic cosine value of -.5  is 1.12763                                  
*** TEST #3 PASSED ***                                                          
The hyperbolic cosine value of  1  is 1.54308                                   
*** TEST #4 PASSED ***                                                          
The hyperbolic cosine value of -1  is 1.54308                                   
*** TEST #5 PASSED ***                                                          
*** ALL TESTS PASSED ***                                                        
