The cotangent value of  .0001  is 10000.                                        
*** TEST #1 PASSED ***                                                          
The cotangent value of  .5  is 1.83049                                          
*** TEST #2 PASSED ***                                                          
The cotangent value of -.5  is-1.83049                                          
*** TEST #3 PASSED ***                                                          
The cotangent value of  1  is .642093                                           
*** TEST #4 PASSED ***                                                          
The cotangent value of -1  is-.642093                                           
*** TEST #5 PASSED ***                                                          
*** ALL TESTS PASSED ***                                                        
