The cosecant value of  .0001  is 10000.                                         
*** TEST #1 PASSED ***                                                          
The cosecant value of  .5  is 2.08583                                           
*** TEST #2 PASSED ***                                                          
The cosecant value of -.5  is-2.08583                                           
*** TEST #3 PASSED ***                                                          
The cosecant value of  1  is 1.1884                                             
*** TEST #4 PASSED ***                                                          
The cosecant value of -1  is-1.1884                                             
*** TEST #5 PASSED ***                                                          
*** ALL TESTS PASSED ***                                                        
