TESTCASE # 1   E= 0           R= 0           X= 0                               
               F= 0           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 2   E= 0           R= .785398     X= 1                               
               F= 0           N= .785398                                        
*** TEST PASSED ***                                                             
TESTCASE # 3   E= 0           R=-.785398     X=-1                               
               F= 0           N=-.785398                                        
*** TEST PASSED ***                                                             
TESTCASE # 4   E= 0           R= .380506     X= .4                              
               F= 0           N= .380506                                        
*** TEST PASSED ***                                                             
TESTCASE # 5   E= 0           R=-.380506     X=-.4                              
               F= 0           N=-.380506                                        
*** TEST PASSED ***                                                             
TESTCASE # 6   E= 0           R= .54042      X= .6                              
               F= 0           N= .54042                                         
*** TEST PASSED ***                                                             
TESTCASE # 7   E= 0           R=-.54042      X=-.6                              
               F= 0           N=-.54042                                         
*** TEST PASSED ***                                                             
TESTCASE # 8   E= 0           R= 1.56686     X= 254                             
               F= 0           N= 1.56686                                        
*** TEST PASSED ***                                                             
TESTCASE # 9   E= 0           R= 1.56687     X= 255                             
               F= 0           N= 1.56687                                        
*** TEST PASSED ***                                                             
TESTCASE # 10  E= 0           R= 1.56689     X= 256                             
               F= 0           N= 1.56689                                        
*** TEST PASSED ***                                                             
TESTCASE # 11  E= 0           R= 1.57077     X= 32000                           
               F= 0           N= 1.57077                                        
*** TEST PASSED ***                                                             
TESTCASE # 12  E= 0           R=-.223435     X=-.227229                         
               F= 0           N=-.223435                                        
*** TEST PASSED ***                                                             
TESTCASE # 13  E= 0           R=-.234748     X=-.239157                         
               F= 0           N=-.234748                                        
*** TEST PASSED ***                                                             
TESTCASE # 14  E= 0           R=-.210424     X=-.213586                         
               F= 0           N=-.210424                                        
*** TEST PASSED ***                                                             
TESTCASE # 15  E= 0           R= .268064     X= .274675                         
               F= 0           N= .268064                                        
*** TEST PASSED ***                                                             
TESTCASE # 16  E= 0           R= .168163     X= .169766                         
               F= 0           N= .168163                                        
*** TEST PASSED ***                                                             
TESTCASE # 17  E= 0           R= .308583     X= .318766                         
               F= 0           N= .308583                                        
*** TEST PASSED ***                                                             
TESTCASE # 18  E= 0           R= 2.06629E-2  X= 2.06658E-2                      
               F= 0           N= 2.06629E-2                                     
*** TEST PASSED ***                                                             
TESTCASE # 19  E= 0           R= .186079     X= .188257                         
               F= 0           N= .186079                                        
*** TEST PASSED ***                                                             
TESTCASE # 20  E= 0           R=-.270723     X=-.277537                         
               F= 0           N=-.270723                                        
*** TEST PASSED ***                                                             
TESTCASE # 21  E= 0           R=-.448578     X=-.481303                         
               F= 0           N=-.448578                                        
*** TEST PASSED ***                                                             
TESTCASE # 22  E= 0           R= .410781     X= .43556                          
               F= 0           N= .410781                                        
*** TEST PASSED ***                                                             
TESTCASE # 23  E= 0           R=-.207922     X=-.210971                         
               F= 0           N=-.207922                                        
*** TEST PASSED ***                                                             
TESTCASE # 24  E= 0           R=-.427183     X=-.455216                         
               F= 0           N=-.427183                                        
*** TEST PASSED ***                                                             
TESTCASE # 25  E= 0           R=-1.56178     X=-110.907                         
               F= 0           N=-1.56178                                        
*** TEST PASSED ***                                                             
TESTCASE # 26  E= 0           R= 1.56133     X= 105.632                         
               F= 0           N= 1.56133                                        
*** TEST PASSED ***                                                             
TESTCASE # 27  E= 0           R=-1.56205     X=-114.341                         
               F= 0           N=-1.56205                                        
*** TEST PASSED ***                                                             
TESTCASE # 28  E= 0           R= 1.56168     X= 109.706                         
               F= 0           N= 1.56168                                        
*** TEST PASSED ***                                                             
TESTCASE # 29  E= 0           R= 1.56164     X= 109.198                         
               F= 0           N= 1.56164                                        
*** TEST PASSED ***                                                             
TESTCASE # 30  E= 0           R= 1.55915     X= 85.8773                         
               F= 0           N= 1.55915                                        
*** TEST PASSED ***                                                             
TESTCASE # 31  E= 0           R=-1.55366     X=-58.3548                         
               F= 0           N=-1.55366                                        
*** TEST PASSED ***                                                             
TESTCASE # 32  E= 0           R= 1.53707     X= 29.6397                         
               F= 0           N= 1.53707                                        
*** TEST PASSED ***                                                             
TESTCASE # 33  E= 0           R=-1.56157     X=-108.36                          
               F= 0           N=-1.56157                                        
*** TEST PASSED ***                                                             
TESTCASE # 34  E= 0           R=-1.5493      X=-46.5199                         
               F= 0           N=-1.5493                                         
*** TEST PASSED ***                                                             
TESTCASE # 35  E= 0           R= 1.56191     X= 112.521                         
               F= 0           N= 1.56191                                        
*** TEST PASSED ***                                                             
TESTCASE # 36  E= 0           R= 1.54878     X= 45.4151                         
               F= 0           N= 1.54878                                        
*** TEST PASSED ***                                                             
TESTCASE # 37  E= 0           R= 1.56091     X= 101.129                         
               F= 0           N= 1.56091                                        
*** TEST PASSED ***                                                             
TESTCASE # 38  E= 0           R= 1.55542     X= 65.0473                         
               F= 0           N= 1.55542                                        
*** TEST PASSED ***                                                             
TESTCASE # 39  E= 0           R= 1.55014     X= 48.4012                         
               F= 0           N= 1.55014                                        
*** TEST PASSED ***                                                             
TESTCASE # 40  E= 0           R= 1.56262     X= 122.294                         
               F= 0           N= 1.56262                                        
*** TEST PASSED ***                                                             
TESTCASE # 41  E= 0           R=-1.55298     X=-56.1094                         
               F= 0           N=-1.55298                                        
*** TEST PASSED ***                                                             
TESTCASE # 42  E= 0           R=-1.56254     X=-121.087                         
               F= 0           N=-1.56254                                        
*** TEST PASSED ***                                                             
TESTCASE # 43  E= 0           R=-1.5627      X=-123.517                         
               F= 0           N=-1.5627                                         
*** TEST PASSED ***                                                             
TESTCASE # 44  E= 0           R=-1.56055     X=-97.6301                         
               F= 0           N=-1.56055                                        
*** TEST PASSED ***                                                             
TESTCASE # 45  E= 0           R=-1.55517     X=-64.0001                         
               F= 0           N=-1.55517                                        
*** TEST PASSED ***                                                             
TESTCASE # 46  E= 0           R=-1.53189     X=-25.6888                         
               F= 0           N=-1.53189                                        
*** TEST PASSED ***                                                             
TESTCASE # 47  E= 0           R= 1.50333     X= 14.8006                         
               F= 0           N= 1.50333                                        
*** TEST PASSED ***                                                             
TESTCASE # 48  E= 0           R=-1.55443     X=-61.0877                         
               F= 0           N=-1.55443                                        
*** TEST PASSED ***                                                             
TESTCASE # 49  E= 0           R=-1.55579     X=-66.6381                         
               F= 0           N=-1.55579                                        
*** TEST PASSED ***                                                             
TESTCASE # 50  E= 0           R=-1.57061     X=-5476.5                          
               F= 0           N=-1.57061                                        
*** TEST PASSED ***                                                             
TESTCASE # 51  E= 0           R=-1.57075     X=-21210.3                         
               F= 0           N=-1.57075                                        
*** TEST PASSED ***                                                             
TESTCASE # 52  E= 0           R=-1.57076     X=-28757.2                         
               F= 0           N=-1.57076                                        
*** TEST PASSED ***                                                             
TESTCASE # 53  E= 0           R=-1.57076     X=-28732.2                         
               F= 0           N=-1.57076                                        
*** TEST PASSED ***                                                             
TESTCASE # 54  E= 0           R= 1.57072     X= 12730.3                         
               F= 0           N= 1.57072                                        
*** TEST PASSED ***                                                             
TESTCASE # 55  E= 0           R=-1.57025     X=-1830.69                         
               F= 0           N=-1.57025                                        
*** TEST PASSED ***                                                             
TESTCASE # 56  E= 0           R= 1.57061     X= 5486.39                         
               F= 0           N= 1.57061                                        
*** TEST PASSED ***                                                             
TESTCASE # 57  E= 0           R= 1.57075     X= 22405.9                         
               F= 0           N= 1.57075                                        
*** TEST PASSED ***                                                             
TESTCASE # 58  E= 0           R= 1.57076     X= 30809.8                         
               F= 0           N= 1.57076                                        
*** TEST PASSED ***                                                             
TESTCASE # 59  E= 0           R=-1.57076     X=-28930.6                         
               F= 0           N=-1.57076                                        
*** TEST PASSED ***                                                             
TESTCASE # 60  E= 0           R=-1.57063     X=-6014.53                         
               F= 0           N=-1.57063                                        
*** TEST PASSED ***                                                             
TESTCASE # 61  E= 0           R= 1.57074     X= 17414.6                         
               F= 0           N= 1.57074                                        
*** TEST PASSED ***                                                             
TESTCASE # 62  E= 0           R=-1.5707      X=-10538.3                         
               F= 0           N=-1.5707                                         
*** TEST PASSED ***                                                             
TESTCASE # 63  E= 0           R=-1.57074     X=-17536.3                         
               F= 0           N=-1.57074                                        
*** TEST PASSED ***                                                             
TESTCASE # 64  E= 0           R=-1.57068     X=-8856.62                         
               F= 0           N=-1.57068                                        
*** TEST PASSED ***                                                             
TESTCASE # 65  E= 0           R=-1.5706      X=-5140.12                         
               F= 0           N=-1.5706                                         
*** TEST PASSED ***                                                             
TESTCASE # 66  E= 0           R=-1.57068     X=-8595.31                         
               F= 0           N=-1.57068                                        
*** TEST PASSED ***                                                             
TESTCASE # 67  E= 0           R=-1.5705      X=-3382.87                         
               F= 0           N=-1.5705                                         
*** TEST PASSED ***                                                             
TESTCASE # 68  E= 0           R=-1.5706      X=-5002.07                         
               F= 0           N=-1.5706                                         
*** TEST PASSED ***                                                             
TESTCASE # 69  E= 0           R=-1.57062     X=-5800.72                         
               F= 0           N=-1.57062                                        
*** TEST PASSED ***                                                             
TESTCASE # 70  E= 0           R= 1.57076     X= 29686.4                         
               F= 0           N= 1.57076                                        
*** TEST PASSED ***                                                             
TESTCASE # 71  E= 0           R= 1.57041     X= 2571                            
               F= 0           N= 1.57041                                        
*** TEST PASSED ***                                                             
TESTCASE # 72  E= 0           R= 1.57076     X= 31091                           
               F= 0           N= 1.57076                                        
*** TEST PASSED ***                                                             
TESTCASE # 73  E= 0           R= 1.57073     X= 14819                           
               F= 0           N= 1.57073                                        
*** TEST PASSED ***                                                             
TESTCASE # 74  E= 0           R= 1.57053     X= 3790.9                          
               F= 0           N= 1.57053                                        
*** TEST PASSED ***                                                             
TESTCASE # 75  E= 0           R=-1.5708      X=-4.2981E+9                       
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 76  E= 0           R=-1.5708      X=-7.05453E+8                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 77  E= 0           R=-1.5708      X=-3.10179E+9                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 78  E= 0           R=-1.5708      X=-4.86159E+9                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 79  E= 0           R=-1.5708      X=-8.62908E+8                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 80  E= 0           R=-1.5708      X=-3.4101E+9                       
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 81  E= 0           R= 1.5708      X= 3.3889E+9                       
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 82  E= 0           R= 1.5708      X= 2.49826E+9                      
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 83  E= 0           R= 1.5708      X= 2.3491E+9                       
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 84  E= 0           R= 1.5708      X= 1.94745E+8                      
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 85  E= 0           R= 1.5708      X= 2.02475E+9                      
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 86  E= 0           R=-1.5708      X=-2.26748E+9                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 87  E= 0           R=-1.5708      X=-2.10587E+9                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 88  E= 0           R= 1.5708      X= 4.23585E+9                      
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 89  E= 0           R=-1.5708      X=-2.66524E+9                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 90  E= 0           R= 1.5708      X= 4.01052E+9                      
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 91  E= 0           R=-1.5708      X=-4.87912E+9                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 92  E= 0           R= 1.5708      X= 1.77556E+9                      
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 93  E= 0           R= 1.5708      X= 2.87705E+8                      
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 94  E= 0           R= 1.5708      X= 1.99977E+8                      
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 95  E= 0           R=-1.5708      X=-3.39941E+9                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 96  E= 0           R=-1.5708      X=-3.49119E+9                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 97  E= 0           R=-1.5708      X=-2.86324E+9                      
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 98  E= 0           R= 1.5708      X= 4.20418E+9                      
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 99  E= 0           R=-1.5708      X=-3.1518E+9                       
               F= 0           N=-1.5708                                         
*** TEST PASSED ***                                                             
TESTCASE # 100                E= 0           R= 1.5708      X= 4.60615E+9       
               F= 0           N= 1.5708                                         
*** TEST PASSED ***                                                             
*** ALL TESTS PASSED ***                                                        
