TESTCASE # 1   E= 1           R= 0           A$=[]                              
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 2   E= 1           R= 0           A$=[ ]                             
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 3   E= 1           R= 0           A$=[3]                             
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 4   E= 1           R= 0           A$=[z]                             
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 5   E= 1           R= 0           A$=[  ]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 6   E= 1           R= 0           A$=[ 3]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 7   E= 1           R= 0           A$=[ z]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 8   E= 1           R= 0           A$=[3 ]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 9   E= 1           R= 0           A$=[z ]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 10  E= 1           R= 0           A$=[ 3 ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 11  E= 1           R= 0           A$=[ z ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 12  E= 0           R= 5.35553E+7  A$=[ LLLL]                         
               F= 0           N= 5.35553E+7                                     
*** TEST PASSED ***                                                             
TESTCASE # 13  E= 0           R= 1.35632E-19                A$=[    ''    ]     
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 14  E= 0           R= 4.95564E+28                A$=[   oo     ]     
               F= 0           N= 4.95564E+28                                    
*** TEST PASSED ***                                                             
TESTCASE # 15  E= 0           R= 1.49237E-19                A$=[ 00  ]          
               F= 0           N= 1.49237E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 16  E= 0           R= 1.80285E+17                A$=[   \\\\  ]      
               F= 0           N= 1.80285E+17                                    
*** TEST PASSED ***                                                             
TESTCASE # 17  E= 0           R= 1.14327E+27                A$=[ lllll  ]       
               F= 0           N= 1.14327E+27                                    
*** TEST PASSED ***                                                             
TESTCASE # 18  E= 0           R= 1.35632E-19                A$=[    uuuu  ]     
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 19  E= 0           R= 1.90689E-19                A$=[  a  ]          
               F= 0           N= 1.90689E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 20  E= 0           R= 1.35632E-19                A$=[       ]        
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 21  E= 0           R= 1.96856E-19                A$=[ hh     ]       
               F= 0           N= 1.96856E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 22  E= 0           R= 1.96618E-19                A$=[  h   ]         
               F= 0           N= 1.96618E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 23  E= 1           R= 0           A$=[ )]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 24  E= 0           R= 1.35632E-19                A$=[    5   ]       
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 25  E= 0           R= 1.50878E-19                A$=[  2 ]           
               F= 0           N= 1.50878E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 26  E= 0           R= 1.35675E-19                A$=[ -   ]          
               F= 0           N= 1.35675E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 27  E= 1           R= 0           A$=[dd ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 28  E= 0           R= 7.73665E+31                A$=[  tttt   ]      
               F= 0           N= 7.73665E+31                                    
*** TEST PASSED ***                                                             
TESTCASE # 29  E= 0           R= 7.10012E-4  A$=[  ::::   ]                     
               F= 0           N= 7.10012E-4                                     
*** TEST PASSED ***                                                             
TESTCASE # 30  E= 0           R= 1.15383E+19                A$=[   ___   ]      
               F= 0           N= 1.15383E+19                                    
*** TEST PASSED ***                                                             
TESTCASE # 31  E= 0           R= 1.35632E-19                A$=[     ]          
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 32  E= 0           R= 1.35632E-19                A$=[       ]        
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 33  E= 0           R= 1.60956E+19                A$=[ _____  ]       
               F= 0           N= 1.60956E+19                                    
*** TEST PASSED ***                                                             
TESTCASE # 34  E= 1           R= 0           A$=[ S ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 35  E= 0           R= 12680       A$=[  FFFF ]                       
               F= 0           N= 12680.                                         
*** TEST PASSED ***                                                             
TESTCASE # 36  E= 0           R= 1.35632E-19                A$=[    kkk]        
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 37  E= 0           R= 1.35632E-19                A$=[    NNNN  ]     
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 38  E= 0           R= 3.09728E+27                A$=[   mmmm  ]      
               F= 0           N= 3.09728E+27                                    
*** TEST PASSED ***                                                             
TESTCASE # 39  E= 0           R= 1.35632E-19                A$=[    ,,,,, ]     
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 40  E= 0           R= 1.35788E-19                A$=[OO   ]          
               F= 0           N= 1.35788E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 41  E= 0           R= 163968      A$=[   HHHH  ]                     
               F= 0           N= 163968.                                        
*** TEST PASSED ***                                                             
TESTCASE # 42  E= 1           R= 0           A$=[ < ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 43  E= 0           R= 4.8395E+25  A$=[   j    ]                      
               F= 0           N= 4.8395E+25                                     
*** TEST PASSED ***                                                             
TESTCASE # 44  E= 0           R= 1.35632E-19                A$=[    yyyy    ]   
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 45  E= 0           R= 6.0796E-13  A$=[  +++ ]                        
               F= 0           N= 6.0796E-13                                     
*** TEST PASSED ***                                                             
TESTCASE # 46  E= 1           R= 0           A$=[o  ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 47  E= 0           R= 1.35632E-19                A$=[    ((]         
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 48  E= 0           R= 1.35632E-19                A$=[     uu     ]   
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 49  E= 0           R= 1.35632E-19                A$=[    00     ]    
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 50  E= 0           R= 1.35632E-19                A$=[     HH  ]      
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 51  E= 0           R= 1.35632E-19                A$=[     ]          
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 52  E= 0           R= 1.68666E-19                A$=[  G   ]         
               F= 0           N= 1.68666E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 53  E= 0           R= 1.35632E-19                A$=[    {{{{ ]      
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 54  E= 0           R= 1.35632E-19                A$=[    ]]]     ]   
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 55  E= 1           R= 0           A$=[CCC]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 56  E= 0           R= 1.35632E-19                A$=[     44  ]      
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 57  E= 0           R= 1.35838E-19                A$=[^^  ]           
               F= 0           N= 1.35838E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 58  E= 0           R= 1.35632E-19                A$=[    QQ    ]     
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 59  E= 0           R= 1.35632E-19                A$=[     FFFF  ]    
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 60  E= 0           R= 1.3589E-19  A$=[ n   ]                         
               F= 0           N= 1.3589E-19                                     
*** TEST PASSED ***                                                             
TESTCASE # 61  E= 0           R= 1.35632E-19                A$=[    hh  ]       
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 62  E= 0           R= 1.53489E-19                A$=[555    ]        
               F= 0           N= 1.53489E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 63  E= 0           R= 1.35632E-19                A$=[    YYYY ]      
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 64  E= 0           R= 1.35632E-19                A$=[    w     ]     
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 65  E= 0           R= 2.15275E+8  A$=[MMMM ]                         
               F= 0           N= 2.15275E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 66  E= 0           R= 3.31431E+6  A$=[ JJJJ    ]                     
               F= 0           N= 3.31431E+6                                     
*** TEST PASSED ***                                                             
TESTCASE # 67  E= 0           R= 1.35632E-19                A$=[    %%    ]     
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 68  E= 0           R= 1.35632E-19                A$=[     *  ]       
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 69  E= 0           R= 1.35632E-19                A$=[    @@@   ]     
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 70  E= 1           R= 0           A$=[I ]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 71  E= 0           R= 1.35632E-19                A$=[    ss  ]       
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 72  E= 0           R= 1.94924E-19                A$=[  f ]           
               F= 0           N= 1.94924E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 73  E= 0           R= 640.502     A$=[   D  ]                        
               F= 0           N= 640.502                                        
*** TEST PASSED ***                                                             
TESTCASE # 74  E= 0           R= 1.38183E-19                A$=[###    ]        
               F= 0           N= 1.38183E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 75  E= 0           R= 1.35632E-19                A$=[    '     ]     
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 76  E= 0           R= 1.68327E+22                A$=[  dd    ]       
               F= 0           N= 1.68327E+22                                    
*** TEST PASSED ***                                                             
TESTCASE # 77  E= 0           R= 1.79849E-19                A$=[ TT    ]        
               F= 0           N= 1.79849E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 78  E= 0           R= 1.248E+33   A$=[  vvv ]                        
               F= 0           N= 1.248E+33                                      
*** TEST PASSED ***                                                             
TESTCASE # 79  E= 0           R= 1.35632E-19                A$=[    X ]         
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 80  E= 0           R= 1.35632E-19                A$=[    %   ]       
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 81  E= 1           R= 0           A$=[  ]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 82  E= 0           R= 6.75051E-7  A$=[ 5555   ]                      
               F= 0           N= 6.75051E-7                                     
*** TEST PASSED ***                                                             
TESTCASE # 83  E= 0           R= 12689.6     A$=[FFFF   ]                       
               F= 0           N= 12689.6                                        
*** TEST PASSED ***                                                             
TESTCASE # 84  E= 0           R= 1.35632E-19                A$=[     %%  ]      
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 85  E= 0           R= 1.35632E-19                A$=[     ]          
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 86  E= 0           R= 8.44477E+37                A$=[  ~~~~    ]     
               F= 0           N= 8.44477E+37                                    
*** TEST PASSED ***                                                             
TESTCASE # 87  E= 0           R= 3.32568E+36                A$=[   ||    ]      
               F= 0           N= 3.32568E+36                                    
*** TEST PASSED ***                                                             
TESTCASE # 88  E= 0           R= 1.35632E-19                A$=[     SSS     ]  
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 89  E= 0           R= 2.38606E-6  A$=[   6666 ]                      
               F= 0           N= 2.38606E-6                                     
*** TEST PASSED ***                                                             
TESTCASE # 90  E= 0           R= 1.35632E-19                A$=[    ww   ]      
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 91  E= 0           R= 2.57752E-9  A$=[  1111   ]                     
               F= 0           N= 2.57752E-9                                     
*** TEST PASSED ***                                                             
TESTCASE # 92  E= 1           R= 0           A$=[ K ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 93  E= 0           R= 7.73665E+31                A$=[  ttttt ]       
               F= 0           N= 7.73665E+31                                    
*** TEST PASSED ***                                                             
TESTCASE # 94  E= 0           R= 3.47807E+9  A$=[ OOOOO   ]                     
               F= 0           N= 3.47807E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 95  E= 0           R= 1.35754E-19                A$=[ E  ]           
               F= 0           N= 1.35754E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 96  E= 0           R= 1.39796E+10                A$=[ PPPPP   ]      
               F= 0           N= 1.39796E+10                                    
*** TEST PASSED ***                                                             
TESTCASE # 97  E= 0           R= 1.35632E-19                A$=[    == ]        
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 98  E= 0           R= 5.89163E+13                A$=[ VVVV    ]      
               F= 0           N= 5.89163E+13                                    
*** TEST PASSED ***                                                             
TESTCASE # 99  E= 0           R= 1.35853E-19                A$=[ c   ]          
               F= 0           N= 1.35853E-19                                    
*** TEST PASSED ***                                                             
TESTCASE # 100                E= 0           R= 1.35632E-19                A$=[ 
    yyyy     ]                                                                  
               F= 0           N= 1.35632E-19                                    
*** TEST PASSED ***                                                             
*** ALL TESTS PASSED ***                                                        
