TESTCASE # 1   E= 1           R= 0           A$=[]                              
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 2   E= 1           R= 0           A$=[ ]                             
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 3   E= 1           R= 0           A$=[3]                             
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 4   E= 1           R= 0           A$=[z]                             
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 5   E= 1           R= 0           A$=[  ]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 6   E= 1           R= 0           A$=[ 3]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 7   E= 1           R= 0           A$=[ z]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 8   E= 1           R= 0           A$=[3 ]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 9   E= 1           R= 0           A$=[z ]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 10  E= 1           R= 0           A$=[ 3 ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 11  E= 1           R= 0           A$=[ z ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 12  E= 0           R= 1.28007E+9  A$=[ LLLL]                         
               F= 0           N= 1.28007E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 13  E= 0           R= 5.38976E+8  A$=[    ''    ]                    
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 14  E= 0           R= 1.86438E+9  A$=[   oo     ]                    
               F= 0           N= 1.86438E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 15  E= 0           R= 5.40029E+8  A$=[ 00  ]                         
               F= 0           N= 5.40029E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 16  E= 0           R= 1.54561E+9  A$=[   \\\\  ]                     
               F= 0           N= 1.54561E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 17  E= 0           R= 1.81904E+9  A$=[ lllll  ]                      
               F= 0           N= 1.81904E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 18  E= 0           R= 5.38976E+8  A$=[    uuuu  ]                    
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 19  E= 0           R= 5.43236E+8  A$=[  a  ]                         
               F= 0           N= 5.43236E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 20  E= 0           R= 5.38976E+8  A$=[       ]                       
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 21  E= 0           R= 5.43713E+8  A$=[ hh     ]                      
               F= 0           N= 5.43713E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 22  E= 0           R= 5.43695E+8  A$=[  h   ]                        
               F= 0           N= 5.43695E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 23  E= 1           R= 0           A$=[ )]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 24  E= 0           R= 5.38976E+8  A$=[    5   ]                      
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 25  E= 0           R= 5.40156E+8  A$=[  2 ]                          
               F= 0           N= 5.40156E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 26  E= 0           R= 5.3898E+8   A$=[ -   ]                         
               F= 0           N= 5.3898E+8                                      
*** TEST PASSED ***                                                             
TESTCASE # 27  E= 1           R= 0           A$=[dd ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 28  E= 0           R= 1.95377E+9  A$=[  tttt   ]                     
               F= 0           N= 1.95377E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 29  E= 0           R= 9.76888E+8  A$=[  ::::   ]                     
               F= 0           N= 9.76888E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 30  E= 0           R= 1.59594E+9  A$=[   ___   ]                     
               F= 0           N= 1.59594E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 31  E= 0           R= 5.38976E+8  A$=[     ]                         
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 32  E= 0           R= 5.38976E+8  A$=[       ]                       
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 33  E= 0           R= 1.60009E+9  A$=[ _____  ]                      
               F= 0           N= 1.60009E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 34  E= 1           R= 0           A$=[ S ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 35  E= 0           R= 1.179E+9    A$=[  FFFF ]                       
               F= 0           N= 1.179E+9                                       
*** TEST PASSED ***                                                             
TESTCASE # 36  E= 0           R= 5.38976E+8  A$=[    kkk]                       
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 37  E= 0           R= 5.38976E+8  A$=[    NNNN  ]                    
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 38  E= 0           R= 1.83082E+9  A$=[   mmmm  ]                     
               F= 0           N= 1.83082E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 39  E= 0           R= 5.38976E+8  A$=[    ,,,,, ]                    
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 40  E= 0           R= 5.38988E+8  A$=[OO   ]                         
               F= 0           N= 5.38988E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 41  E= 0           R= 1.21006E+9  A$=[   HHHH  ]                     
               F= 0           N= 1.21006E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 42  E= 1           R= 0           A$=[ < ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 43  E= 0           R= 1.78049E+9  A$=[   j    ]                      
               F= 0           N= 1.78049E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 44  E= 0           R= 5.38976E+8  A$=[    yyyy    ]                  
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 45  E= 0           R= 7.24247E+8  A$=[  +++ ]                        
               F= 0           N= 7.24247E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 46  E= 1           R= 0           A$=[o  ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 47  E= 0           R= 5.38976E+8  A$=[    ((]                        
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 48  E= 0           R= 5.38976E+8  A$=[     uu     ]                  
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 49  E= 0           R= 5.38976E+8  A$=[    00     ]                   
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 50  E= 0           R= 5.38976E+8  A$=[     HH  ]                     
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 51  E= 0           R= 5.38976E+8  A$=[     ]                         
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 52  E= 0           R= 5.41532E+8  A$=[  G   ]                        
               F= 0           N= 5.41532E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 53  E= 0           R= 5.38976E+8  A$=[    {{{{ ]                     
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 54  E= 0           R= 5.38976E+8  A$=[    ]]]     ]                  
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 55  E= 1           R= 0           A$=[CCC]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 56  E= 0           R= 5.38976E+8  A$=[     44  ]                     
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 57  E= 0           R= 5.38992E+8  A$=[^^  ]                          
               F= 0           N= 5.38992E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 58  E= 0           R= 5.38976E+8  A$=[    QQ    ]                    
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 59  E= 0           R= 5.38976E+8  A$=[     FFFF  ]                   
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 60  E= 0           R= 5.38996E+8  A$=[ n   ]                         
               F= 0           N= 5.38996E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 61  E= 0           R= 5.38976E+8  A$=[    hh  ]                      
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 62  E= 0           R= 5.40358E+8  A$=[555    ]                       
               F= 0           N= 5.40358E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 63  E= 0           R= 5.38976E+8  A$=[    YYYY ]                     
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 64  E= 0           R= 5.38976E+8  A$=[    w     ]                    
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 65  E= 0           R= 1.29691E+9  A$=[MMMM ]                         
               F= 0           N= 1.29691E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 66  E= 0           R= 1.24638E+9  A$=[ JJJJ    ]                     
               F= 0           N= 1.24638E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 67  E= 0           R= 5.38976E+8  A$=[    %%    ]                    
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 68  E= 0           R= 5.38976E+8  A$=[     *  ]                      
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 69  E= 0           R= 5.38976E+8  A$=[    @@@   ]                    
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 70  E= 1           R= 0           A$=[I ]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 71  E= 0           R= 5.38976E+8  A$=[    ss  ]                      
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 72  E= 0           R= 5.43564E+8  A$=[  f ]                          
               F= 0           N= 5.43564E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 73  E= 0           R= 1.14296E+9  A$=[   D  ]                        
               F= 0           N= 1.14296E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 74  E= 0           R= 5.39174E+8  A$=[###    ]                       
               F= 0           N= 5.39174E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 75  E= 0           R= 5.38976E+8  A$=[    '     ]                    
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 76  E= 0           R= 1.68428E+9  A$=[  dd    ]                      
               F= 0           N= 1.68428E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 77  E= 0           R= 5.42397E+8  A$=[ TT    ]                       
               F= 0           N= 5.42397E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 78  E= 0           R= 1.98745E+9  A$=[  vvv ]                        
               F= 0           N= 1.98745E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 79  E= 0           R= 5.38976E+8  A$=[    X ]                        
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 80  E= 0           R= 5.38976E+8  A$=[    %   ]                      
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 81  E= 1           R= 0           A$=[  ]                            
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 82  E= 0           R= 8.92679E+8  A$=[ 5555   ]                      
               F= 0           N= 8.92679E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 83  E= 0           R= 1.17901E+9  A$=[FFFF   ]                       
               F= 0           N= 1.17901E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 84  E= 0           R= 5.38976E+8  A$=[     %%  ]                     
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 85  E= 0           R= 5.38976E+8  A$=[     ]                         
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 86  E= 0           R= 2.12219E+9  A$=[  ~~~~    ]                    
               F= 0           N= 2.12219E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 87  E= 0           R= 2.08248E+9  A$=[   ||    ]                     
               F= 0           N= 2.08248E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 88  E= 0           R= 5.38976E+8  A$=[     SSS     ]                 
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 89  E= 0           R= 9.08075E+8  A$=[   6666 ]                      
               F= 0           N= 9.08075E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 90  E= 0           R= 5.38976E+8  A$=[    ww   ]                     
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 91  E= 0           R= 8.25303E+8  A$=[  1111   ]                     
               F= 0           N= 8.25303E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 92  E= 1           R= 0           A$=[ K ]                           
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 93  E= 0           R= 1.95377E+9  A$=[  ttttt ]                      
               F= 0           N= 1.95377E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 94  E= 0           R= 1.3306E+9   A$=[ OOOOO   ]                     
               F= 0           N= 1.3306E+9                                      
*** TEST PASSED ***                                                             
TESTCASE # 95  E= 0           R= 5.38986E+8  A$=[ E  ]                          
               F= 0           N= 5.38986E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 96  E= 0           R= 1.34744E+9  A$=[ PPPPP   ]                     
               F= 0           N= 1.34744E+9                                     
*** TEST PASSED ***                                                             
TESTCASE # 97  E= 0           R= 5.38976E+8  A$=[    == ]                       
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 98  E= 0           R= 1.4485E+9   A$=[ VVVV    ]                     
               F= 0           N= 1.4485E+9                                      
*** TEST PASSED ***                                                             
TESTCASE # 99  E= 0           R= 5.38993E+8  A$=[ c   ]                         
               F= 0           N= 5.38993E+8                                     
*** TEST PASSED ***                                                             
TESTCASE # 100                E= 0           R= 5.38976E+8  A$=[    yyyy     ]  
               F= 0           N= 5.38976E+8                                     
*** TEST PASSED ***                                                             
*** ALL TESTS PASSED ***                                                        
