TESTCASE # 1   E= 1           R= 0           X= 0                               
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 2   E= 0           R= 0           X= 1                               
               F= 0           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 3   E= 1           R= 0           X=-1                               
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 4   E= 0           R=-.39794      X= .4                              
               F= 0           N=-.39794                                         
*** TEST PASSED ***                                                             
TESTCASE # 5   E= 1           R= 0           X=-.4                              
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 6   E= 0           R=-.221849     X= .6                              
               F= 0           N=-.221849                                        
*** TEST PASSED ***                                                             
TESTCASE # 7   E= 1           R= 0           X=-.6                              
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 8   E= 0           R= 2.40483     X= 254                             
               F= 0           N= 2.40483                                        
*** TEST PASSED ***                                                             
TESTCASE # 9   E= 0           R= 2.40654     X= 255                             
               F= 0           N= 2.40654                                        
*** TEST PASSED ***                                                             
TESTCASE # 10  E= 0           R= 2.40824     X= 256                             
               F= 0           N= 2.40824                                        
*** TEST PASSED ***                                                             
TESTCASE # 11  E= 0           R= 4.50515     X= 32000                           
               F= 0           N= 4.50515                                        
*** TEST PASSED ***                                                             
TESTCASE # 12  E= 1           R= 0           X=-.227229                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 13  E= 1           R= 0           X=-.239157                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 14  E= 1           R= 0           X=-.213586                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 15  E= 0           R=-.561181     X= .274675                         
               F= 0           N=-.561181                                        
*** TEST PASSED ***                                                             
TESTCASE # 16  E= 0           R=-.770149     X= .169766                         
               F= 0           N=-.770149                                        
*** TEST PASSED ***                                                             
TESTCASE # 17  E= 0           R=-.496528     X= .318766                         
               F= 0           N=-.496528                                        
*** TEST PASSED ***                                                             
TESTCASE # 18  E= 0           R=-1.68475     X= 2.06658E-2                      
               F= 0           N=-1.68475                                        
*** TEST PASSED ***                                                             
TESTCASE # 19  E= 0           R=-.725249     X= .188257                         
               F= 0           N=-.725249                                        
*** TEST PASSED ***                                                             
TESTCASE # 20  E= 1           R= 0           X=-.277537                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 21  E= 1           R= 0           X=-.481303                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 22  E= 0           R=-.360952     X= .43556                          
               F= 0           N=-.360952                                        
*** TEST PASSED ***                                                             
TESTCASE # 23  E= 1           R= 0           X=-.210971                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 24  E= 1           R= 0           X=-.455216                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 25  E= 1           R= 0           X=-110.907                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 26  E= 0           R= 2.0238      X= 105.632                         
               F= 0           N= 2.0238                                         
*** TEST PASSED ***                                                             
TESTCASE # 27  E= 1           R= 0           X=-114.341                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 28  E= 0           R= 2.04023     X= 109.706                         
               F= 0           N= 2.04023                                        
*** TEST PASSED ***                                                             
TESTCASE # 29  E= 0           R= 2.03821     X= 109.198                         
               F= 0           N= 2.03821                                        
*** TEST PASSED ***                                                             
TESTCASE # 30  E= 0           R= 1.93388     X= 85.8773                         
               F= 0           N= 1.93388                                        
*** TEST PASSED ***                                                             
TESTCASE # 31  E= 1           R= 0           X=-58.3548                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 32  E= 0           R= 1.47187     X= 29.6397                         
               F= 0           N= 1.47187                                        
*** TEST PASSED ***                                                             
TESTCASE # 33  E= 1           R= 0           X=-108.36                          
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 34  E= 1           R= 0           X=-46.5199                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 35  E= 0           R= 2.05123     X= 112.521                         
               F= 0           N= 2.05123                                        
*** TEST PASSED ***                                                             
TESTCASE # 36  E= 0           R= 1.6572      X= 45.4151                         
               F= 0           N= 1.6572                                         
*** TEST PASSED ***                                                             
TESTCASE # 37  E= 0           R= 2.00488     X= 101.129                         
               F= 0           N= 2.00488                                        
*** TEST PASSED ***                                                             
TESTCASE # 38  E= 0           R= 1.81323     X= 65.0473                         
               F= 0           N= 1.81323                                        
*** TEST PASSED ***                                                             
TESTCASE # 39  E= 0           R= 1.68486     X= 48.4012                         
               F= 0           N= 1.68486                                        
*** TEST PASSED ***                                                             
TESTCASE # 40  E= 0           R= 2.08741     X= 122.294                         
               F= 0           N= 2.08741                                        
*** TEST PASSED ***                                                             
TESTCASE # 41  E= 1           R= 0           X=-56.1094                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 42  E= 1           R= 0           X=-121.087                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 43  E= 1           R= 0           X=-123.517                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 44  E= 1           R= 0           X=-97.6301                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 45  E= 1           R= 0           X=-64.0001                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 46  E= 1           R= 0           X=-25.6888                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 47  E= 0           R= 1.17028     X= 14.8006                         
               F= 0           N= 1.17028                                        
*** TEST PASSED ***                                                             
TESTCASE # 48  E= 1           R= 0           X=-61.0877                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 49  E= 1           R= 0           X=-66.6381                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 50  E= 1           R= 0           X=-5476.5                          
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 51  E= 1           R= 0           X=-21210.3                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 52  E= 1           R= 0           X=-28757.2                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 53  E= 1           R= 0           X=-28732.2                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 54  E= 0           R= 4.10484     X= 12730.3                         
               F= 0           N= 4.10484                                        
*** TEST PASSED ***                                                             
TESTCASE # 55  E= 1           R= 0           X=-1830.69                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 56  E= 0           R= 3.73929     X= 5486.39                         
               F= 0           N= 3.73929                                        
*** TEST PASSED ***                                                             
TESTCASE # 57  E= 0           R= 4.35036     X= 22405.9                         
               F= 0           N= 4.35036                                        
*** TEST PASSED ***                                                             
TESTCASE # 58  E= 0           R= 4.48869     X= 30809.8                         
               F= 0           N= 4.48869                                        
*** TEST PASSED ***                                                             
TESTCASE # 59  E= 1           R= 0           X=-28930.6                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 60  E= 1           R= 0           X=-6014.53                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 61  E= 0           R= 4.24091     X= 17414.6                         
               F= 0           N= 4.24091                                        
*** TEST PASSED ***                                                             
TESTCASE # 62  E= 1           R= 0           X=-10538.3                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 63  E= 1           R= 0           X=-17536.3                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 64  E= 1           R= 0           X=-8856.62                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 65  E= 1           R= 0           X=-5140.12                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 66  E= 1           R= 0           X=-8595.31                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 67  E= 1           R= 0           X=-3382.87                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 68  E= 1           R= 0           X=-5002.07                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 69  E= 1           R= 0           X=-5800.72                         
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 70  E= 0           R= 4.47256     X= 29686.4                         
               F= 0           N= 4.47256                                        
*** TEST PASSED ***                                                             
TESTCASE # 71  E= 0           R= 3.4101      X= 2571                            
               F= 0           N= 3.4101                                         
*** TEST PASSED ***                                                             
TESTCASE # 72  E= 0           R= 4.49263     X= 31091                           
               F= 0           N= 4.49263                                        
*** TEST PASSED ***                                                             
TESTCASE # 73  E= 0           R= 4.17082     X= 14819                           
               F= 0           N= 4.17082                                        
*** TEST PASSED ***                                                             
TESTCASE # 74  E= 0           R= 3.57874     X= 3790.9                          
               F= 0           N= 3.57874                                        
*** TEST PASSED ***                                                             
TESTCASE # 75  E= 1           R= 0           X=-4.2981E+9                       
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 76  E= 1           R= 0           X=-7.05453E+8                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 77  E= 1           R= 0           X=-3.10179E+9                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 78  E= 1           R= 0           X=-4.86159E+9                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 79  E= 1           R= 0           X=-8.62908E+8                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 80  E= 1           R= 0           X=-3.4101E+9                       
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 81  E= 0           R= 9.53006     X= 3.3889E+9                       
               F= 0           N= 9.53006                                        
*** TEST PASSED ***                                                             
TESTCASE # 82  E= 0           R= 9.39764     X= 2.49826E+9                      
               F= 0           N= 9.39764                                        
*** TEST PASSED ***                                                             
TESTCASE # 83  E= 0           R= 9.3709      X= 2.3491E+9                       
               F= 0           N= 9.3709                                         
*** TEST PASSED ***                                                             
TESTCASE # 84  E= 0           R= 8.28947     X= 1.94745E+8                      
               F= 0           N= 8.28947                                        
*** TEST PASSED ***                                                             
TESTCASE # 85  E= 0           R= 9.30637     X= 2.02475E+9                      
               F= 0           N= 9.30637                                        
*** TEST PASSED ***                                                             
TESTCASE # 86  E= 1           R= 0           X=-2.26748E+9                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 87  E= 1           R= 0           X=-2.10587E+9                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 88  E= 0           R= 9.62694     X= 4.23585E+9                      
               F= 0           N= 9.62694                                        
*** TEST PASSED ***                                                             
TESTCASE # 89  E= 1           R= 0           X=-2.66524E+9                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 90  E= 0           R= 9.6032      X= 4.01052E+9                      
               F= 0           N= 9.6032                                         
*** TEST PASSED ***                                                             
TESTCASE # 91  E= 1           R= 0           X=-4.87912E+9                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 92  E= 0           R= 9.24934     X= 1.77556E+9                      
               F= 0           N= 9.24934                                        
*** TEST PASSED ***                                                             
TESTCASE # 93  E= 0           R= 8.45895     X= 2.87705E+8                      
               F= 0           N= 8.45895                                        
*** TEST PASSED ***                                                             
TESTCASE # 94  E= 0           R= 8.30098     X= 1.99977E+8                      
               F= 0           N= 8.30098                                        
*** TEST PASSED ***                                                             
TESTCASE # 95  E= 1           R= 0           X=-3.39941E+9                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 96  E= 1           R= 0           X=-3.49119E+9                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 97  E= 1           R= 0           X=-2.86324E+9                      
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 98  E= 0           R= 9.62368     X= 4.20418E+9                      
               F= 0           N= 9.62368                                        
*** TEST PASSED ***                                                             
TESTCASE # 99  E= 1           R= 0           X=-3.1518E+9                       
               F= 1           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 100                E= 0           R= 9.66334     X= 4.60615E+9       
               F= 0           N= 9.66334                                        
*** TEST PASSED ***                                                             
*** ALL TESTS PASSED ***                                                        
