TESTCASE # 1   E= 0           R= 1           X= 0                               
               F= 0           N= 1                                              
*** TEST PASSED ***                                                             
TESTCASE # 2   E= 0           R= 1.85082     X= 1                               
               F= 0           N= 1.85082                                        
*** TEST PASSED ***                                                             
TESTCASE # 3   E= 0           R= 1.85082     X=-1                               
               F= 0           N= 1.85082                                        
*** TEST PASSED ***                                                             
TESTCASE # 4   E= 0           R= 1.0857      X= .4                              
               F= 0           N= 1.0857                                         
*** TEST PASSED ***                                                             
TESTCASE # 5   E= 0           R= 1.0857      X=-.4                              
               F= 0           N= 1.0857                                         
*** TEST PASSED ***                                                             
TESTCASE # 6   E= 0           R= 1.21163     X= .6                              
               F= 0           N= 1.21163                                        
*** TEST PASSED ***                                                             
TESTCASE # 7   E= 0           R= 1.21163     X=-.6                              
               F= 0           N= 1.21163                                        
*** TEST PASSED ***                                                             
TESTCASE # 8   E= 0           R=-1.12105     X= 254                             
               F= 0           N=-1.12105                                        
*** TEST PASSED ***                                                             
TESTCASE # 9   E= 0           R=-1.15968     X= 255                             
               F= 0           N=-1.15968                                        
*** TEST PASSED ***                                                             
TESTCASE # 10  E= 0           R=-25.1315     X= 256                             
               F= 0           N=-25.1315                                        
*** TEST PASSED ***                                                             
TESTCASE # 11  E= 0           R= 1.03555     X= 32000                           
               F= 0           N= 1.03555                                        
*** TEST PASSED ***                                                             
TESTCASE # 12  E= 0           R= 1.02638     X=-.227229                         
               F= 0           N= 1.02638                                        
*** TEST PASSED ***                                                             
TESTCASE # 13  E= 0           R= 1.0293      X=-.239157                         
               F= 0           N= 1.0293                                         
*** TEST PASSED ***                                                             
TESTCASE # 14  E= 0           R= 1.02325     X=-.213586                         
               F= 0           N= 1.02325                                        
*** TEST PASSED ***                                                             
TESTCASE # 15  E= 0           R= 1.03895     X= .274675                         
               F= 0           N= 1.03895                                        
*** TEST PASSED ***                                                             
TESTCASE # 16  E= 0           R= 1.01459     X= .169766                         
               F= 0           N= 1.01459                                        
*** TEST PASSED ***                                                             
TESTCASE # 17  E= 0           R= 1.05305     X= .318766                         
               F= 0           N= 1.05305                                        
*** TEST PASSED ***                                                             
TESTCASE # 18  E= 0           R= 1.00021     X= 2.06658E-2                      
               F= 0           N= 1.00021                                        
*** TEST PASSED ***                                                             
TESTCASE # 19  E= 0           R= 1.01799     X= .188257                         
               F= 0           N= 1.01799                                        
*** TEST PASSED ***                                                             
TESTCASE # 20  E= 0           R= 1.03979     X=-.277537                         
               F= 0           N= 1.03979                                        
*** TEST PASSED ***                                                             
TESTCASE # 21  E= 0           R= 1.12817     X=-.481303                         
               F= 0           N= 1.12817                                        
*** TEST PASSED ***                                                             
TESTCASE # 22  E= 0           R= 1.10298     X= .43556                          
               F= 0           N= 1.10298                                        
*** TEST PASSED ***                                                             
TESTCASE # 23  E= 0           R= 1.02267     X=-.210971                         
               F= 0           N= 1.02267                                        
*** TEST PASSED ***                                                             
TESTCASE # 24  E= 0           R= 1.11338     X=-.455216                         
               F= 0           N= 1.11338                                        
*** TEST PASSED ***                                                             
TESTCASE # 25  E= 0           R=-1.72218     X=-110.907                         
               F= 0           N=-1.72218                                        
*** TEST PASSED ***                                                             
TESTCASE # 26  E= 0           R= 2.63897     X= 105.632                         
               F= 0           N= 2.63897                                        
*** TEST PASSED ***                                                             
TESTCASE # 27  E= 0           R= 3.11208     X=-114.341                         
               F= 0           N= 3.11208                                        
*** TEST PASSED ***                                                             
TESTCASE # 28  E= 0           R=-1.03202     X= 109.706                         
               F= 0           N=-1.03202                                        
*** TEST PASSED ***                                                             
TESTCASE # 29  E= 0           R=-1.37667     X= 109.198                         
               F= 0           N=-1.37667                                        
*** TEST PASSED ***                                                             
TESTCASE # 30  E= 0           R=-2.02496     X= 85.8773                         
               F= 0           N=-2.02496                                        
*** TEST PASSED ***                                                             
TESTCASE # 31  E= 0           R=-4.28872     X=-58.3548                         
               F= 0           N=-4.28872                                        
*** TEST PASSED ***                                                             
TESTCASE # 32  E= 0           R=-4.90224     X= 29.6397                         
               F= 0           N=-4.90224                                        
*** TEST PASSED ***                                                             
TESTCASE # 33  E= 0           R= 40.0899     X=-108.36                          
               F= 0           N= 40.0899                                        
*** TEST PASSED ***                                                             
TESTCASE # 34  E= 0           R=-1.21495     X=-46.5199                         
               F= 0           N=-1.21495                                        
*** TEST PASSED ***                                                             
TESTCASE # 35  E= 0           R= 1.19266     X= 112.521                         
               F= 0           N= 1.19266                                        
*** TEST PASSED ***                                                             
TESTCASE # 36  E= 0           R= 7.26977     X= 45.4151                         
               F= 0           N= 7.26977                                        
*** TEST PASSED ***                                                             
TESTCASE # 37  E= 0           R= 1.21        X= 101.129                         
               F= 0           N= 1.21                                           
*** TEST PASSED ***                                                             
TESTCASE # 38  E= 0           R=-1.66412     X= 65.0473                         
               F= 0           N=-1.66412                                        
*** TEST PASSED ***                                                             
TESTCASE # 39  E= 0           R=-3.45673     X= 48.4012                         
               F= 0           N=-3.45673                                        
*** TEST PASSED ***                                                             
TESTCASE # 40  E= 0           R=-1.02659     X= 122.294                         
               F= 0           N=-1.02659                                        
*** TEST PASSED ***                                                             
TESTCASE # 41  E= 0           R= 1.1049      X=-56.1094                         
               F= 0           N= 1.1049                                         
*** TEST PASSED ***                                                             
TESTCASE # 42  E= 0           R=-7.39279     X=-121.087                         
               F= 0           N=-7.39279                                        
*** TEST PASSED ***                                                             
TESTCASE # 43  E= 0           R=-1.83622     X=-123.517                         
               F= 0           N=-1.83622                                        
*** TEST PASSED ***                                                             
TESTCASE # 44  E= 0           R=-1.02969     X=-97.6301                         
               F= 0           N=-1.02969                                        
*** TEST PASSED ***                                                             
TESTCASE # 45  E= 0           R= 2.55255     X=-64.0001                         
               F= 0           N= 2.55255                                        
*** TEST PASSED ***                                                             
TESTCASE # 46  E= 0           R= 1.17738     X=-25.6888                         
               F= 0           N= 1.17738                                        
*** TEST PASSED ***                                                             
TESTCASE # 47  E= 0           R=-1.62384     X= 14.8006                         
               F= 0           N=-1.62384                                        
*** TEST PASSED ***                                                             
TESTCASE # 48  E= 0           R=-5.79745     X=-61.0877                         
               F= 0           N=-5.79745                                        
*** TEST PASSED ***                                                             
TESTCASE # 49  E= 0           R=-1.27044     X=-66.6381                         
               F= 0           N=-1.27044                                        
*** TEST PASSED ***                                                             
TESTCASE # 50  E= 0           R=-1.3119      X=-5476.5                          
               F= 0           N=-1.3119                                         
*** TEST PASSED ***                                                             
TESTCASE # 51  E= 0           R=-6.1697      X=-21210.3                         
               F= 0           N=-6.1697                                         
*** TEST PASSED ***                                                             
TESTCASE # 52  E= 0           R= 1.69356     X=-28757.2                         
               F= 0           N= 1.69356                                        
*** TEST PASSED ***                                                             
TESTCASE # 53  E= 0           R= 1.44489     X=-28732.2                         
               F= 0           N= 1.44489                                        
*** TEST PASSED ***                                                             
TESTCASE # 54  E= 0           R= 1.18519     X= 12730.3                         
               F= 0           N= 1.18519                                        
*** TEST PASSED ***                                                             
TESTCASE # 55  E= 0           R=-1.53008     X=-1830.69                         
               F= 0           N=-1.53008                                        
*** TEST PASSED ***                                                             
TESTCASE # 56  E= 0           R= 2.55844     X= 5486.39                         
               F= 0           N= 2.55844                                        
*** TEST PASSED ***                                                             
TESTCASE # 57  E= 0           R= 1.00188     X= 22405.9                         
               F= 0           N= 1.00188                                        
*** TEST PASSED ***                                                             
TESTCASE # 58  E= 0           R=-1.02051     X= 30809.8                         
               F= 0           N=-1.02051                                        
*** TEST PASSED ***                                                             
TESTCASE # 59  E= 0           R=-1.05586     X=-28930.6                         
               F= 0           N=-1.05586                                        
*** TEST PASSED ***                                                             
TESTCASE # 60  E= 0           R= 20.3602     X=-6014.53                         
               F= 0           N= 20.3602                                        
*** TEST PASSED ***                                                             
TESTCASE # 61  E= 0           R=-1.36915     X= 17414.6                         
               F= 0           N=-1.36915                                        
*** TEST PASSED ***                                                             
TESTCASE # 62  E= 0           R= 5.82406     X=-10538.3                         
               F= 0           N= 5.82406                                        
*** TEST PASSED ***                                                             
TESTCASE # 63  E= 0           R= 1.00247     X=-17536.3                         
               F= 0           N= 1.00247                                        
*** TEST PASSED ***                                                             
TESTCASE # 64  E= 0           R=-1.1218      X=-8856.62                         
               F= 0           N=-1.1218                                         
*** TEST PASSED ***                                                             
TESTCASE # 65  E= 0           R= 1.12415     X=-5140.12                         
               F= 0           N= 1.12415                                        
*** TEST PASSED ***                                                             
TESTCASE # 66  E= 0           R= 1.00384     X=-8595.31                         
               F= 0           N= 1.00384                                        
*** TEST PASSED ***                                                             
TESTCASE # 67  E= 0           R=-1.23336     X=-3382.87                         
               F= 0           N=-1.23336                                        
*** TEST PASSED ***                                                             
TESTCASE # 68  E= 0           R= 1.26047     X=-5002.07                         
               F= 0           N= 1.26047                                        
*** TEST PASSED ***                                                             
TESTCASE # 69  E= 0           R= 4.37081     X=-5800.72                         
               F= 0           N= 4.37081                                        
*** TEST PASSED ***                                                             
TESTCASE # 70  E= 0           R=-12.5478     X= 29686.4                         
               F= 0           N=-12.5478                                        
*** TEST PASSED ***                                                             
TESTCASE # 71  E= 0           R= 2.60754     X= 2571                            
               F= 0           N= 2.60754                                        
*** TEST PASSED ***                                                             
TESTCASE # 72  E= 0           R=-4.41841     X= 31091                           
               F= 0           N=-4.41841                                        
*** TEST PASSED ***                                                             
TESTCASE # 73  E= 0           R=-1.0058      X= 14819                           
               F= 0           N=-1.0058                                         
*** TEST PASSED ***                                                             
TESTCASE # 74  E= 0           R=-1.85757     X= 3790.9                          
               F= 0           N=-1.85757                                        
*** TEST PASSED ***                                                             
TESTCASE # 75  E= 0           R= 1.21811     X=-4.2981E+9                       
               F= 0           N= 1.21811                                        
*** TEST PASSED ***                                                             
TESTCASE # 76  E= 0           R= 1.10197     X=-7.05453E+8                      
               F= 0           N= 1.10197                                        
*** TEST PASSED ***                                                             
TESTCASE # 77  E= 0           R= 1.09563     X=-3.10179E+9                      
               F= 0           N= 1.09563                                        
*** TEST PASSED ***                                                             
TESTCASE # 78  E= 0           R= 4.44344     X=-4.86159E+9                      
               F= 0           N= 4.44344                                        
*** TEST PASSED ***                                                             
TESTCASE # 79  E= 0           R=-1.49665     X=-8.62908E+8                      
               F= 0           N=-1.49665                                        
*** TEST PASSED ***                                                             
TESTCASE # 80  E= 0           R=-1.08191     X=-3.4101E+9                       
               F= 0           N=-1.08191                                        
*** TEST PASSED ***                                                             
TESTCASE # 81  E= 0           R=-1.6201      X= 3.3889E+9                       
               F= 0           N=-1.6201                                         
*** TEST PASSED ***                                                             
TESTCASE # 82  E= 0           R= 1.44883     X= 2.49826E+9                      
               F= 0           N= 1.44883                                        
*** TEST PASSED ***                                                             
TESTCASE # 83  E= 0           R= 2.44122     X= 2.3491E+9                       
               F= 0           N= 2.44122                                        
*** TEST PASSED ***                                                             
TESTCASE # 84  E= 0           R=-1.28179     X= 1.94745E+8                      
               F= 0           N=-1.28179                                        
*** TEST PASSED ***                                                             
TESTCASE # 85  E= 0           R= 1.01278     X= 2.02475E+9                      
               F= 0           N= 1.01278                                        
*** TEST PASSED ***                                                             
TESTCASE # 86  E= 0           R=-1.54534     X=-2.26748E+9                      
               F= 0           N=-1.54534                                        
*** TEST PASSED ***                                                             
TESTCASE # 87  E= 0           R= 1.00158     X=-2.10587E+9                      
               F= 0           N= 1.00158                                        
*** TEST PASSED ***                                                             
TESTCASE # 88  E= 0           R=-2.99423     X= 4.23585E+9                      
               F= 0           N=-2.99423                                        
*** TEST PASSED ***                                                             
TESTCASE # 89  E= 0           R=-1.01375     X=-2.66524E+9                      
               F= 0           N=-1.01375                                        
*** TEST PASSED ***                                                             
TESTCASE # 90  E= 0           R=-1.47161     X= 4.01052E+9                      
               F= 0           N=-1.47161                                        
*** TEST PASSED ***                                                             
TESTCASE # 91  E= 0           R= 1.07953     X=-4.87912E+9                      
               F= 0           N= 1.07953                                        
*** TEST PASSED ***                                                             
TESTCASE # 92  E= 0           R= 25.4889     X= 1.77556E+9                      
               F= 0           N= 25.4889                                        
*** TEST PASSED ***                                                             
TESTCASE # 93  E= 0           R= 1.2236      X= 2.87705E+8                      
               F= 0           N= 1.2236                                         
*** TEST PASSED ***                                                             
TESTCASE # 94  E= 0           R= 1.06209     X= 1.99977E+8                      
               F= 0           N= 1.06209                                        
*** TEST PASSED ***                                                             
TESTCASE # 95  E= 0           R= 1.21439     X=-3.39941E+9                      
               F= 0           N= 1.21439                                        
*** TEST PASSED ***                                                             
TESTCASE # 96  E= 0           R= 6.9457      X=-3.49119E+9                      
               F= 0           N= 6.9457                                         
*** TEST PASSED ***                                                             
TESTCASE # 97  E= 0           R=-18.8696     X=-2.86324E+9                      
               F= 0           N=-18.8696                                        
*** TEST PASSED ***                                                             
TESTCASE # 98  E= 0           R=-1.6737      X= 4.20418E+9                      
               F= 0           N=-1.6737                                         
*** TEST PASSED ***                                                             
TESTCASE # 99  E= 0           R=-1.53453     X=-3.1518E+9                       
               F= 0           N=-1.53453                                        
*** TEST PASSED ***                                                             
TESTCASE # 100                E= 0           R= 1.3945      X= 4.60615E+9       
               F= 0           N= 1.3945                                         
*** TEST PASSED ***                                                             
*** ALL TESTS PASSED ***                                                        
