TESTCASE # 1   E= 0           R= 0           X= 0                               
               F= 0           N= 0                                              
*** TEST PASSED ***                                                             
TESTCASE # 2   E= 0           R= 1.55741     X= 1                               
               F= 0           N= 1.55741                                        
*** TEST PASSED ***                                                             
TESTCASE # 3   E= 0           R=-1.55741     X=-1                               
               F= 0           N=-1.55741                                        
*** TEST PASSED ***                                                             
TESTCASE # 4   E= 0           R= .422793     X= .4                              
               F= 0           N= .422793                                        
*** TEST PASSED ***                                                             
TESTCASE # 5   E= 0           R=-.422793     X=-.4                              
               F= 0           N=-.422793                                        
*** TEST PASSED ***                                                             
TESTCASE # 6   E= 0           R= .684137     X= .6                              
               F= 0           N= .684137                                        
*** TEST PASSED ***                                                             
TESTCASE # 7   E= 0           R=-.684137     X=-.6                              
               F= 0           N=-.684137                                        
*** TEST PASSED ***                                                             
TESTCASE # 8   E= 0           R=-.506715     X= 254                             
               F= 0           N=-.506715                                        
*** TEST PASSED ***                                                             
TESTCASE # 9   E= 0           R= .587254     X= 255                             
               F= 0           N= .587254                                        
*** TEST PASSED ***                                                             
TESTCASE # 10  E= 0           R= 25.1116     X= 256                             
               F= 0           N= 25.1116                                        
*** TEST PASSED ***                                                             
TESTCASE # 11  E= 0           R=-.268989     X= 32000                           
               F= 0           N=-.268989                                        
*** TEST PASSED ***                                                             
TESTCASE # 12  E= 0           R=-.231222     X=-.227229                         
               F= 0           N=-.231222                                        
*** TEST PASSED ***                                                             
TESTCASE # 13  E= 0           R=-.243823     X=-.239157                         
               F= 0           N=-.243823                                        
*** TEST PASSED ***                                                             
TESTCASE # 14  E= 0           R=-.216894     X=-.213586                         
               F= 0           N=-.216894                                        
*** TEST PASSED ***                                                             
TESTCASE # 15  E= 0           R= .281798     X= .274675                         
               F= 0           N= .281798                                        
*** TEST PASSED ***                                                             
TESTCASE # 16  E= 0           R= .171416     X= .169766                         
               F= 0           N= .171416                                        
*** TEST PASSED ***                                                             
TESTCASE # 17  E= 0           R= .33002      X= .318766                         
               F= 0           N= .33002                                         
*** TEST PASSED ***                                                             
TESTCASE # 18  E= 0           R= 2.06687E-2  X= 2.06658E-2                      
               F= 0           N= 2.06687E-2                                     
*** TEST PASSED ***                                                             
TESTCASE # 19  E= 0           R= .190513     X= .188257                         
               F= 0           N= .190513                                        
*** TEST PASSED ***                                                             
TESTCASE # 20  E= 0           R=-.28489      X=-.277537                         
               F= 0           N=-.28489                                         
*** TEST PASSED ***                                                             
TESTCASE # 21  E= 0           R=-.522268     X=-.481303                         
               F= 0           N=-.522268                                        
*** TEST PASSED ***                                                             
TESTCASE # 22  E= 0           R= .465368     X= .43556                          
               F= 0           N= .465368                                        
*** TEST PASSED ***                                                             
TESTCASE # 23  E= 0           R=-.214158     X=-.210971                         
               F= 0           N=-.214158                                        
*** TEST PASSED ***                                                             
TESTCASE # 24  E= 0           R=-.489504     X=-.455216                         
               F= 0           N=-.489504                                        
*** TEST PASSED ***                                                             
TESTCASE # 25  E= 0           R=-1.4021      X=-110.907                         
               F= 0           N=-1.4021                                         
*** TEST PASSED ***                                                             
TESTCASE # 26  E= 0           R=-2.44216     X= 105.632                         
               F= 0           N=-2.44216                                        
*** TEST PASSED ***                                                             
TESTCASE # 27  E= 0           R=-2.94704     X=-114.341                         
               F= 0           N=-2.94704                                        
*** TEST PASSED ***                                                             
TESTCASE # 28  E= 0           R=-.255068     X= 109.706                         
               F= 0           N=-.255068                                        
*** TEST PASSED ***                                                             
TESTCASE # 29  E= 0           R=-.946165     X= 109.198                         
               F= 0           N=-.946165                                        
*** TEST PASSED ***                                                             
TESTCASE # 30  E= 0           R= 1.76081     X= 85.8773                         
               F= 0           N= 1.76081                                        
*** TEST PASSED ***                                                             
TESTCASE # 31  E= 0           R= 4.17051     X=-58.3548                         
               F= 0           N= 4.17051                                        
*** TEST PASSED ***                                                             
TESTCASE # 32  E= 0           R= 4.79916     X= 29.6397                         
               F= 0           N= 4.79916                                        
*** TEST PASSED ***                                                             
TESTCASE # 33  E= 0           R=-40.0774     X=-108.36                          
               F= 0           N=-40.0774                                        
*** TEST PASSED ***                                                             
TESTCASE # 34  E= 0           R= .69001      X=-46.5199                         
               F= 0           N= .69001                                         
*** TEST PASSED ***                                                             
TESTCASE # 35  E= 0           R=-.649944     X= 112.521                         
               F= 0           N=-.649944                                        
*** TEST PASSED ***                                                             
TESTCASE # 36  E= 0           R= 7.20066     X= 45.4151                         
               F= 0           N= 7.20066                                        
*** TEST PASSED ***                                                             
TESTCASE # 37  E= 0           R= .681256     X= 101.129                         
               F= 0           N= .681256                                        
*** TEST PASSED ***                                                             
TESTCASE # 38  E= 0           R=-1.33015     X= 65.0473                         
               F= 0           N=-1.33015                                        
*** TEST PASSED ***                                                             
TESTCASE # 39  E= 0           R= 3.30892     X= 48.4012                         
               F= 0           N= 3.30892                                        
*** TEST PASSED ***                                                             
TESTCASE # 40  E= 0           R=-.232154     X= 122.294                         
               F= 0           N=-.232154                                        
*** TEST PASSED ***                                                             
TESTCASE # 41  E= 0           R= .469886     X=-56.1094                         
               F= 0           N= .469886                                        
*** TEST PASSED ***                                                             
TESTCASE # 42  E= 0           R= 7.32485     X=-121.087                         
               F= 0           N= 7.32485                                        
*** TEST PASSED ***                                                             
TESTCASE # 43  E= 0           R=-1.54003     X=-123.517                         
               F= 0           N=-1.54003                                        
*** TEST PASSED ***                                                             
TESTCASE # 44  E= 0           R=-.245488     X=-97.6301                         
               F= 0           N=-.245488                                        
*** TEST PASSED ***                                                             
TESTCASE # 45  E= 0           R=-2.34851     X=-64.0001                         
               F= 0           N=-2.34851                                        
*** TEST PASSED ***                                                             
TESTCASE # 46  E= 0           R=-.621473     X=-25.6888                         
               F= 0           N=-.621473                                        
*** TEST PASSED ***                                                             
TESTCASE # 47  E= 0           R=-1.27939     X= 14.8006                         
               F= 0           N=-1.27939                                        
*** TEST PASSED ***                                                             
TESTCASE # 48  E= 0           R=-5.71055     X=-61.0877                         
               F= 0           N=-5.71055                                        
*** TEST PASSED ***                                                             
TESTCASE # 49  E= 0           R=-.78359      X=-66.6381                         
               F= 0           N=-.78359                                         
*** TEST PASSED ***                                                             
TESTCASE # 50  E= 0           R=-.849158     X=-5476.5                          
               F= 0           N=-.849158                                        
*** TEST PASSED ***                                                             
TESTCASE # 51  E= 0           R=-6.08812     X=-21210.3                         
               F= 0           N=-6.08812                                        
*** TEST PASSED ***                                                             
TESTCASE # 52  E= 0           R= 1.3668      X=-28757.2                         
               F= 0           N= 1.3668                                         
*** TEST PASSED ***                                                             
TESTCASE # 53  E= 0           R= 1.04293     X=-28732.2                         
               F= 0           N= 1.04293                                        
*** TEST PASSED ***                                                             
TESTCASE # 54  E= 0           R= .636137     X= 12730.3                         
               F= 0           N= .636137                                        
*** TEST PASSED ***                                                             
TESTCASE # 55  E= 0           R= 1.15808     X=-1830.69                         
               F= 0           N= 1.15808                                        
*** TEST PASSED ***                                                             
TESTCASE # 56  E= 0           R= 2.35491     X= 5486.39                         
               F= 0           N= 2.35491                                        
*** TEST PASSED ***                                                             
TESTCASE # 57  E= 0           R= 6.12711E-2  X= 22405.9                         
               F= 0           N= 6.12711E-2                                     
*** TEST PASSED ***                                                             
TESTCASE # 58  E= 0           R= .203591     X= 30809.8                         
               F= 0           N= .203591                                        
*** TEST PASSED ***                                                             
TESTCASE # 59  E= 0           R= .338894     X=-28930.6                         
               F= 0           N= .338894                                        
*** TEST PASSED ***                                                             
TESTCASE # 60  E= 0           R=-20.3356     X=-6014.53                         
               F= 0           N=-20.3356                                        
*** TEST PASSED ***                                                             
TESTCASE # 61  E= 0           R= .935191     X= 17414.6                         
               F= 0           N= .935191                                        
*** TEST PASSED ***                                                             
TESTCASE # 62  E= 0           R=-5.73757     X=-10538.3                         
               F= 0           N=-5.73757                                        
*** TEST PASSED ***                                                             
TESTCASE # 63  E= 0           R= 7.03078E-2  X=-17536.3                         
               F= 0           N= 7.03078E-2                                     
*** TEST PASSED ***                                                             
TESTCASE # 64  E= 0           R=-.508355     X=-8856.62                         
               F= 0           N=-.508355                                        
*** TEST PASSED ***                                                             
TESTCASE # 65  E= 0           R=-.513537     X=-5140.12                         
               F= 0           N=-.513537                                        
*** TEST PASSED ***                                                             
TESTCASE # 66  E= 0           R= 8.77242E-2  X=-8595.31                         
               F= 0           N= 8.77242E-2                                     
*** TEST PASSED ***                                                             
TESTCASE # 67  E= 0           R= .721922     X=-3382.87                         
               F= 0           N= .721922                                        
*** TEST PASSED ***                                                             
TESTCASE # 68  E= 0           R=-.767322     X=-5002.07                         
               F= 0           N=-.767322                                        
*** TEST PASSED ***                                                             
TESTCASE # 69  E= 0           R=-4.25488     X=-5800.72                         
               F= 0           N=-4.25488                                        
*** TEST PASSED ***                                                             
TESTCASE # 70  E= 0           R= 12.5078     X= 29686.4                         
               F= 0           N= 12.5078                                        
*** TEST PASSED ***                                                             
TESTCASE # 71  E= 0           R= 2.40816     X= 2571                            
               F= 0           N= 2.40816                                        
*** TEST PASSED ***                                                             
TESTCASE # 72  E= 0           R=-4.30376     X= 31091                           
               F= 0           N=-4.30376                                        
*** TEST PASSED ***                                                             
TESTCASE # 73  E= 0           R= .107868     X= 14819                           
               F= 0           N= .107868                                        
*** TEST PASSED ***                                                             
TESTCASE # 74  E= 0           R=-1.56543     X= 3790.9                          
               F= 0           N=-1.56543                                        
*** TEST PASSED ***                                                             
TESTCASE # 75  E= 0           R= .695559     X=-4.2981E+9                       
               F= 0           N= .695559                                        
*** TEST PASSED ***                                                             
TESTCASE # 76  E= 0           R=-.462965     X=-7.05453E+8                      
               F= 0           N=-.462965                                        
*** TEST PASSED ***                                                             
TESTCASE # 77  E= 0           R= .447665     X=-3.10179E+9                      
               F= 0           N= .447665                                        
*** TEST PASSED ***                                                             
TESTCASE # 78  E= 0           R= 4.32945     X=-4.86159E+9                      
               F= 0           N= 4.32945                                        
*** TEST PASSED ***                                                             
TESTCASE # 79  E= 0           R=-1.11353     X=-8.62908E+8                      
               F= 0           N=-1.11353                                        
*** TEST PASSED ***                                                             
TESTCASE # 80  E= 0           R= .412946     X=-3.4101E+9                       
               F= 0           N= .412946                                        
*** TEST PASSED ***                                                             
TESTCASE # 81  E= 0           R= 1.27465     X= 3.3889E+9                       
               F= 0           N= 1.27465                                        
*** TEST PASSED ***                                                             
TESTCASE # 82  E= 0           R= 1.04838     X= 2.49826E+9                      
               F= 0           N= 1.04838                                        
*** TEST PASSED ***                                                             
TESTCASE # 83  E= 0           R=-2.22701     X= 2.3491E+9                       
               F= 0           N=-2.22701                                        
*** TEST PASSED ***                                                             
TESTCASE # 84  E= 0           R=-.801861     X= 1.94745E+8                      
               F= 0           N=-.801861                                        
*** TEST PASSED ***                                                             
TESTCASE # 85  E= 0           R= .160414     X= 2.02475E+9                      
               F= 0           N= .160414                                        
*** TEST PASSED ***                                                             
TESTCASE # 86  E= 0           R= 1.17816     X=-2.26748E+9                      
               F= 0           N= 1.17816                                        
*** TEST PASSED ***                                                             
TESTCASE # 87  E= 0           R=-5.61655E-2  X=-2.10587E+9                      
               F= 0           N=-5.61655E-2                                     
*** TEST PASSED ***                                                             
TESTCASE # 88  E= 0           R= 2.82231     X= 4.23585E+9                      
               F= 0           N= 2.82231                                        
*** TEST PASSED ***                                                             
TESTCASE # 89  E= 0           R=-.166401     X=-2.66524E+9                      
               F= 0           N=-.166401                                        
*** TEST PASSED ***                                                             
TESTCASE # 90  E= 0           R=-1.07964     X= 4.01052E+9                      
               F= 0           N=-1.07964                                        
*** TEST PASSED ***                                                             
TESTCASE # 91  E= 0           R= .406664     X=-4.87912E+9                      
               F= 0           N= .406664                                        
*** TEST PASSED ***                                                             
TESTCASE # 92  E= 0           R=-25.4693     X= 1.77556E+9                      
               F= 0           N=-25.4693                                        
*** TEST PASSED ***                                                             
TESTCASE # 93  E= 0           R=-.705126     X= 2.87705E+8                      
               F= 0           N=-.705126                                        
*** TEST PASSED ***                                                             
TESTCASE # 94  E= 0           R= .357809     X= 1.99977E+8                      
               F= 0           N= .357809                                        
*** TEST PASSED ***                                                             
TESTCASE # 95  E= 0           R=-.689009     X=-3.39941E+9                      
               F= 0           N=-.689009                                        
*** TEST PASSED ***                                                             
TESTCASE # 96  E= 0           R= 6.87334     X=-3.49119E+9                      
               F= 0           N= 6.87334                                        
*** TEST PASSED ***                                                             
TESTCASE # 97  E= 0           R= 18.8431     X=-2.86324E+9                      
               F= 0           N= 18.8431                                        
*** TEST PASSED ***                                                             
TESTCASE # 98  E= 0           R= 1.34211     X= 4.20418E+9                      
               F= 0           N= 1.34211                                        
*** TEST PASSED ***                                                             
TESTCASE # 99  E= 0           R=-1.16396     X=-3.1518E+9                       
               F= 0           N=-1.16396                                        
*** TEST PASSED ***                                                             
TESTCASE # 100                E= 0           R= .971919     X= 4.60615E+9       
               F= 0           N= .971919                                        
*** TEST PASSED ***                                                             
*** ALL TESTS PASSED ***                                                        
