100. Enter CONT at the command line.  Next line should be 120                   
                                                                                
Program interrupted at line 110                                                 
bwBASIC: CONT                                                                   
120. Enter CONT at the command line.  Next line should be 140                   
bwBASIC: CONT                                                                   
140. Enter CONT at the command line.  Next line should be 100                   
bwBASIC: CONT                                                                   
100. Enter CONT at the command line.  Next line should be 120                   
                                                                                
Program interrupted at line 110                                                 
bwBASIC: CONT                                                                   
120. Enter CONT at the command line.  Next line should be 140                   
bwBASIC: CONT                                                                   
140. Enter CONT at the command line.  Next line should be 100                   
bwBASIC: CONT                                                                   
100. Enter CONT at the command line.  Next line should be 120                   
                                                                                
Program interrupted at line 110                                                 
bwBASIC: CONT                                                                   
120. Enter CONT at the command line.  Next line should be 140                   
bwBASIC: CONT                                                                   
140. Enter CONT at the command line.  Next line should be 100                   
TEST COMPLETED                                                                  
                                                                                
