REGULAR PAYMENT ON A LOAN                                                       
                                                                                
TERM IN YEARS? 30                                                               
PRINCIPAL? 456789                                                               
ANNUAL INTEREST RATE? 3.75                                                      
NUMBER OF PAYMENTS PER YEAR? 12                                                 
REGULAR PAYMENT = $ 2115.46                                                     
                                                                                
MORE DATA? (1=YES, 0=NO)? 0                                                     
