                                                                                
THIS PROGRAM IS DESIGNED TO SELECT THE                                          
PROPER VALUES OF RESISTANCE AND CAPA-                                           
CITANCE FOR THE PROPER OPERATION OF THE                                         
567 TONE DECODER.                                                               
                                                                                
ENTER THE DESIRED FREQUENCY OF OPERATION                                        
? 1000                                                                          
                                                                                
                                                                                
                                                                                
THE FOLLOWING VALUES OF RESISTANCE                                              
AND CAPACITANCE DETERMINE THE FRE-                                              
QUENCY OF 1000 HZ                                                               
                                                                                
                                                                                
SET 1 :                                                                         
R1 = 100 OHMS                                                                   
C1 = 10 UF                                                                      
                                                                                
                                                                                
                                                                                
SET 2 :                                                                         
R1 = 220. OHMS                                                                  
C1 = 4.54545 UF                                                                 
                                                                                
                                                                                
                                                                                
SET 3 :                                                                         
R1 = 470 OHMS                                                                   
C1 = 2.12766 UF                                                                 
                                                                                
                                                                                
                                                                                
SET 4 :                                                                         
R1 = 1000 OHMS                                                                  
C1 = 1 UF                                                                       
                                                                                
                                                                                
                                                                                
SET 5 :                                                                         
R1 = 2200 OHMS                                                                  
C1 = .454545 UF                                                                 
                                                                                
                                                                                
                                                                                
SET 6 :                                                                         
R1 = 4700 OHMS                                                                  
C1 = .212766 UF                                                                 
                                                                                
                                                                                
                                                                                
SET 7 :                                                                         
R1 = 10000 OHMS                                                                 
C1 = .1 UF                                                                      
                                                                                
                                                                                
                                                                                
SET 8 :                                                                         
R1 = 22000 OHMS                                                                 
C1 = 4.54545E-2 UF                                                              
                                                                                
                                                                                
                                                                                
SET 9 :                                                                         
R1 = 47000 OHMS                                                                 
C1 = 2.12766E-2 UF                                                              
                                                                                
                                                                                
                                                                                
SET 10 :                                                                        
R1 = 100000 OHMS                                                                
C1 = .01 UF                                                                     
                                                                                
                                                                                
                                                                                
SET 11 :                                                                        
R1 = 220000. OHMS                                                               
C1 = 4.54545E-3 UF                                                              
                                                                                
                                                                                
                                                                                
SET 12 :                                                                        
R1 = 470000 OHMS                                                                
C1 = 2.12766E-3 UF                                                              
                                                                                
                                                                                
                                                                                
SET 13 :                                                                        
R1 = 1.E+6 OHMS                                                                 
C1 = .001 UF                                                                    
                                                                                
