 *                                                                              
                   -=*AUDIO LAB PROGRAM*=-                                      
Select the program you require from the following menu                          
         (0) Exit from program. (Changed my mind)                               
         (1) Calculate power, given voltage and impedance                       
         (2) Calculate voltage, given power and impedance                       
         (3) Calculate the dB ratio of two voltages                             
         (4) Calculate the dB ratio of two power values                         
         (5) Change percent (%), to dB                                          
         (6) Change dB to percent (%)                                           
         (7) Calculate dBf, given a number in microvolts                        
         (8) Calculate microvolts (uV), given dBf                               
         (9) Damping factor of an amplifier with 8-ohm loads                    
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
ENTER THE NUMBER OF YOUR CHOICE AND PRESS 'RETURN'                              
? 1                                                                             
To calculate POWER enter the VOLTAGE                                            
? 120                                                                           
Now enter the impedance, in ohms                                                
? 50                                                                            
Power equals>  288 < watts                                                      
DO YOU WISH TO DO THIS CALCULATION AGAIN? (Y/N)                                 
? N                                                                             
                                                                                
                                                                                
Do you wish to return to the menu? (Y/N)                                        
? Y                                                                             
 *                                                                              
                   -=*AUDIO LAB PROGRAM*=-                                      
Select the program you require from the following menu                          
         (0) Exit from program. (Changed my mind)                               
         (1) Calculate power, given voltage and impedance                       
         (2) Calculate voltage, given power and impedance                       
         (3) Calculate the dB ratio of two voltages                             
         (4) Calculate the dB ratio of two power values                         
         (5) Change percent (%), to dB                                          
         (6) Change dB to percent (%)                                           
         (7) Calculate dBf, given a number in microvolts                        
         (8) Calculate microvolts (uV), given dBf                               
         (9) Damping factor of an amplifier with 8-ohm loads                    
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
ENTER THE NUMBER OF YOUR CHOICE AND PRESS 'RETURN'                              
? 2                                                                             
To calculate VOLTAGE,for a given power, enter POWER, in watts                   
? 1000                                                                          
Now enter the load impedance, in ohms                                           
? 50                                                                            
Voltage for that power equals>  223.607 < volts                                 
DO YOU WISH TO DO THIS CALCULATION AGAIN? (Y/N)                                 
? N                                                                             
                                                                                
                                                                                
Do you wish to return to the menu? (Y/N)                                        
? Y                                                                             
 *                                                                              
                   -=*AUDIO LAB PROGRAM*=-                                      
Select the program you require from the following menu                          
         (0) Exit from program. (Changed my mind)                               
         (1) Calculate power, given voltage and impedance                       
         (2) Calculate voltage, given power and impedance                       
         (3) Calculate the dB ratio of two voltages                             
         (4) Calculate the dB ratio of two power values                         
         (5) Change percent (%), to dB                                          
         (6) Change dB to percent (%)                                           
         (7) Calculate dBf, given a number in microvolts                        
         (8) Calculate microvolts (uV), given dBf                               
         (9) Damping factor of an amplifier with 8-ohm loads                    
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
ENTER THE NUMBER OF YOUR CHOICE AND PRESS 'RETURN'                              
? 0                                                                             
Happy to have been of service!! SEE YOU LATER!!                                 
