                                                                                
                        EXTENDED PRECISION CALCULATOR                           
                                                                                
                             JUDSON D. MCCLENDON                                
                                                                                
                    Modified for S-Basic by R.J. Sandel                         
                                                                                
                                                                                
                                                                                
                                                                                
Legal commands are: ADD, SUB, MUL, & DIV for math operations                    
                                                                                
A or EA for Enter into Register A:   PA for Print A:   CA for Clear A           
                                                                                
XAB for Exchange A and B:   MAB for Move A into B:   similar for other registers
                                                                                
ZAP for Clear All:         END or QUIT or Q for termination.                    
                                                                                
                                                                                
Warning !!! 100 place divisions take a while !!!                                
                                                                                
                                                                                
                             Enter maximum (10 to 100) precision desired ? 10   
                                                                                
                                                                                
A: 0                                                                            
B: 0                                                                            
C: 0                                                                            
                                                                                
ENTER COMMAND: EA                                                               
Enter A: 1234567.89                                                             
                                                                                
A: 1,234,567.89                                                                 
B: 0                                                                            
C: 0                                                                            
                                                                                
ENTER COMMAND: EB                                                               
Enter B: 9876543.21                                                             
                                                                                
A: 1,234,567.89                                                                 
B: 9,876,543.21                                                                 
C: 0                                                                            
                                                                                
ENTER COMMAND: ADD                                                              
                                                                                
 B = B + A                                                                      
                                                                                
                                                                                
A: 1,234,567.89                                                                 
B: 11,111,111.1                                                                 
C: 0                                                                            
                                                                                
ENTER COMMAND: XAB                                                              
                                                                                
A: 11,111,111.1                                                                 
B: 1,234,567.89                                                                 
C: 0                                                                            
                                                                                
ENTER COMMAND: XAB                                                              
                                                                                
A: 1,234,567.89                                                                 
B: 11,111,111.1                                                                 
C: 0                                                                            
                                                                                
ENTER COMMAND: DIV                                                              
                                                                                
 C = B / A                                                                      
                                                                                
                                                                                
A: 1,234,567.89                                                                 
B: 11,111,111.1                                                                 
C: 9.000,000,07                                                                 
                                                                                
ENTER COMMAND: QUIT                                                             
