Elkins Log(10k!) Benchmark                                                      
                                                                                
Note the Start Time!                                                            
Note the End Time!                                                              
                                                                                
Error:  .545725                                                                 
