                                                                                
   DO YOU WISH:                                                                 
     (R)ESISTOR (1 OHM-100 MEG)                                                 
     (C)APACITOR (1PF-1000 MFD)                                                 
     (E)XIT                                                                     
                                                                                
? R                                                                             
                                                                                
NUMBER OF RESISTORS TO BE ENTERED:                                              
? 1                                                                             
                                                                                
ENTER THE RESISTOR VALUES USING THE POWER OF TEN FORMAT.                        
ERRORS MAY BE CORRECTED AFTER ALL VALUES HAVE BEEN ENTERED.                     
R 1 =                                                                           
? 123                                                                           
                                                                                
                                                                                
 R 1 = 123                                                                      
ARE THESE VALUES CORRECT (Y/N)? Y                                               
                                                                                
     CALCULATING STANDARD VALUES                                                
                                                                                
 R 1 = 120 OHMS                                                                 
                                                                                
DO YOU WANT HARDCOPY (Y/N)? Y                                                   
                                                                                
   DO YOU WISH:                                                                 
     (R)ESISTOR (1 OHM-100 MEG)                                                 
     (C)APACITOR (1PF-1000 MFD)                                                 
     (E)XIT                                                                     
                                                                                
? C                                                                             
                                                                                
NUMBER OF CAPACITORS TO BE ENTERED:                                             
? 1                                                                             
                                                                                
ENTER THE VALUE OF CAPACITOR,IN MFD.,USING THE POWER OF TEN FORMAT.             
ERRORS MAY BE CORRECTED AFTER ALL THE VALUES HAVE BEEN ENTERED.                 
C 1 =                                                                           
? 12.34e-6                                                                      
                                                                                
                                                                                
 C 1 = 1.234E-5                                                                 
ARE THESE VALUES CORRECT (Y/N)? Y                                               
                                                                                
     CALCULATING STANDARD VALUES                                                
                                                                                
 C 1 = 12 PF                                                                    
                                                                                
DO YOU WANT HARDCOPY (Y/N)? Y                                                   
                                                                                
   DO YOU WISH:                                                                 
     (R)ESISTOR (1 OHM-100 MEG)                                                 
     (C)APACITOR (1PF-1000 MFD)                                                 
     (E)XIT                                                                     
                                                                                
? E                                                                             
                                                                                
GOODBYE                                                                         
                                                                                
